import { env } from "cloudflare:workers";
import { decryptPrintifyToken } from "../../token-crypto";
import { etsyBudget } from "../../../etsy/client";
import { finishEtsyListing } from "../../../etsy/finish";

type Settings={printifyImageIndices:number[];printifyImageSelections:Record<string,number[]>;etsyShippingProfileId:number};
type Draft={id:string;batchId?:string;shopId:number;title?:string;tags?:string[];description?:string;etsyDetails?:unknown};
type Runtime={DB:D1Database;PRINTIFY_TOKEN_KEY?:string};
const runtime=()=>env as unknown as Runtime;
const MAX_CONCURRENT_LISTINGS=4;
const RESERVED_CALLS_PER_LISTING=25;
const printifyHeaders=(token:string)=>({Authorization:`Bearer ${token}`,"User-Agent":"Goldie-Listing-Factory"});

async function printifyListingId(token:string,shopId:number,productId:string){const response=await fetch(`https://api.printify.com/v1/shops/${shopId}/products/${productId}.json`,{headers:printifyHeaders(token)});if(!response.ok)return 0;const product=await response.json() as {external?:{id?:string}};return Number(product.external?.id)||0}
async function waitForEtsyListing(token:string,shopId:number,productId:string){for(let attempt=0;attempt<18;attempt++){if(attempt)await new Promise(resolve=>setTimeout(resolve,2500));const id=await printifyListingId(token,shopId,productId);if(id>0)return id}throw new Error("Printify published the product, but has not returned its Etsy listing ID yet. Goldie will retry this listing safely.")}
async function refreshJob(jobId:string){const totals=await runtime().DB.prepare("SELECT SUM(CASE WHEN status='completed' THEN 1 ELSE 0 END) completed,SUM(CASE WHEN status='failed' THEN 1 ELSE 0 END) failed,SUM(CASE WHEN status IN ('queued','running') THEN 1 ELSE 0 END) pending FROM etsy_publish_items WHERE job_id=?").bind(jobId).first<{completed:number;failed:number;pending:number}>();const completed=Number(totals?.completed||0),failed=Number(totals?.failed||0),pending=Number(totals?.pending||0),status=pending?"processing":failed?"needs_attention":"completed";await runtime().DB.prepare("UPDATE etsy_publish_jobs SET status=?,completed=?,failed=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(status,completed,failed,jobId).run()}

export async function processNextPublishItem(userId:string,jobId:string){
  const now=Math.floor(Date.now()/1000);await runtime().DB.prepare("UPDATE etsy_publish_items SET status='queued',locked_at=NULL,available_at=?,updated_at=CURRENT_TIMESTAMP WHERE status='running' AND locked_at<?").bind(now,now-300).run();
  const [budget,running]=await Promise.all([etsyBudget(),runtime().DB.prepare("SELECT COUNT(*) count FROM etsy_publish_items WHERE status='running' AND locked_at>=?").bind(now-300).first<{count:number}>()]),active=Number(running?.count||0);
  if(active>=MAX_CONCURRENT_LISTINGS||budget.remaining-active*RESERVED_CALLS_PER_LISTING<RESERVED_CALLS_PER_LISTING)return {waitingForQuota:true,budget};
  const item=await runtime().DB.prepare("SELECT id,product_id,attempts FROM etsy_publish_items WHERE job_id=? AND user_id=? AND status='queued' AND available_at<=? ORDER BY created_at,id LIMIT 1").bind(jobId,userId,now).first<{id:string;product_id:string;attempts:number}>();
  if(!item){await refreshJob(jobId);return {waiting:false,budget}}const claimed=await runtime().DB.prepare("UPDATE etsy_publish_items SET status='running',locked_at=?,attempts=attempts+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='queued'").bind(now,item.id).run();if(!claimed.meta.changes)return {waiting:false,budget};
  try{
    const job=await runtime().DB.prepare("SELECT settings_json FROM etsy_publish_jobs WHERE id=? AND user_id=?").bind(jobId,userId).first<{settings_json:string}>(),row=await runtime().DB.prepare("SELECT response_json FROM printify_draft_results WHERE user_id=? AND status='succeeded' AND json_extract(response_json,'$.id')=? LIMIT 1").bind(userId,item.product_id).first<{response_json:string}>();if(!job||!row)throw new Error("Goldie could not reload this listing safely.");
    const settings=JSON.parse(job.settings_json) as Settings,draft=JSON.parse(row.response_json) as Draft,connection=await runtime().DB.prepare("SELECT encrypted_token FROM printify_connections WHERE user_id=?").bind(userId).first<{encrypted_token:string}>(),secret=runtime().PRINTIFY_TOKEN_KEY;if(!connection||!secret)throw new Error("Reconnect Printify so Goldie can continue this queued batch.");const token=await decryptPrintifyToken(connection.encrypted_token,secret);
    const linked=await runtime().DB.prepare("SELECT etsy_listing_id FROM etsy_listing_links WHERE printify_product_id=? AND user_id=? AND etsy_listing_id>0").bind(draft.id,userId).first<{etsy_listing_id:number}>();let listingId=Number(linked?.etsy_listing_id)||await printifyListingId(token,draft.shopId,draft.id);
    if(!listingId){const response=await fetch(`https://api.printify.com/v1/shops/${draft.shopId}/products/${draft.id}/publish.json`,{method:"POST",headers:{...printifyHeaders(token),"Content-Type":"application/json"},body:JSON.stringify({title:true,description:true,images:true,variants:true,tags:true,keyFeatures:true,shipping_template:true})});if(!response.ok)throw new Error(`Printify could not publish this listing (${response.status}).`);listingId=await waitForEtsyListing(token,draft.shopId,draft.id)}
    await runtime().DB.prepare("INSERT INTO etsy_listing_links (printify_product_id,user_id,batch_id,etsy_listing_id,status,last_error,updated_at) VALUES (?,?,?,?, 'finishing',NULL,CURRENT_TIMESTAMP) ON CONFLICT(printify_product_id) DO UPDATE SET etsy_listing_id=excluded.etsy_listing_id,status='finishing',last_error=NULL,updated_at=CURRENT_TIMESTAMP").bind(draft.id,userId,draft.batchId||"",listingId).run();
    const selection=Array.isArray(settings.printifyImageSelections[draft.id])?[...new Set(settings.printifyImageSelections[draft.id].map(Number).filter(value=>Number.isInteger(value)&&value>=0))]:settings.printifyImageIndices,before=budget.used,result=await finishEtsyListing(userId,{...draft,etsyShippingProfileId:settings.etsyShippingProfileId,etsyDetails:draft.etsyDetails as {category?:string;attributes?:Record<string,string>;optional?:Record<string,string>}},listingId,selection),after=await etsyBudget(),apiCalls=Math.max(0,after.used-before),resultJson=JSON.stringify({printifyProductId:draft.id,etsyListingId:listingId,url:result.url});
    await runtime().DB.batch([runtime().DB.prepare("UPDATE etsy_publish_items SET status='completed',result_json=?,last_error=NULL,locked_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(resultJson,item.id),runtime().DB.prepare("INSERT INTO etsy_listing_usage (user_product,user_id,product_id,job_id,etsy_listing_id,api_calls,published_at) VALUES (?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(user_product) DO UPDATE SET job_id=excluded.job_id,etsy_listing_id=excluded.etsy_listing_id,api_calls=excluded.api_calls").bind(`${userId}:${draft.id}`,userId,draft.id,jobId,listingId,apiCalls)]);
  }catch(error){const message=error instanceof Error?error.message:"Goldie could not finish this listing.",attempt=item.attempts+1,retryable=attempt<5&&!/different shop|missing|required listing field|Choose an Etsy shipping profile/i.test(message),delay=Math.min(900,30*2**Math.max(0,attempt-1));await runtime().DB.prepare("UPDATE etsy_publish_items SET status=?,available_at=?,last_error=?,locked_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(retryable?"queued":"failed",retryable?now+delay:0,message,item.id).run();if(!retryable)await runtime().DB.prepare("UPDATE etsy_publish_jobs SET last_error=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(message,jobId).run()}
  await refreshJob(jobId);return {waiting:false,budget:await etsyBudget()};
}

export async function processNextGlobalPublishItem(){
  const now=Math.floor(Date.now()/1000),next=await runtime().DB.prepare("SELECT user_id,job_id FROM etsy_publish_items WHERE status='queued' AND available_at<=? ORDER BY created_at,id LIMIT 1").bind(now).first<{user_id:string;job_id:string}>();
  return next?processNextPublishItem(next.user_id,next.job_id):{waiting:false,budget:await etsyBudget()};
}

export async function publishJobPayload(userId:string,jobId:string){const job=await runtime().DB.prepare("SELECT id,status,total,completed,failed,last_error,created_at,updated_at FROM etsy_publish_jobs WHERE id=? AND user_id=?").bind(jobId,userId).first<{id:string;status:string;total:number;completed:number;failed:number;last_error?:string;created_at:string;updated_at:string}>();if(!job)return null;const rows=await runtime().DB.prepare("SELECT status,result_json,last_error,available_at FROM etsy_publish_items WHERE job_id=? AND user_id=? ORDER BY created_at,id").bind(jobId,userId).all<{status:string;result_json?:string;last_error?:string;available_at:number}>(),finished=rows.results.flatMap(row=>row.result_json?[JSON.parse(row.result_json)]:[]),nextRetry=Math.min(...rows.results.filter(row=>row.status==="queued"&&row.available_at>0).map(row=>row.available_at),Infinity);return {...job,finished,queued:rows.results.filter(row=>row.status==="queued").length,processing:rows.results.filter(row=>row.status==="running").length,nextRetry:Number.isFinite(nextRetry)?nextRetry:null,budget:await etsyBudget()}}
