import { env } from "cloudflare:workers";
import { NextResponse } from "next/server";
import { getChatGPTUser } from "@/app/chatgpt-auth";
import { monthKey, planFor } from "@/app/plan-limits";
import { processNextGlobalPublishItem, publishJobPayload } from "./queue";
import { isOwner } from "@/app/mastermind/access";

export async function POST(request:Request){
  const user=await getChatGPTUser();if(!user)return NextResponse.json({error:"Sign in to publish these listings."},{status:401});
  const body=await request.json() as {productIds?:string[];printifyImageIndices?:number[];printifyImageSelections?:Record<string,number[]>;etsyShippingProfileId?:number},ids=[...new Set((body.productIds||[]).map(String).filter(Boolean))],etsyShippingProfileId=Number(body.etsyShippingProfileId);
  if(!ids.length)return NextResponse.json({error:"Choose at least one completed listing."},{status:400});if(!Number.isInteger(etsyShippingProfileId)||etsyShippingProfileId<=0)return NextResponse.json({error:"Choose an Etsy shipping profile before publishing."},{status:400});
  const rows=await env.DB.prepare(`SELECT response_json FROM printify_draft_results WHERE user_id=? AND status='succeeded' AND json_extract(response_json,'$.id') IN (${ids.map(()=>"?").join(",")})`).bind(user.userId,...ids).all<{response_json:string}>();if(rows.results.length!==ids.length)return NextResponse.json({error:"One or more listings do not belong to this Listing Factory account."},{status:403});
  /* D475 - pressing Publish again could not retry a failed listing. If any one
     item was still queued, the `existing` check below returned the old job
     immediately and never reached the upsert that re-queues the rest, so the
     failed ones stayed failed forever. And even when it did reach the upsert,
     attempts was never reset, so a listing that had used up its retries could
     never be tried again. Her retry is now a real retry. */
  await env.DB.prepare(`UPDATE etsy_publish_items SET status='queued',attempts=0,available_at=0,locked_at=NULL,last_error=NULL,updated_at=CURRENT_TIMESTAMP WHERE user_id=? AND status='failed' AND product_id IN (${ids.map(()=>"?").join(",")})`).bind(user.userId,...ids).run();
  /* D476 - D475 re-queued the failed items but left the job row saying
     needs_attention. That status is terminal: the GET below refuses to run the
     queue on a terminal job, and the browser stops polling the moment it sees
     one. So publish spun for a second and stopped without attempting anything,
     and the failure panel was empty because the items were no longer failed.
     Re-queuing an item has to revive its job in the same breath. */
  await env.DB.prepare(`UPDATE etsy_publish_jobs SET status='processing',failed=0,last_error=NULL,updated_at=CURRENT_TIMESTAMP WHERE user_id=? AND id IN (SELECT DISTINCT job_id FROM etsy_publish_items WHERE user_id=? AND status IN ('queued','running') AND product_id IN (${ids.map(()=>"?").join(",")}))`).bind(user.userId,user.userId,...ids).run();
  const existing=await env.DB.prepare(`SELECT job_id FROM etsy_publish_items WHERE user_id=? AND product_id IN (${ids.map(()=>"?").join(",")}) AND status IN ('queued','running') LIMIT 1`).bind(user.userId,...ids).first<{job_id:string}>();if(existing)return NextResponse.json({ok:true,resumed:true,job:await publishJobPayload(user.userId,existing.job_id)});
  const completed=await env.DB.prepare(`SELECT job_id,COUNT(*) count FROM etsy_publish_items WHERE user_id=? AND product_id IN (${ids.map(()=>"?").join(",")}) AND status='completed' GROUP BY job_id ORDER BY count DESC LIMIT 1`).bind(user.userId,...ids).first<{job_id:string;count:number}>();if(Number(completed?.count||0)===ids.length)return NextResponse.json({ok:true,resumed:true,job:await publishJobPayload(user.userId,completed!.job_id)});
  const [etsy,printify,planRow,monthUsed,dayUsed,pending]=await Promise.all([env.DB.prepare("SELECT shop_id FROM etsy_connections WHERE user_id=?").bind(user.userId).first(),env.DB.prepare("SELECT 1 ready FROM printify_connections WHERE user_id=?").bind(user.userId).first(),env.DB.prepare("SELECT plan_key FROM account_plans WHERE user_id=?").bind(user.userId).first<{plan_key:string}>(),env.DB.prepare("SELECT COUNT(*) count FROM etsy_listing_usage WHERE user_id=? AND substr(published_at,1,7)=?").bind(user.userId,monthKey()).first<{count:number}>(),env.DB.prepare("SELECT COUNT(*) count FROM etsy_listing_usage WHERE user_id=? AND published_at>=datetime('now','-24 hours')").bind(user.userId).first<{count:number}>(),env.DB.prepare("SELECT COUNT(*) count FROM etsy_publish_items WHERE user_id=? AND status IN ('queued','running')").bind(user.userId).first<{count:number}>()]);
  if(!etsy)return NextResponse.json({error:"Connect Etsy before publishing. Goldie will not publish listings it cannot finish safely."},{status:400});if(!printify)return NextResponse.json({error:"Reconnect Printify before publishing."},{status:401});
  const plan=planFor(planRow?.plan_key,isOwner(user)),reserved=Number(pending?.count||0),monthlyRemaining=plan.drafts-Number(monthUsed?.count||0)-reserved,dailyRemaining=plan.dailyListings-Number(dayUsed?.count||0)-reserved;
  if(ids.length>monthlyRemaining)return NextResponse.json({error:`This batch would exceed your ${plan.drafts}-listing monthly allowance. You can queue ${Math.max(0,monthlyRemaining)} more ${monthlyRemaining===1?"listing":"listings"} this month.`},{status:429});if(ids.length>dailyRemaining)return NextResponse.json({error:`Goldie can publish ${Math.max(0,dailyRemaining)} more ${dailyRemaining===1?"listing":"listings"} for this account within the current 24-hour window. Your monthly listings remain available.`},{status:429});
  const proposedJobId=crypto.randomUUID(),drafts=rows.results.map(row=>JSON.parse(row.response_json) as {id:string;batchId?:string}),batchId=drafts[0]?.batchId||proposedJobId,settings=JSON.stringify({printifyImageIndices:[...new Set((body.printifyImageIndices||[]).map(Number).filter(Number.isInteger))],printifyImageSelections:body.printifyImageSelections||{},etsyShippingProfileId});
  await env.DB.prepare("INSERT INTO etsy_publish_jobs (id,user_id,batch_id,status,total,settings_json) VALUES (?,?,?,'queued',?,?) ON CONFLICT(user_id,batch_id) DO UPDATE SET status='queued',settings_json=excluded.settings_json,total=MAX(etsy_publish_jobs.total,excluded.total),failed=0,last_error=NULL,updated_at=CURRENT_TIMESTAMP").bind(proposedJobId,user.userId,batchId,ids.length,settings).run();
  const canonical=await env.DB.prepare("SELECT id FROM etsy_publish_jobs WHERE user_id=? AND batch_id=?").bind(user.userId,batchId).first<{id:string}>(),jobId=canonical?.id||proposedJobId;
  await env.DB.batch(ids.map(productId=>env.DB.prepare("INSERT INTO etsy_publish_items (id,job_id,user_id,product_id,status,available_at) VALUES (?,?,?,?,'queued',0) ON CONFLICT(user_id,product_id) DO UPDATE SET job_id=excluded.job_id,status=CASE WHEN etsy_publish_items.status='completed' THEN 'completed' ELSE 'queued' END,attempts=0,available_at=0,last_error=NULL,locked_at=NULL,updated_at=CURRENT_TIMESTAMP").bind(crypto.randomUUID(),jobId,user.userId,productId)));
  return NextResponse.json({ok:true,job:await publishJobPayload(user.userId,jobId)},{status:202});
}

export async function GET(request:Request){const user=await getChatGPTUser();if(!user)return NextResponse.json({error:"Sign in to view this publish job."},{status:401});const jobId=new URL(request.url).searchParams.get("jobId")||"";if(!jobId)return NextResponse.json({error:"A publish job is required."},{status:400});const current=await publishJobPayload(user.userId,jobId);if(!current)return NextResponse.json({error:"This publish job was not found."},{status:404});if(current.queued+current.processing>0)await processNextGlobalPublishItem();/* D476 - was gated on the job's status string, which could say needs_attention while items sat queued underneath it, stalling the queue permanently. */return NextResponse.json({ok:true,job:await publishJobPayload(user.userId,jobId)})}
