import { env } from "cloudflare:workers";
import { NextResponse } from "next/server";
import { getChatGPTUser } from "@/app/chatgpt-auth";
import { decryptPrintifyToken } from "../../token-crypto";
import { finishEtsyListing } from "../../../etsy/finish";

async function waitForEtsyListing(token:string,shopId:number,productId:string){for(let attempt=0;attempt<18;attempt++){if(attempt)await new Promise(resolve=>setTimeout(resolve,2500));const response=await fetch(`https://api.printify.com/v1/shops/${shopId}/products/${productId}.json`,{headers:{Authorization:`Bearer ${token}`,"User-Agent":"Goldie-Listing-Factory"}});if(!response.ok)continue;const product=await response.json() as {external?:{id?:string}};const id=Number(product.external?.id);if(id>0)return id}throw new Error("Printify published the product, but has not returned its Etsy listing ID yet. Goldie did not guess which listing to edit.")}

export async function POST(request:Request){
  const user=await getChatGPTUser();if(!user)return NextResponse.json({error:"Sign in to publish these listings."},{status:401});
  const body=await request.json() as {productIds?:string[];printifyImageIndices?:number[];printifyImageSelections?:Record<string,number[]>;etsyShippingProfileId?:number},ids=[...new Set((body.productIds||[]).map(String).filter(Boolean))],printifyImageIndices=[...new Set((body.printifyImageIndices||[]).map(Number).filter(value=>Number.isInteger(value)&&value>=0))],printifyImageSelections=body.printifyImageSelections||{},etsyShippingProfileId=Number(body.etsyShippingProfileId);
  if(!ids.length)return NextResponse.json({error:"Choose at least one completed listing."},{status:400});
  if(!Number.isInteger(etsyShippingProfileId)||etsyShippingProfileId<=0)return NextResponse.json({error:"Choose an Etsy shipping profile before publishing."},{status:400});
  const rows=await env.DB.prepare(`SELECT response_json FROM printify_draft_results WHERE user_id=? AND status='succeeded' AND json_extract(response_json,'$.id') IN (${ids.map(()=>"?").join(",")})`).bind(user.userId,...ids).all<{response_json:string}>();
  if(rows.results.length!==ids.length)return NextResponse.json({error:"One or more listings do not belong to this Goldie account."},{status:403});
  const etsy=await env.DB.prepare("SELECT shop_id FROM etsy_connections WHERE user_id=?").bind(user.userId).first<{shop_id:number}>();if(!etsy)return NextResponse.json({error:"Connect Etsy before publishing. Goldie will not publish listings it cannot finish safely."},{status:400});
  const connection=await env.DB.prepare("SELECT encrypted_token FROM printify_connections WHERE user_id=?").bind(user.userId).first<{encrypted_token:string}>(),secret=(env as unknown as {PRINTIFY_TOKEN_KEY?:string}).PRINTIFY_TOKEN_KEY;
  if(!connection||!secret)return NextResponse.json({error:"Reconnect Printify before publishing."},{status:401});
  const token=await decryptPrintifyToken(connection.encrypted_token,secret),published:string[]=[];
  const finished:Array<{printifyProductId:string;etsyListingId:number;url:string}>=[];
  for(const row of rows.results){const draft=JSON.parse(row.response_json) as {id:string;batchId?:string;shopId:number;title?:string;tags?:string[];description?:string;etsyDetails?:unknown};const response=await fetch(`https://api.printify.com/v1/shops/${draft.shopId}/products/${draft.id}/publish.json`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json","User-Agent":"Goldie-Listing-Factory"},body:JSON.stringify({title:true,description:true,images:true,variants:true,tags:true,keyFeatures:true,shipping_template:true})});if(!response.ok)return NextResponse.json({error:`Printify stopped after ${published.length} listings because ${draft.id} could not be published (${response.status}).`,published,finished},{status:response.status});published.push(draft.id);try{const listingId=await waitForEtsyListing(token,draft.shopId,draft.id),selection=Array.isArray(printifyImageSelections[draft.id])?[...new Set(printifyImageSelections[draft.id].map(Number).filter(value=>Number.isInteger(value)&&value>=0))]:printifyImageIndices,result=await finishEtsyListing(user.userId,{...draft,etsyShippingProfileId,etsyDetails:draft.etsyDetails as {category?:string;attributes?:Record<string,string>;optional?:Record<string,string>}},listingId,selection);finished.push({printifyProductId:draft.id,etsyListingId:listingId,url:result.url})}catch(error){await env.DB.prepare("INSERT INTO etsy_listing_links (printify_product_id,user_id,batch_id,etsy_listing_id,status,last_error,updated_at) VALUES (?,?,?,?, 'needs_attention',?,CURRENT_TIMESTAMP) ON CONFLICT(printify_product_id) DO UPDATE SET status='needs_attention',last_error=excluded.last_error,updated_at=CURRENT_TIMESTAMP").bind(draft.id,user.userId,draft.batchId||"",0,error instanceof Error?error.message:"Etsy finishing failed.").run();return NextResponse.json({error:`${draft.title||draft.id} is live on Etsy, but Goldie stopped before finishing it: ${error instanceof Error?error.message:"Unknown Etsy error"}`,published,finished},{status:502})}}
  return NextResponse.json({ok:true,published,finished});
}
