"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import "../pricing-profile.css";
import GoldieWordmark from "../goldie-wordmark";
type PlanKey="trial"|"goldie"|"pro"|"scale"|"mastermind_beta";
type Data={plan:{key:PlanKey;name:string;price:number;drafts:number;dailyListings:number;aiMockups:number;mockupSets:number;mockupsPerSet:number};resetAt:string;usage:{drafts:number;aiMockups:number;mockupSets:number;publishedToday:number;publishing:number};billing?:{active:boolean;subscription?:{status:string;currentPeriodEnd:number|null;cancelAtPeriodEnd:number}|null}};
type Fees={etsyFeePercent:number;fixedFee:number;listingFee:number};
function Meter({label,used,limit,monthly=true}:{label:string;used:number;limit:number;monthly?:boolean}){const pct=Math.min(100,Math.round(used/limit*100));const warning=pct>=100?"Limit reached":pct>=95?"Almost at your limit":pct>=80?"You’re getting close":"Plenty of room";return <article className="usage-card"><div><h2>{label}</h2><b>{used} <span>/ {limit}{monthly?" this month":""}</span></b></div><div className="usage-track"><i style={{width:`${pct}%`}} /></div><p className={pct>=80?"usage-warning":""}>{warning}</p></article>}
export default function UsagePage(){
  const[data,setData]=useState<Data|null>(null),[loadError,setLoadError]=useState(""),[fees,setFees]=useState<Fees>({etsyFeePercent:9.5,fixedFee:.25,listingFee:.20}),[feeMessage,setFeeMessage]=useState(""),[billingMessage,setBillingMessage]=useState(""),[checkoutPlan,setCheckoutPlan]=useState<"goldie"|"pro"|"scale"|null>(null);
  useEffect(()=>{fetch("/api/usage").then(async response=>{const result=await response.json() as Partial<Data>&{error?:string};if(!response.ok||!result.plan||!result.usage||!result.resetAt)throw new Error(result.error||"Your usage could not be loaded.");setData(result as Data)}).catch(error=>setLoadError(error instanceof Error?error.message:"Your usage could not be loaded."));fetch("/api/seller-preferences").then(r=>r.json()).then(r=>{if(r.pricing)setFees(current=>({...current,...r.pricing}))}).catch(()=>undefined)},[]);
  async function saveFees(){setFeeMessage("Saving…");const response=await fetch("/api/seller-preferences",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pricing:fees})});setFeeMessage(response.ok?"Pricing profile saved for every future batch.":"Pricing profile could not be saved.")}
  async function manageBilling(){setBillingMessage("Opening secure billing…");const response=await fetch("/api/billing/portal",{method:"POST"}),result=await response.json() as {url?:string;error?:string};if(response.ok&&result.url){window.location.href=result.url;return}setBillingMessage(result.error||"Billing could not be opened.")}
  async function choosePlan(plan:"goldie"|"pro"|"scale"){if(data?.billing?.active){await manageBilling();return}setCheckoutPlan(plan);setBillingMessage("");const response=await fetch("/api/billing/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({plan})}),result=await response.json() as {url?:string;error?:string};if(response.ok&&result.url){window.location.href=result.url;return}setBillingMessage(result.error||"Secure checkout could not be opened.");setCheckoutPlan(null)}
  return <main className="usage-page">
    <nav className="management-nav"><GoldieWordmark/><Link href="/listing-factory">Listing Factory</Link><Link href="/batches">Batch History</Link><Link href="/keywords">Keyword Banks</Link><Link href="/mockups">Mockup Sets</Link><Link className="active" href="/usage">Usage + Plan</Link></nav>
    <header><p className="mini-label">USAGE + PLAN</p><h1>Your Listing Factory plan</h1><p>Your included credits reset automatically each month. Failed listing attempts and failed AI renders never use your allowance.</p></header>
    {loadError?<section className="usage-load-error" role="alert"><h2>Sign in to view your plan and usage</h2><p>{loadError}</p><Link href="/listing-factory">Return to Listing Factory</Link></section>:!data?<p>Loading your usage…</p>:<>
      <section className="plan-banner"><div><span>CURRENT PLAN</span><h2>{data.plan.name}</h2><p>{data.plan.price?`$${data.plan.price}/month`:"3-day trial"}</p></div><div><p>Resets {new Date(data.resetAt).toLocaleDateString(undefined,{month:"long",day:"numeric",year:"numeric"})}</p>{data.billing?.active&&<button onClick={()=>void manageBilling()}>Manage billing</button>}{billingMessage&&<small role="status">{billingMessage}</small>}</div></section>
      <section className="usage-grid"><Meter label="Listing creations" used={data.usage.drafts} limit={data.plan.drafts}/><Meter label="Listings published in 24 hours" used={data.usage.publishedToday+data.usage.publishing} limit={data.plan.dailyListings} monthly={false}/><Meter label="AI lifestyle mockups" used={data.usage.aiMockups} limit={data.plan.aiMockups}/><Meter label="Saved mockup sets" used={data.usage.mockupSets} limit={data.plan.mockupSets}/></section>
      <p className="usage-note">A credit is used only after Goldie successfully creates a unique listing or AI mockup. Failed attempts and retries do not count again. Each custom set can hold up to {data.plan.mockupsPerSet} mockups.</p>
      <section className="pricing-profile"><div><p className="mini-label">SAVED ONCE · USED IN EVERY LISTING SETUP</p><h2>Etsy fee profile</h2><p>The US defaults are 6.5% Etsy transaction + 3% Etsy Payments, $0.25 payment processing, and $0.20 listing/renewal. If your bank is outside the US, enter Etsy’s rates for your country once here.</p></div><div className="pricing-profile-grid"><label>Combined percentage fee<input type="number" min="0" max="40" step="0.1" value={fees.etsyFeePercent} onChange={e=>setFees({...fees,etsyFeePercent:Number(e.target.value)})}/><small>Transaction + payment processing + any regulatory fee</small></label><label>Fixed payment fee<input type="number" min="0" step="0.01" value={fees.fixedFee} onChange={e=>setFees({...fees,fixedFee:Number(e.target.value)})}/></label><label>Listing / renewal fee<input type="number" min="0" step="0.01" value={fees.listingFee} onChange={e=>setFees({...fees,listingFee:Number(e.target.value)})}/></label></div><button onClick={()=>void saveFees()}>Save pricing profile</button>{feeMessage&&<span role="status">{feeMessage}</span>}<small className="pricing-caveat">Goldie AI calculates a recommended minimum from each variant’s live Printify cost, Printify standard US shipping, buyer-paid shipping, and this fee profile. Etsy payment processing can also apply to buyer sales tax, which varies by order and cannot be known before the sale.</small></section>
      <section className="usage-plan-chooser" aria-labelledby="usage-plan-heading">
        <div className="usage-plan-heading"><p className="mini-label">PLANS + BILLING</p><h2 id="usage-plan-heading">Choose the plan that fits your listing volume</h2><p>Upgrade, downgrade, or manage your subscription whenever you need to.</p></div>
        <div className="usage-plan-grid">
          <article className={data.plan.key==="trial"?"current":""}><div><p>Free Trial</p>{data.plan.key==="trial"&&<span>CURRENT PLAN</span>}</div><h3>$0 <small>for 3 days</small></h3><ul><li>10 listing creations</li><li>6 AI lifestyle mockups</li><li>2 saved mockup sets</li><li>Then $29/month</li></ul>{data.plan.key==="trial"?<button disabled>Current plan</button>:<button disabled>Available to new customers</button>}</article>
          <article className={data.plan.key==="goldie"?"current":""}><div><p>Starter</p>{data.plan.key==="goldie"&&<span>CURRENT PLAN</span>}</div><h3>$29 <small>/month</small></h3><ul><li>100 listing creations each month</li><li>50 AI lifestyle mockups each month</li><li>10 saved mockup sets</li><li>Up to 50 mockups in each set</li></ul>{data.plan.key==="goldie"?<button onClick={()=>void manageBilling()}>Manage current plan</button>:<button disabled={Boolean(checkoutPlan)} onClick={()=>void choosePlan("goldie")}>{checkoutPlan==="goldie"?"Opening secure checkout…":data.billing?.active?"Switch to Starter":"Choose Starter"}</button>}</article>
          <article className={data.plan.key==="pro"?"current recommended":"recommended"}><div><p>Pro</p>{data.plan.key==="pro"?<span>CURRENT PLAN</span>:<span>MOST POPULAR</span>}</div><h3>$59 <small>/month</small></h3><ul><li>300 listing creations each month</li><li>150 AI lifestyle mockups each month</li><li>30 saved mockup sets</li><li>Up to 50 mockups in each set</li></ul>{data.plan.key==="pro"?<button onClick={()=>void manageBilling()}>Manage current plan</button>:<button disabled={Boolean(checkoutPlan)} onClick={()=>void choosePlan("pro")}>{checkoutPlan==="pro"?"Opening secure checkout…":data.billing?.active?"Switch to Pro":"Choose Pro"}</button>}</article>
          <article className={data.plan.key==="scale"?"current":""}><div><p>Scale</p>{data.plan.key==="scale"&&<span>CURRENT PLAN</span>}</div><h3>$99 <small>/month</small></h3><ul><li>750 listing creations each month</li><li>300 AI lifestyle mockups each month</li><li>75 saved mockup sets</li><li>Up to 50 mockups in each set</li></ul>{data.plan.key==="scale"?<button onClick={()=>void manageBilling()}>Manage current plan</button>:<button disabled={Boolean(checkoutPlan)} onClick={()=>void choosePlan("scale")}>{checkoutPlan==="scale"?"Opening secure checkout…":data.billing?.active?"Switch to Scale":"Choose Scale"}</button>}</article>
        </div>
        <p className="usage-plan-fineprint">One unique Etsy listing successfully created by Goldie uses one listing creation. A product bundle uses one creation for each listing it generates. Etsy’s standard $0.20 USD listing fee is charged separately by Etsy.</p>
        {billingMessage&&<p className="usage-billing-message" role="status">{billingMessage}</p>}
      </section>
    </>}
  </main>
}
