'use client';
import {useEffect,useState} from 'react';
import type {PlanFeature,SellerPlan} from '@/app/command-center-plan';
import './tools.css';
export default function ActionPlan({feature,source,heading:title,notes}:{feature:PlanFeature;source:string;heading:string;notes:string}){
 const [plans,setPlans]=useState<SellerPlan[]>([]),[editing,setEditing]=useState<Partial<SellerPlan>|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const url=`/api/command-center/plans?feature=${feature}&source=${encodeURIComponent(source)}`;
 useEffect(()=>{let active=true;setPlans([]);setEditing(null);setMessage('');fetch(url).then(async r=>{if(!r.ok)throw Error();return r.json() as Promise<{plans:SellerPlan[]}>}).then(b=>{if(active)setPlans(b.plans??[])}).catch(()=>{if(active)setMessage('Saved plans could not load. Reload to try again.')});return()=>{active=false}},[url]);
 const save=async()=>{if(!editing||busy)return;setBusy(true);setMessage('');try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing)});const b=await r.json() as {plan:SellerPlan;error?:string};if(!r.ok)throw Error(b.error||'Could not save.');setPlans(old=>[b.plan,...old.filter(p=>p.id!==b.plan.id)]);setEditing(null);setMessage('Plan saved.')}catch(e){setMessage(e instanceof Error?e.message:'Could not save.')}finally{setBusy(false)}};
 return <section className="cc-tool cc-plan"><div className="cc-tool-heading"><div><p className="mini-label">PUT IT TO WORK</p><h3>Your next move</h3><p>Keep the evidence, choose one change, and record what happened.</p></div><button type="button" className="p-button p-button-primary" onClick={()=>{setEditing({title,notes,outcome:'',status:'planned'});setMessage('')}}>Create a plan</button></div>
 {editing&&<div className="cc-plan-form"><label>Plan title<input maxLength={180} value={editing.title??''} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label>Evidence and change to test<textarea rows={6} maxLength={6000} value={editing.notes??''} onChange={e=>setEditing({...editing,notes:e.target.value})}/></label><label>Status<select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value as SellerPlan['status']})}><option value="planned">Planned</option><option value="testing">Testing</option><option value="finished">Finished</option></select></label><label>Result and what you learned<textarea rows={3} maxLength={3000} value={editing.outcome??''} onChange={e=>setEditing({...editing,outcome:e.target.value})} placeholder="What changed, over which dates, and would you repeat it?"/></label><div className="cc-actions"><button className="p-button p-button-primary" disabled={busy||!editing.title?.trim()} onClick={()=>void save()}>{busy?'Saving…':'Save plan'}</button><button className="p-button p-button-quiet" disabled={busy} onClick={()=>setEditing(null)}>Cancel</button></div></div>}
 {message&&<p role="status">{message}</p>}
 {plans.map(p=><details key={p.id} className="cc-saved-plan"><summary>{p.title} · {p.status}</summary><p className="cc-prewrap">{p.notes}</p>{p.outcome&&<p className="cc-prewrap"><b>Result</b>{'\n'}{p.outcome}</p>}<p>Saved {new Date(p.updatedAt*1000).toLocaleDateString()} · a record of your plan at that time</p><button className="p-button p-button-quiet" onClick={()=>setEditing({...p})}>Update plan</button></details>)}
 </section>;
}
