'use client';
import {useEffect,useRef,useState} from 'react';
import type {PlanFeature,SellerPlan} from '@/app/command-center-plan';
import './tools.css';
export default function ActionPlan({feature,source,heading:title,notes,context,expanded=false}:{feature:PlanFeature;source:string;heading:string;notes:string;context?:"shop";expanded?:boolean}){
 const [plans,setPlans]=useState<SellerPlan[]>([]),[editing,setEditing]=useState<Partial<SellerPlan>|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const url=`/api/command-center/plans?feature=${feature}&source=${encodeURIComponent(source)}`;
 const currentSource=useRef(url);currentSource.current=url;
 useEffect(()=>{let active=true;setPlans([]);setEditing(null);setMessage('');setBusy(false);fetch(url).then(async r=>{if(!r.ok)throw Error();return r.json() as Promise<{plans:SellerPlan[]}>}).then(b=>{if(active)setPlans(b.plans??[])}).catch(()=>{if(active)setMessage('Saved notes could not load. Reload to try again.')});return()=>{active=false}},[url]);
 const save=async()=>{if(!editing||busy)return;setBusy(true);setMessage('');try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing)});const b=await r.json() as {plan:SellerPlan;error?:string};if(currentSource.current!==url)return;if(!r.ok)throw Error(b.error||'Could not save.');setPlans(old=>[b.plan,...old.filter(p=>p.id!==b.plan.id)]);setEditing(null);setMessage('Notes saved.')}catch(e){if(currentSource.current===url)setMessage(e instanceof Error?e.message:'Could not save.')}finally{if(currentSource.current===url)setBusy(false)}};
 const copy=context==='shop'?['Notes for this shop','Save products, buyer feedback, or ideas you want to revisit. These notes stay in Goldie.']:feature==='marketWatch'?['Save this pricing comparison','Keep these prices and cost assumptions with your keyword so you can revisit the decision.']:feature==='designScanner'?['Design revision notes','Save the scan findings and the changes you want to make to this design.']:feature==='shopMap'?['Listing improvement notes','Keep the sales finding and your planned change together for this listing.']:['Phrase review notes','Save the matching marks and your notes about this phrase for a later review.'];
 return <details className="cc-tool cc-plan" open={expanded||undefined}><summary>{copy[0]}{plans.length>0?` · ${plans.length} saved`:''}</summary><div className="cc-tool-heading"><div><p>{copy[1]}</p></div><button type="button" className="p-button p-button-primary" disabled={busy} onClick={()=>{setEditing({title:title.slice(0,180),notes:notes.slice(0,6000),outcome:'',status:'planned'});setMessage('')}}>Add notes</button></div>
 {editing&&<div className="cc-plan-form"><label>Note title<input maxLength={180} value={editing.title??''} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label>Notes and supporting details<textarea rows={6} maxLength={6000} value={editing.notes??''} onChange={e=>setEditing({...editing,notes:e.target.value})}/></label><label>Status<select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value as SellerPlan['status']})}><option value="planned">Planned</option><option value="testing">Testing</option><option value="finished">Finished</option></select></label><label>Follow-up or result (optional)<textarea rows={3} maxLength={3000} value={editing.outcome??''} onChange={e=>setEditing({...editing,outcome:e.target.value})} placeholder="What changed, over which dates, and would you repeat it?"/></label><div className="cc-actions"><button className="p-button p-button-primary" disabled={busy||!editing.title?.trim()} onClick={()=>void save()}>{busy?'Saving…':'Save notes'}</button><button className="p-button p-button-quiet" disabled={busy} onClick={()=>setEditing(null)}>Cancel</button></div></div>}
 {message&&<p role="status">{message}</p>}
 {plans.map(p=><details key={p.id} className="cc-saved-plan"><summary>{p.title} · {p.status}</summary><p className="cc-prewrap">{p.notes}</p>{p.outcome&&<p className="cc-prewrap"><b>Result</b>{'\n'}{p.outcome}</p>}<p>Saved {new Date(p.updatedAt*1000).toLocaleDateString()} · saved notes from that date</p><button className="p-button p-button-quiet" disabled={busy} onClick={()=>setEditing({...p})}>Edit notes</button></details>)}
 </details>;
}
