'use client';
import {useState} from 'react';
import {offerEconomics,comparablePrices,type OfferInputs} from '@/app/offer-economics';
import ActionPlan from './action-plan';
import './tools.css';
type Listing={listingId:number;title:string;priceCents:number|null;currency:string;displayFresh:boolean};
type Product={title:string;note:string;variants:Array<{id:number;title:string;productionMinor:number|null;priceMinor:number}>;shipping:Array<{variant_ids:number[];countries:string[];first_item:{cost:number;currency:string}}>};
const fields:Array<[keyof OfferInputs,string]>=[['price','Your regular item price'],['discount','Sale discount %'],['shippingCharged','Shipping charged to buyer'],['production','Production cost per item'],['shippingCost','Shipping cost to you'],['feePercent','Combined selling fees %'],['fixedFees','Fixed fees per order'],['adPercent','Additional ad fee %'],['target','Minimum you want to keep']];
export default function OfferPlanner({listings,phrase,source}:{listings:Listing[];phrase:string;source:string}){
 const [selected,setSelected]=useState<number[]>([]),[currency,setCurrency]=useState('USD');
 const [inputs,setInputs]=useState<Record<keyof OfferInputs,string>>({price:'',discount:'0',shippingCharged:'0',production:'',shippingCost:'',feePercent:'',fixedFees:'',adPercent:'0',target:''});
 const [productLink,setProductLink]=useState(''),[product,setProduct]=useState<Product|null>(null),[shops,setShops]=useState<Array<{id:number;title:string}>>([]),[shop,setShop]=useState(''),[country,setCountry]=useState('US'),[costCurrency,setCostCurrency]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const prices=comparablePrices(listings.filter(l=>selected.includes(l.listingId)));
 const values=Object.fromEntries(Object.entries(inputs).map(([k,v])=>[k,v.trim()===''?NaN:Number(v)])) as OfferInputs;
 const result=offerEconomics(values);
 const money=(v:number)=>new Intl.NumberFormat(undefined,{style:'currency',currency}).format(v);
 const load=async()=>{setBusy(true);setError('');setProduct(null);setCostCurrency('');try{const r=await fetch(`/api/command-center/product?product=${encodeURIComponent(productLink)}${shop?`&shop=${shop}`:''}`);const b=await r.json() as Product & {shops?:Array<{id:number;title:string}>;error?:string};if(!r.ok)throw Error(b.error);if(b.shops){setShops(b.shops);if(!b.shops.length)setError('No Printify shops are available.')}else setProduct(b);}catch(e){setError(e instanceof Error?e.message:'Product could not load.')}finally{setBusy(false)}};
 const variants=product?.variants.map(v=>{
   const profiles=product.shipping.filter(s=>s.variant_ids.includes(v.id));
   const exact=profiles.filter(s=>s.countries.includes(country));
   const choices=exact.length?exact:profiles.filter(s=>s.countries.includes('REST_OF_THE_WORLD'));
   const shipping=choices.length===1?choices[0].first_item:null;
   const valid=costCurrency===currency && shipping?.currency===currency && v.productionMinor!==null;
   const quote=valid?offerEconomics({...values,production:v.productionMinor!/100,shippingCost:shipping!.cost/100}):null;
   return {...v,shipping,quote};
 }).sort((a,b)=>(a.quote?.contribution??Infinity)-(b.quote?.contribution??Infinity))??[];
 const below=variants.filter(v=>v.quote&&!v.quote.targetMet);
 const notes=`Idea: ${phrase}\nComparable listing IDs: ${selected.join(', ')||'Choose comparable listings first'}\n${prices?`Selected sample: ${prices.count} listings; advertised item prices ${prices.min/100}–${prices.max/100} ${prices.currency}. Shipping, variant upgrades and discounts may differ.`:''}\n\nPricing assumptions (${currency}):\n${fields.map(([key,label])=>`${label}: ${inputs[key]||'not entered'}`).join('\n')}\n${result?`Modeled contribution per order: ${money(result.contribution)}. Minimum regular price for my target: ${money(result.minimumPrice)}.`:'Complete the pricing assumptions before deciding.'}\n\nOne difference I will test:\n\nStart/end dates and listings included:\n\nSuccess measure: actual orders and contribution after costs; compare equal periods and note promotions or seasonal changes. This is an experiment, not a sales forecast.`;
 return <>
 <details className="cc-tool"><summary><strong>Will this idea pay? Build an offer test</strong></summary><p>Compare like-for-like products, then test the price against your costs before spending time on designs.</p>
 <h3>1. Choose your comparison set</h3><p className="cc-note">Select at least three similar products: same garment or item type, similar personalization and print coverage. Exclude digital downloads, bundles and misleading starting prices.</p>
 <div className="cc-comparables">{listings.filter(l=>l.displayFresh).map(l=><label className="cc-check" key={l.listingId}><input type="checkbox" checked={selected.includes(l.listingId)} onChange={e=>setSelected(old=>e.target.checked?[...old,l.listingId]:old.filter(id=>id!==l.listingId))}/><span>{l.title}<br/>{l.priceCents==null?'Price unavailable':new Intl.NumberFormat(undefined,{style:'currency',currency:l.currency}).format(l.priceCents/100)}</span></label>)}</div>
 {prices?<p><b>{prices.count} selected listings</b> · median advertised item price {new Intl.NumberFormat(undefined,{style:'currency',currency:prices.currency}).format(prices.median/100)}. This is your selected sample, not a market-wide price or a demand estimate.</p>:<p className="cc-note">Choose three or more fresh listings in the same currency to compare their advertised item prices.</p>}
 <h3>2. Stress-test the numbers</h3><label>Scenario currency<select value={currency} onChange={e=>{setCurrency(e.target.value);setCostCurrency('')}}>{['USD','GBP','EUR','CAD','AUD'].map(c=><option key={c}>{c}</option>)}</select></label><p className="cc-note">Enter your applicable fee rates and every cost in {currency}. Percentage fees are modeled on the discounted item price plus buyer shipping. Fixed fees must include any per-order charges, tax-related processing fees and other costs you want covered.</p>
 <div className="cc-fields">{fields.map(([key,label])=><label key={key}>{label}<input type="number" min="0" step="0.01" value={inputs[key]} onChange={e=>setInputs({...inputs,[key]:e.target.value})}/></label>)}</div>
 {result?<><dl className="cc-results"><div><dt>Modeled contribution per order</dt><dd>{money(result.contribution)}</dd></div><div><dt>Regular price needed for your target</dt><dd>{money(result.minimumPrice)}</dd></div><div><dt>Discount ceiling for your target</dt><dd>{result.targetMet||result.maximumDiscount!>0?`${result.maximumDiscount?.toFixed(1)}%`:'Target not met'}</dd></div></dl><p>{result.targetMet?'This scenario meets your target.':'This scenario misses your target. Raise the regular price, reduce the discount, or change the costs before testing it.'}</p></>:<p className="cc-note">Fill every cost and fee field to calculate. Zero is allowed when a cost does not apply. Discount and combined percentage fees must be below 100%.</p>}
 <p className="cc-note">Contribution is what remains under these assumptions, before overhead, income tax and unentered costs. It is not your verified shop profit.</p>
 <h3>3. Check the expensive sizes, too</h3><p>Load a saved Printify product to test every enabled variant against the same price. This reads product data and creates no product or order.</p><label>Printify product link<input value={productLink} onChange={e=>{setProductLink(e.target.value);setProduct(null);setShops([]);setShop('')}} placeholder="Paste your saved product link"/></label>
 {shops.length>0&&<label>Printify shop<select value={shop} onChange={e=>setShop(e.target.value)}><option value="">Choose the shop containing this product</option>{shops.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label>}
 <div className="cc-actions"><button className="p-button p-button-quiet" disabled={busy||!productLink.trim()||(shops.length>0&&!shop)} onClick={()=>void load()}>{busy?'Reading Printify…':'Load product costs'}</button></div>{error&&<p role="alert">{error}</p>}
 {product&&<><h4>{product.title}</h4><p className="cc-note">{product.note}</p><div className="cc-fields"><label>Ship to<select value={country} onChange={e=>setCountry(e.target.value)}>{[...new Set(['US','GB','CA','AU',...product.shipping.flatMap(s=>s.countries).filter(c=>c!=='REST_OF_THE_WORLD')])].sort().map(c=><option key={c}>{c}</option>)}</select></label><label>Production cost currency confirmed in Printify<select value={costCurrency} onChange={e=>setCostCurrency(e.target.value)}><option value="">Confirm before calculating</option>{['USD','GBP','EUR','CAD','AUD'].map(c=><option key={c}>{c}</option>)}</select></label></div>
 {below.length>0&&<p className="cc-warning">{below.length} variants miss your target at this price. Use the minimum price below for those sizes or choose a different product.</p>}
 <div className="cc-table"><table><thead><tr><th>Variant</th><th>Production</th><th>Shipping quote</th><th>Contribution</th><th>Minimum price</th></tr></thead><tbody>{variants.map(v=><tr key={v.id}><td>{v.title}</td><td>{v.productionMinor===null?'Unavailable':`${(v.productionMinor/100).toFixed(2)} ${costCurrency||'(confirm currency)'}`}</td><td>{v.shipping?`${(v.shipping.cost/100).toFixed(2)} ${v.shipping.currency}`:'Unavailable'}</td><td>{v.quote?money(v.quote.contribution):'Inputs / currency needed'}</td><td>{v.quote?money(v.quote.minimumPrice):'—'}</td></tr>)}</tbody></table></div><p className="cc-note">One item per order. Missing or ambiguous shipping quotes stay unavailable. Mixed currencies are never added.</p></>}
 <ActionPlan feature="marketWatch" source={source} heading={`Offer test: ${phrase}`} notes={notes}/>
 </details></>;
}
