import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import ts from 'typescript';
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');const {transferDraft}=await import('data:text/javascript;base64,'+Buffer.from(ts.transpile(read('app/api/listing-photos/delivery/transfer-engine.ts'),{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022})).toString('base64'));
function fixture(){let product={id:'p',visible:true,title:'QA',variants:[{id:1,price:2500}],print_areas:[]},state={phase:'ready'},calls=[];return {get product(){return product},set product(p){product=p},get state(){return state},calls,io:{read:async()=>{calls.push('read');return structuredClone(product)},hide:async()=>{calls.push('hide');product.visible=false},backup:async()=>{calls.push('backup')},claim:async s=>{calls.push('claim');if(state.phase!=='ready')return false;state=s;return true},save:async s=>{calls.push('save');state=s},send:async()=>{calls.push('send');assert.equal(product.visible,false);return {ok:true,status:200}}}}}
test('automatic transfer hides, reads back, claims durably, then sends once',async()=>{const f=fixture();await transferDraft(f.io,'p',f.state);assert.deepEqual(f.calls,['read','backup','hide','read','claim','send','save']);assert.equal(f.state.phase,'accepted');await transferDraft(f.io,'p',f.state);assert.equal(f.calls.filter(x=>x==='send').length,1)});
test('ignored visibility update, product mismatch or changed variants prevent transfer',async()=>{for(const change of ['ignored','variants','wrong']){const f=fixture();if(change==='wrong')f.product.id='other';else f.io.hide=async()=>{if(change==='variants'){f.product.visible=false;f.product.variants[0].price=1}};await assert.rejects(transferDraft(f.io,'p',f.state));assert.ok(!f.calls.includes('send'))}});
test('existing linked draft skips creation; locked products are only observed',async()=>{for(const product of [{external:{id:'123'}},{is_locked:true}]){const f=fixture();Object.assign(f.product,product);await transferDraft(f.io,'p',f.state);assert.deepEqual(f.calls,['read'])}});
test('backup and durable-claim failures cannot publish',async()=>{const a=fixture();a.io.backup=async()=>{throw Error('storage')};await assert.rejects(transferDraft(a.io,'p',a.state));assert.ok(!a.calls.includes('hide'));const b=fixture();b.io.claim=async()=>false;await transferDraft(b.io,'p',b.state);assert.ok(!b.calls.includes('send'))});
test('lost submission response reconciles without repeat creation',async()=>{const f=fixture();f.io.send=async()=>{f.calls.push('send');throw Error('network')};await assert.rejects(transferDraft(f.io,'p',f.state));assert.equal(f.state.phase,'submitted');await transferDraft(f.io,'p',f.state);assert.equal(f.calls.filter(x=>x==='send').length,1);f.product.external={id:'123'};assert.equal((await transferDraft(f.io,'p',f.state)).linked,true)});
test('known rejection remains explicit and cannot automatically resubmit',async()=>{const f=fixture();f.io.send=async()=>({ok:false,status:400});await assert.rejects(transferDraft(f.io,'p',f.state),/declined/);assert.equal(f.state.phase,'rejected');await assert.rejects(transferDraft(f.io,'p',f.state),/declined/)});
test('unresolved creation is bounded and a later actual link can still reconcile',async()=>{const f=fixture(),state={phase:'submitted',submittedAt:Date.now()-16*60*1000};await assert.rejects(transferDraft(f.io,'p',state),/not completed/);assert.ok(!f.calls.includes('send'));f.product.external={id:'123'};assert.equal((await transferDraft(f.io,'p',state)).linked,true)});
test('UI requests explicit automatic draft mode and main action stays in Goldie',()=>{const ui=read('app/photo-delivery-handoff.tsx'),app=read('app/listing-factory-app.tsx'),route=read('app/api/listing-photos/delivery/route.ts');assert.match(ui,/automaticDraft:true/);assert.match(app,/Save to Etsy Drafts/);assert.doesNotMatch(ui,/check <b>Hide in store/);assert.match(route,/Automatic creation requires draft-only mode/);assert.match(read('app/api/printify/drafts/publish/route.ts'),/GOLDIE_ETSY_PUBLISHING_ENABLED=false/)});
test('delayed hidden-setting readback is polled before one transfer, without showing a premature failure',async()=>{const f=fixture();let reads=0;f.io.hide=async()=>{f.calls.push('hide')};f.io.read=async()=>{reads++;if(reads===4)f.product.visible=false;return structuredClone(f.product)};f.io.wait=async ms=>{f.calls.push(`wait:${ms}`)};await transferDraft(f.io,'p',f.state);assert.equal(f.state.phase,'accepted');assert.equal(f.calls.filter(c=>c==='send').length,1);assert.equal(f.calls.filter(c=>c==='hide').length,1);assert.ok(f.calls.includes('wait:1000'))});
test('equivalent object property order is not mistaken for a variant edit',async()=>{const f=fixture();let reads=0;f.io.read=async()=>{reads++;return reads===1?structuredClone(f.product):{...structuredClone(f.product),variants:[{price:2500,id:1}]}};await transferDraft(f.io,'p',f.state);assert.equal(f.state.phase,'accepted')});
test('Printify per-read image instance UUID does not mask or invalidate stable artwork and geometry',async()=>{
 const first='artwork_9775602d-6c3d-6bfb-8200-c793dac43d2b',second='artwork_9b5dbb34-7e4f-aa16-f055-654bfa83dea6';
 for(const change of [null,{id:'different'},{x:.6},{scale:.8},{flipX:true}]){const f=fixture();let reads=0;const image={id:'artwork',imageId:first,x:.5,y:.3,scale:.65,angle:0,flipX:false};f.io.read=async()=>({...structuredClone(f.product),print_areas:[{placeholders:[{position:'front',images:[++reads===1?image:{...image,imageId:second,...change}]}]}]});if(change)await assert.rejects(transferDraft(f.io,'p',f.state),/print_areas/);else{await transferDraft(f.io,'p',f.state);assert.equal(f.state.phase,'accepted')}}
});
