import {prerequisitesModule} from './delivery-prerequisites-module.mjs';
import {pacingModule} from './etsy-pacing-module.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8').replace("from '../../etsy/request-pacing'",`from '${pacingModule}'`);
const load=async source=>import('data:text/javascript;base64,'+Buffer.from(ts.transpile(source,{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022})).toString('base64'));
const {freezeDraft,draftStep,verifyDraft,DraftWriteRejected}=await load(read('app/api/listing-photos/delivery/draft-engine.ts'));
const {deliveryStep}=await load(read('app/api/listing-photos/delivery/engine.ts'));
const source=()=>({title:'QA hoodie',description:'Saved copy',tags:['books'],etsyShippingProfileId:8,etsyDetails:{taxonomyId:9,properties:[{propertyId:10,valueId:11,value:'Cotton'}],personalization:{enabled:true,questions:[{type:'text_input',question:'Name',required:true,maxCharacters:30}]}}});
function fixture(){const wanted=freezeDraft(source());let saved=null,writes=[],backups=[],view={shopId:7,state:'draft',basic:{title:'Old',description:'Old',tags:[],taxonomy_id:9,shipping_profile_id:8},properties:[],questions:[]};return {wanted,get saved(){return saved},writes,backups,view,io:{read:async()=>structuredClone(view),save:async s=>{saved=structuredClone(s)},backup:async v=>{backups.push(structuredClone(v))},write:async op=>{writes.push(structuredClone(op));if(op.key==='basic')view.basic=structuredClone(op.value);else if(op.key==='questions')view.questions=structuredClone(op.value);else view.properties=[structuredClone(op.value)]}}}}
test('draft finishing writes exact saved fields, backs up once, then reads them back before completion',async()=>{const f=fixture();let result;for(let i=0;i<8;i++){result=await draftStep(f.io,7,123,f.wanted,f.saved);if(result.done)break}assert.equal(result.done,true);assert.equal(f.backups.length,1);assert.deepEqual(f.writes.map(o=>o.key),['basic','property:10','questions']);verifyDraft(f.view,7,f.wanted);await draftStep(f.io,7,123,f.wanted,f.saved);assert.equal(f.writes.length,3)});
test('wrong shop, non-draft states, and changed Printify link are blocked before writes',async()=>{for(const state of ['active','inactive','sold_out','expired']){const f=fixture();f.view.state=state;await assert.rejects(draftStep(f.io,7,123,f.wanted,null));assert.equal(f.writes.length,0)}const f=fixture();await assert.rejects(draftStep(f.io,8,123,f.wanted,null));await assert.rejects(draftStep(f.io,7,456,f.wanted,{listingId:123,index:0}));assert.equal(f.writes.length,0)});
test('lost accepted response is reconciled without repeating a metadata write',async()=>{const f=fixture(),write=f.io.write;f.io.write=async op=>{await write(op);throw Error('lost response')};await assert.rejects(draftStep(f.io,7,123,f.wanted,null));assert.ok(f.saved.pending);f.io.write=write;await draftStep(f.io,7,123,f.wanted,f.saved);assert.equal(f.writes.filter(o=>o.key==='basic').length,1)});
test('unaccepted or conflicting pending write cannot be repeated silently',async()=>{const f=fixture();f.io.write=async()=>{throw Error('unconfirmed')};await assert.rejects(draftStep(f.io,7,123,f.wanted,null));await assert.rejects(draftStep(f.io,7,123,f.wanted,f.saved),/did not confirm/);assert.equal(f.writes.length,0)});
test('external changes to earlier fields fail final readback instead of reporting completion',async()=>{const f=fixture();for(let i=0;i<3;i++)await draftStep(f.io,7,123,f.wanted,f.saved);f.view.basic.title='Seller changed this';await assert.rejects(draftStep(f.io,7,123,f.wanted,f.saved),/did not match/)});
test('snapshot validation refuses truncation, missing categories, duplicate tags and invalid questions',()=>{for(const mutate of [s=>s.title='x'.repeat(141),s=>s.etsyDetails.taxonomyId=undefined,s=>s.tags=['books','Books'],s=>s.etsyDetails.properties[0].value='',s=>s.etsyDetails.personalization.questions[0].maxCharacters=2000,s=>s.etsyDetails.personalization.questions[0].question='x'.repeat(121)]){const s=source();mutate(s);assert.throws(()=>freezeDraft(s))}const s=source(),frozen=freezeDraft(s);s.tags.push('changed');s.etsyDetails.properties[0].value='changed';assert.deepEqual(frozen.tags,['books']);assert.equal(frozen.properties[0].values[0],'Cotton')});
test('all supported personalization forms preserve limits, choices and order',()=>{const s=source();s.etsyDetails.personalization.questions.push({type:'dropdown',question:'Font',required:false,options:['Serif','Sans']},{type:'unlabeled_upload',question:'Photo',instructions:'Upload a photo',required:true,maxFiles:2});const f=freezeDraft(s);assert.deepEqual(f.questions[1].options,[{label:'Serif'},{label:'Sans'}]);assert.equal(f.questions[2].max_allowed_files,2)});
test('draft photo mode is explicit; original active-only default remains enforced',async()=>{let state=null,images=[{rank:1,listing_image_id:5}];const io={read:async()=>({shopId:7,state:'draft',images}),backup:async()=>{},save:async s=>{state=s},upload:async()=>{images=[{rank:1,listing_image_id:6}];return 6},remove:async()=>{}};const photos=[{key:'selected',type:'image/jpeg'}];await assert.rejects(deliveryStep(io,7,123,photos,null));assert.equal(state,null);await deliveryStep(io,7,123,photos,null,'draft');assert.equal((await deliveryStep(io,7,123,photos,state,'draft')).done,true)});
test('integration keeps publishing disabled and binds finishing to server-owned snapshots and existing links',()=>{const route=read('app/api/listing-photos/delivery/route.ts').replace("from './prerequisites'",`from '${prerequisitesModule}'`),service=read('app/api/listing-photos/delivery/service.ts'),adapter=read('app/api/listing-photos/delivery/draft-service.ts').replace("from './prerequisites'",`from '${prerequisitesModule}'`);assert.match(route,/freezeDraft\(\{\.\.\.draft as SourceDraft,etsyShippingProfileId:body.shippingProfileId\}\)/);assert.match(route,/draft_json/);assert.match(service,/verifyOnly:true/);assert.match(service,/readPrintifyPublishState/);assert.doesNotMatch(adapter,/publish\.json|createDraftListing|state\s*:\s*['"]active/);assert.match(read('app/api/printify/drafts/publish/route.ts'),/GOLDIE_ETSY_PUBLISHING_ENABLED=false/)});
const draftEngineUrl='data:text/javascript;base64,'+Buffer.from(ts.transpile(read('app/api/listing-photos/delivery/draft-engine.ts'),{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022})).toString('base64');
const {verifyInventory,narrowedInventory,synchronizedInventory,inventoryUpdateBody,synchronizeNarrowedInventory,draftWithSize,finishDraftMetadata,decodeEtsyText}=await load(read('app/api/listing-photos/delivery/draft-service.ts').replace("from './prerequisites'",`from '${prerequisitesModule}'`).replace("from './draft-engine'",`from '${draftEngineUrl}'`));
const product=()=>({variants:[{id:1,sku:'LF-one',price:4104,is_enabled:true,options:[8,9]}],options:[{name:'Sizes',type:'size',values:[{id:9,title:'4XL'}]}]});
const inventory=()=>({products:[{sku:'LF-one',offerings:[{price:{amount:4104,divisor:100},is_enabled:true}]}]});
test('inventory compares enabled fulfillment SKUs and exact cents without changing inventory',()=>{verifyInventory(product(),inventory());for(const mutate of [i=>i.products[0].sku='other',i=>i.products[0].offerings[0].price.amount=4100,i=>i.products[0].offerings[0].is_enabled=false,i=>i.products.push(i.products[0])]){const i=inventory();mutate(i);assert.throws(()=>verifyInventory(product(),i))}});
test('Etsy may collapse duplicate Printify option labels without losing a buyer-visible choice',()=>{
 const duplicate={options:[{name:'Color',values:[{id:1,title:'Ash'},{id:2,title:'Ash'}]},{name:'Size',values:[{id:3,title:'S'}]}],variants:[{id:11,sku:'ash-one',price:2400,is_enabled:true,options:[1,3]},{id:12,sku:'ash-two',price:2400,is_enabled:true,options:[2,3]}]};
 const collapsed={products:[{sku:'ash-one',offerings:[{price:{amount:2400,divisor:100},is_enabled:true}]}]};
 verifyInventory(duplicate,collapsed);
 duplicate.variants[1].price=2500;
 assert.throws(()=>verifyInventory(duplicate,collapsed),/do not match/);
 duplicate.variants[1].price=2400;
 duplicate.options[0].values[1].title='White';
 assert.throws(()=>verifyInventory(duplicate,collapsed),/do not match/);
});
test('a saved per-listing choice may safely remove extra Etsy colors without changing another listing',async()=>{
 const p={options:[{name:'Color',values:[{id:1,title:'Black'},{id:2,title:'White'}]},{name:'Size',values:[{id:3,title:'S'}]}],variants:[{id:11,sku:'black-s',price:2400,is_enabled:true,options:[1,3]},{id:12,sku:'white-s',price:2400,is_enabled:false,options:[2,3]}]};
 const full={products:[{sku:'black-s',property_values:[{property_id:200,property_name:'Color',values:['Black']}],offerings:[{price:{amount:2400,divisor:100},quantity:999,is_enabled:true}]},{sku:'white-s',property_values:[{property_id:200,property_name:'Color',values:['White']}],offerings:[{price:{amount:2400,divisor:100},quantity:999,is_enabled:true}]}],price_on_property:[],quantity_on_property:[],sku_on_property:[200]};
 const narrowed=narrowedInventory(p,full);assert.equal(narrowed.products.length,1);assert.equal(narrowed.products[0].sku,'black-s');assert.equal(inventoryUpdateBody(narrowed).products[0].offerings[0].price,24);
 let live=structuredClone(full),writes=0,backups=0;
 const request=async(path,init)=>{if(path.endsWith('/inventory')&&init?.method==='PUT'){writes++;const body=JSON.parse(init.body);live={...live,...body,products:body.products.map(product=>({...product,offerings:product.offerings.map(offer=>({...offer,price:{amount:Math.round(offer.price*100),divisor:100}}))}))};return Response.json(live)}if(path.endsWith('/inventory'))return Response.json(live);return Response.json({shop_id:7,state:'draft'})};
 assert.equal(await synchronizeNarrowedInventory(request,123,7,p,{...freezeDraft({...source(),selectedVariantIds:[11]}),selected_variant_ids:[11]},async()=>{backups++}),true);
 assert.equal(writes,1);assert.equal(backups,1);verifyInventory(p,live);
 assert.equal(await synchronizeNarrowedInventory(request,123,7,p,{...freezeDraft({...source(),selectedVariantIds:[11]}),selected_variant_ids:[11]},async()=>{backups++}),false);assert.equal(writes,1);
});
test('inventory repair restores a selected color from the immutable Etsy baseline and removes extras exactly',async()=>{
 const p={options:[{name:'Color',values:[{id:1,title:'Black'},{id:2,title:'White'},{id:3,title:'Pink'}]}],variants:[{id:11,sku:'black',price:2400,is_enabled:true,options:[1]},{id:12,sku:'white',price:2500,is_enabled:true,options:[2]},{id:13,sku:'pink',price:2400,is_enabled:false,options:[3]}]};
 const row=(sku,color,price=2400)=>({sku,property_values:[{property_id:200,property_name:'Color',values:[color]}],offerings:[{price:{amount:price,divisor:100},quantity:999,is_enabled:true}]});
 const current={products:[row('black','Black'),row('pink','Pink')],price_on_property:[200],quantity_on_property:[],sku_on_property:[200]},baseline={...current,products:[row('black','Black'),row('white','White',2400),row('pink','Pink')]};
 const exact=synchronizedInventory(p,current,baseline);assert.deepEqual(exact.products.map(item=>item.sku),['black','white']);assert.equal(exact.products[1].offerings[0].price.amount,2500);
 let live=structuredClone(current),writes=0,backups=0;
 const request=async(path,init)=>{if(path.endsWith('/inventory')&&init?.method==='PUT'){writes++;const body=JSON.parse(init.body);live={...live,...body,products:body.products.map(product=>({...product,offerings:product.offerings.map(offer=>({...offer,price:{amount:Math.round(offer.price*100),divisor:100}}))}))};return Response.json(live)}if(path.endsWith('/inventory'))return Response.json(live);return Response.json({shop_id:7,state:'draft'})};
 assert.equal(await synchronizeNarrowedInventory(request,123,7,p,{...freezeDraft(source()),selected_variant_ids:[11,12]},async()=>{backups++},async()=>baseline),true);assert.equal(writes,1);assert.equal(backups,1);verifyInventory(p,live);
});
test('inventory repair refuses unknown live choices, missing baseline rows and stale saved selections',async()=>{
 const p={options:[{name:'Color',values:[{id:1,title:'Black'},{id:2,title:'White'}]}],variants:[{id:11,sku:'black',price:2400,is_enabled:true,options:[1]},{id:12,sku:'white',price:2400,is_enabled:true,options:[2]}]};
 const black={sku:'black',offerings:[{price:{amount:2400,divisor:100},quantity:999,is_enabled:true}]};
 assert.equal(synchronizedInventory(p,{products:[black]},{products:[black]}),null);
 assert.equal(synchronizedInventory(p,{products:[black,{sku:'seller-added',offerings:[{price:{amount:2400,divisor:100},quantity:1,is_enabled:true}]}]},{products:[]}),null);
 const request=async()=>Response.json({shop_id:7,state:'draft'});await assert.rejects(synchronizeNarrowedInventory(request,1,7,p,{...freezeDraft(source()),selected_variant_ids:[12]},async()=>{}),/changed/);
});
test('single size is explicit in description, does not duplicate an existing label, and never guesses from color names',()=>{const s=freezeDraft(source()),p=product();assert.match(draftWithSize(s,p).description,/Available size: 4XL\./);assert.equal(draftWithSize({...s,description:'Offered in 4XL'},p).description,'Offered in 4XL');p.options=[];assert.equal(draftWithSize(s,p).description,s.description)});
test('adapter refuses draft writes if the listing goes live after initial reads',async()=>{const s=freezeDraft(source());let listingReads=0,writes=0,state=null;const request=async(path,init)=>{if(init?.method){writes++;return Response.json({})}if(path.endsWith('/inventory'))return Response.json(inventory());if(path.endsWith('/properties'))return Response.json({results:[]});if(path.endsWith('/personalization'))return Response.json({personalization_questions:[]});listingReads++;return Response.json({shop_id:7,state:listingReads>1?'active':'draft',title:'Old',description:'Old',tags:[],taxonomy_id:9,shipping_profile_id:8})};await assert.rejects(finishDraftMetadata({request,listingId:123,shopId:7,product:product(),snapshot:s,saved:null,save:async v=>{state=v},backup:async()=>{}}),/no longer a draft/);assert.equal(writes,0);assert.ok(state.pending)});

test('each bundle member passes its own shipping selection and server verifies the profile in the connected shop',()=>{assert.match(read('app/listing-factory-app.tsx'),/shippingProfileId:drafts\.some\(own=>own\.id===draft\.id\)\?etsyShippingProfileId:Number\(Object\.values\(bundleMembers\)/);assert.match(read('app/api/listing-photos/delivery/route.ts').replace("from './prerequisites'",`from '${prerequisitesModule}'`),/profile\.is_deleted/)});

test('free-text attribute verification compares the exact saved value when Etsy assigns a value ID',async()=>{const f=fixture();f.wanted.properties[0].value_ids=[];const write=f.io.write;f.io.write=async op=>{await write(op);if(op.key.startsWith('property:'))f.view.properties[0].value_ids=[999]};let result;for(let i=0;i<8;i++){result=await draftStep(f.io,7,123,f.wanted,f.saved);if(result.done)break}assert.equal(result.done,true);f.view.properties[0].values=['Other'];assert.throws(()=>verifyDraft(f.view,7,f.wanted));});

test('Etsy API text decodes one entity layer without changing literal seller text',()=>{assert.equal(decodeEtsyText("It&#39;s &quot;cotton&quot; &amp; soft"),`It's "cotton" & soft`);assert.equal(decodeEtsyText('&amp;#39;'),'&#39;');assert.equal(decodeEtsyText('&#x1f43a;'),'🐺')});
test('an explicit rejected request clears uncertainty, keeps its error, and never reports completion',async()=>{const f=fixture();f.io.write=async()=>{throw new DraftWriteRejected('Etsy returned 400: unsupported value')};await assert.rejects(draftStep(f.io,7,123,f.wanted,null),/unsupported value/);assert.equal(f.saved.pending,undefined);assert.equal(f.saved.index,0);assert.match(f.saved.lastError,/unsupported value/);assert.notEqual(f.saved.verified,true)});
