import test from 'node:test';import assert from 'node:assert/strict';import ts from 'typescript';import {readFileSync} from 'node:fs';
const raw=readFileSync('app/api/etsy/callback/route.ts','utf8'),source=ts.transpile(raw.replace(/^import .*;\n/gm,'').replace('export async function GET','async function GET'),{target:ts.ScriptTarget.ES2022});
function harness({pending=true,shop={shop_id:9,shop_name:'Test shop'},timeout=false}={}){let reads=0,exchanges=0,batches=0,deletes=0;const env={DB:{prepare(){return {bind(){return this},first:async()=>{reads++;return pending?{user_id:'test',code_verifier:'test-verifier',redirect_uri:'https://goldie.test/callback'}:null},run:async()=>{deletes++}}},batch:async()=>{batches++}}};const GET=new Function('env','NextResponse','apiKey','encryptEtsy','etsyFetch','goldieSiteUrl','forgetPairings','fetch',source+';return GET;')(env,{redirect:url=>({url})},()=> 'test-key',async()=> 'encrypted',async()=>shop,()=> 'https://goldie.test',async()=>{},async(url,init)=>{exchanges++;assert.ok(init.signal);if(timeout)throw new DOMException('timeout','TimeoutError');return Response.json({access_token:'123.test',refresh_token:'test-refresh',expires_in:3600})});return {GET,state:()=>({reads,exchanges,batches,deletes})}}
test('canceled and expired first authorization never contacts Etsy or changes saved accounts',async()=>{for(const [query,opts] of [['error=access_denied',{}],['state=expired&code=test',{pending:false}]]){const h=harness(opts),result=await h.GET(new Request('https://goldie.test/callback?'+query));assert.match(decodeURIComponent(result.url),/canceled|expired/);assert.equal(h.state().exchanges,0);assert.equal(h.state().batches,0)}});
test('first authorization timeout consumes one state but leaves existing connections unchanged',async()=>{const h=harness({timeout:true}),r=await h.GET(new Request('https://goldie.test/callback?state=test&code=test'));assert.match(decodeURIComponent(r.url),/Try connecting again/);assert.deepEqual(h.state(),{reads:1,exchanges:1,batches:0,deletes:1});assert.match(raw,/AbortSignal.timeout\(25000\)/)});
test('an account without an Etsy shop cannot deactivate the previously connected shop',async()=>{for(const shop of [null,{}, {shop_id:0,shop_name:'bad'}]){const h=harness({shop}),r=await h.GET(new Request('https://goldie.test/callback?state=test&code=test'));assert.match(decodeURIComponent(r.url),/existing Etsy shop/);assert.equal(h.state().batches,0)}});
test('a valid first authorization writes only after the shop is verified',async()=>{const h=harness(),r=await h.GET(new Request('https://goldie.test/callback?state=test&code=test'));assert.equal(r.url,'https://goldie.test/?etsy=connected');assert.equal(h.state().batches,1)});

test("authorization cancellation messages survive the later saved-connection response",()=>{const s=readFileSync("app/listing-factory-app.tsx","utf8");assert.match(s,/checkEtsyConnection\(\)\.then\(\(\)=>\{if\(alive&&message&&message!=="connected"\)setEtsyError\(message\)/)});
