import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {COLLECTION_SCHEMA,SAVE_COMPETITOR_SQL,competitorChanges} from '../app/market-collection.ts';
import {keywordSearchParams} from '../app/keyword-search.ts';
function db(){const d=new DatabaseSync(':memory:');d.exec(COLLECTION_SCHEMA);return d}
function save(d,user,key,id,payload='old',at=1){d.prepare(SAVE_COMPETITOR_SQL).run(user,key,id,payload,payload,at,at,user,key)}
test('saved comparisons keep their original baseline and isolate members and keywords',()=>{const d=db();save(d,'a','one',1);save(d,'a','one',1,'new',2);save(d,'b','one',1,'private');save(d,'a','two',1,'other');const row=d.prepare('SELECT * FROM market_keyword_collections WHERE user_id=? AND keyword_key=?').get('a','one');assert.equal(row.baseline,'old');assert.equal(row.saved_at,1);assert.equal(d.prepare('SELECT COUNT(*) n FROM market_keyword_collections').get().n,3);d.close()});
test('collection cap is enforced by the write and removed items restore without losing history',()=>{const d=db();for(let id=1;id<=101;id++)save(d,'a','one',id);assert.equal(d.prepare('SELECT COUNT(*) n FROM market_keyword_collections').get().n,100);d.prepare('UPDATE market_keyword_collections SET archived=1 WHERE listing_id=1').run();save(d,'a','one',1,'new',9);const row=d.prepare('SELECT * FROM market_keyword_collections WHERE listing_id=1').get();assert.equal(row.archived,0);assert.equal(row.baseline,'old');assert.equal(row.saved_at,1);d.close()});
test('observed changes distinguish zero, missing values, declines and currency changes',()=>{assert.deepEqual(competitorChanges({baseline:{favorites:10,views:null,priceCents:100,currency:'USD'},listing:{favorites:8,views:200,priceCents:100,currency:'USD'}}),{favorites:-2,views:null,priceCents:0});assert.equal(competitorChanges({baseline:{favorites:0,views:0,priceCents:100,currency:'USD'},listing:{favorites:3,views:8,priceCents:100,currency:'EUR'}}).priceCents,null)});
test('every keyword search ordering is passed upstream, including price pages',()=>{for(const [sort,field,direction] of [['relevance','score','desc'],['newest','created','desc'],['price','price','asc'],['price-desc','price','desc']]){const p=keywordSearchParams('bachelorette',sort,48,'shirt');assert.equal(p.get('sort_on'),field);assert.equal(p.get('sort_order'),direction);assert.equal(p.get('offset'),'48')}});
test('collection mutations require feature, ownership and same-site checks, and read details from Etsy',()=>{const s=readFileSync(new URL('../app/api/market-watch/collection/route.ts',import.meta.url),'utf8');assert.match(s,/crossSiteWrite\(request\)/);assert.match(s,/requireFeatureApi\('marketWatch'\)/);assert.match(s,/watchesFor\(access.user.userId\)/);assert.match(s,/listingDisplay\(\[id\],'search'\)/);assert.doesNotMatch(s,/body\?\.payload|body\?\.baseline/);assert.match(s,/checked_at<=\?/);assert.match(s,/SET unavailable=1/)});
