import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {UPDATE_SOURCES,sourceText,plainText,addedText,briefDay,editionDay,publishDay,validateCandidate,dailySummary,officialUrl} from '../app/platform-update-model.ts';
const source=UPDATE_SOURCES[0],quote='Sellers must disclose the new required product information before October 1.';
const item={priority:'ACTION REQUIRED',evidence:'Confirmed platform change',title:'Etsy changes a test requirement',impact:'Affected sellers must update their test listings.',action:'Check the required field by October 1.',topic:'test-requirement',quote,urgent:true};
test('official source manifest covers both platforms and never reads a seller shop',()=>{assert.ok(UPDATE_SOURCES.length>=10);for(const s of UPDATE_SOURCES)assert.ok(officialUrl(s.fetchUrl,s.platform));assert.equal(new Set(UPDATE_SOURCES.map(s=>s.id)).size,UPDATE_SOURCES.length)});
test('strip scripts navigation and formatting without treating them as changes',()=>{assert.equal(plainText('<nav>Menu</nav><p>Hello &amp; goodbye</p><script>bad()</script>'),'Hello & goodbye');assert.equal(addedText('A\nB','B\nA'),'')});
test('help-center body extraction excludes timestamp-only edits',()=>{assert.equal(sourceText(source,JSON.stringify({article:{title:'Title',body:'<p>Text</p>',updated_at:'today'}})),'Title\nText');assert.throws(()=>sourceText(source,'{}'))});
test('blocked or missing HTML body cannot become an all-clear',()=>{assert.throws(()=>sourceText(UPDATE_SOURCES.find(s=>s.kind==='html'),'<html>Access denied</html>'))});
test('daily edition follows Pacific morning across daylight saving',()=>{assert.equal(briefDay(new Date('2026-09-27T01:00:00Z')),'2026-09-26');assert.equal(publishDay(new Date('2026-09-26T12:59:00Z'),false),'2026-09-26');assert.equal(publishDay(new Date('2026-09-26T13:00:00Z'),false),'2026-09-27');assert.equal(publishDay(new Date('2026-09-26T15:00:00Z'),true),'2026-09-26');assert.equal(publishDay(new Date('2026-12-26T13:59:00Z'),false),'2026-12-26')});
test('confirmed item needs exact evidence in the changed text',()=>{assert.ok(validateCandidate(item,source,quote,quote));assert.equal(validateCandidate(item,source,quote,'Unrelated changed text'),null);assert.equal(validateCandidate({...item,quote:'invented evidence that is absent'},source,quote,quote),null)});
test('guidance and rumors cannot become mandatory rules',()=>{assert.equal(validateCandidate({...item,evidence:'Official guidance'},source,quote,quote),null);assert.equal(validateCandidate({...item,evidence:'Seller speculation'},source,quote,quote),null)});
test('external and invented source links are refused',()=>{for(const sourceUrl of ['https://etsy.com.evil.test/rule','http://help.etsy.com/rule','https://help.etsy.com/invented','javascript:alert(1)'])assert.equal(validateCandidate({...item,sourceUrl},source,quote,quote),null)});
test('urgent guidance cannot interrupt the daily brief',()=>{assert.equal(validateCandidate({...item,priority:'GOOD TO KNOW',evidence:'Official guidance'},source,quote,quote).urgent,false)});
test('empty daily result is explicit and does not manufacture content',()=>{assert.equal(dailySummary([]),'No important Etsy or Printify changes today.');assert.match(dailySummary([item]),/1 change needs your attention/)});
test('source failures preserve old content and never advance its baseline',()=>{const s=readFileSync(new URL('../app/platform-update-collector.ts',import.meta.url),'utf8');assert.match(s,/if\(!stored\?\.content\)baseline\+\+/);assert.match(s,/ON CONFLICT\(id\) DO UPDATE SET last_error=excluded.last_error/);assert.match(s,/reserveSpend/);assert.match(s,/if\(edited>=4\)/)});
test('daily job is scheduled and home card opens the actual update',()=>{assert.match(readFileSync(new URL('../scripts/add-scheduled-handler.mjs',import.meta.url),'utf8'),/run\("\/api\/platform-updates\/tick"\)/);assert.match(readFileSync(new URL('../app/home/home-view.tsx',import.meta.url),'utf8'),/<PlatformUpdate compact/);assert.match(readFileSync(new URL('../app/platform-updates/update-view.tsx',import.meta.url),'utf8'),/href="\/platform-updates"/)});

test('tomorrow morning items stay out of the midnight edition while urgent changes appear now',()=>{const before=new Date('2026-09-27T10:00:00Z');assert.equal(editionDay(before),'2026-09-26');assert.equal(publishDay(before,false),'2026-09-27');assert.equal(publishDay(before,true),'2026-09-26');assert.equal(editionDay(new Date('2026-09-27T13:00:00Z')),'2026-09-27')});
