import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import ts from 'typescript';import {pacingModule} from './etsy-pacing-module.mjs';
const load=async p=>import('data:text/javascript;base64,'+Buffer.from(ts.transpile(readFileSync(p,'utf8').replace("from '../../etsy/request-pacing'",`from '${pacingModule}'`),{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022})).toString('base64'));
const {reusablePhotoReceipt,photoDigest}=await load('app/api/listing-photos/delivery/reuse-photos.ts');const {deliveryStep}=await load('app/api/listing-photos/delivery/engine.ts');
const fixture=()=>({status:'completed',prefix:'owned/old/',photos:[{key:'owned/old/1',type:'image/jpeg',digest:'one'},{key:'owned/old/2',type:'image/jpeg',digest:'two'}],state:{listingId:123,expected:[{rank:1,listing_image_id:11},{rank:2,listing_image_id:12}],uploaded:[11,12],startedAt:1}});
const next=()=>[{key:'owned/new/1',type:'image/jpeg',digest:'one'},{key:'owned/new/2',type:'image/jpeg',digest:'two'}];
test('metadata-only update reuses exact verified content without backing up or uploading again',async()=>{const before=fixture(),saved=await reusablePhotoReceipt(before,next(),async()=>assert.fail('hashed receipts do not reread storage'));assert.ok(saved);let reads=0;const result=await deliveryStep({read:async()=>{reads++;return {shopId:7,state:'draft',images:before.state.expected}},backup:async()=>assert.fail('no redundant backup'),save:async()=>assert.fail('no redundant write'),upload:async()=>assert.fail('no redundant upload'),remove:async()=>assert.fail('no deletion')},7,123,next(),saved,'draft');assert.equal(result.done,true);assert.equal(reads,1);assert.notEqual(saved,before.state)});
test('changed content, ordering, type, count, missing digest and ownership cannot reuse photos',async()=>{for(const change of [n=>n[0].digest='changed',n=>n.reverse(),n=>n[0].type='image/png',n=>n.pop(),n=>delete n[0].digest]){const n=next();change(n);assert.equal(await reusablePhotoReceipt(fixture(),n,async()=>null),null)}const old=fixture();old.photos[0].key='another-owner/1';assert.equal(await reusablePhotoReceipt(old,next(),async()=>assert.fail('do not read another owner')),null)});
test('incomplete, uncertain and inconsistent receipts cannot skip work',async()=>{for(const change of [p=>p.status='delivering',p=>p.state.pending={rank:2},p=>p.state.uploaded.pop(),p=>p.state.expected[0].listing_image_id=99,p=>p.state=null]){const p=fixture();change(p);assert.equal(await reusablePhotoReceipt(p,next(),async()=>null),null)}});
test('legacy photos require actual content comparison and missing originals fall back safely',async()=>{const p=fixture();delete p.photos[0].digest;const calls=[];assert.ok(await reusablePhotoReceipt(p,next(),async key=>{calls.push(key);return 'one'}));assert.deepEqual(calls,['owned/old/1']);assert.equal(await reusablePhotoReceipt(p,next(),async()=>null),null);assert.notEqual(await photoDigest(new Uint8Array([1])),await photoDigest(new Uint8Array([2])))});
test('reused receipts still stop external photo edits, a changed destination, or active publication',async()=>{const p=fixture(),saved=await reusablePhotoReceipt(p,next(),async()=>null);for(const item of [{shopId:7,state:'draft',images:[{rank:1,listing_image_id:99}]},{shopId:8,state:'draft',images:p.state.expected},{shopId:7,state:'active',images:p.state.expected}])await assert.rejects(deliveryStep({read:async()=>item},7,123,next(),saved,'draft'));await assert.rejects(deliveryStep({read:async()=>({shopId:7,state:'draft',images:p.state.expected})},7,124,next(),saved,'draft'))});

test('carried photo destination is checked before any metadata finishing can begin',()=>{const s=readFileSync('app/api/listing-photos/delivery/service.ts','utf8');const guard=s.indexOf('listingId!==published.listingId');assert.ok(guard>0&&guard<s.indexOf('const metadataArgs='));assert.match(s,/Delivery stopped before any draft changes/)});
