import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {batchHistoryQuery} from '../app/batch-history-query.ts';
import {readBatchHistory} from '../app/batch-history-read.ts';
function fixture(){const db=new DatabaseSync(':memory:');db.exec(`CREATE TABLE listing_batches(id TEXT,user_id TEXT,parent_batch_id TEXT,status TEXT,step TEXT,setup_name TEXT,product_title TEXT,design_count INTEGER,state_json TEXT,created_at TEXT,updated_at TEXT)`);const add=db.prepare('INSERT INTO listing_batches VALUES (?,?,NULL,\'draft\',\'setup\',?,\'Tee\',1,?,\'2026-01-01\',?)');for(let i=1;i<=45;i++)add.run(String(i),'owner',`Batch ${i}`,JSON.stringify({batchDisplayName:i===1?'Older holiday launch':`Batch ${i}`}),`2026-01-${String(i).padStart(2,'0')}`);add.run('private','someone-else','Older holiday launch','{}','2026-09-01');return db;}
function results(db,params,user='owner'){const q=batchHistoryQuery(new URLSearchParams(params));return db.prepare(q.selectSql).all(user,...q.searchBindings,q.limit,q.offset)}
test('history pagination exposes older work once and keeps other members private',()=>{const db=fixture();const pages=[1,2,3].flatMap(page=>results(db,{page:String(page)}));assert.equal(pages.length,45);assert.equal(new Set(pages.map(r=>r.id)).size,45);assert.ok(!pages.some(r=>r.id==='private'));db.close()});
test('history search finds a renamed batch beyond the first page',()=>{const db=fixture();assert.ok(!results(db,{}).some(r=>r.id==='1'));assert.deepEqual(results(db,{query:'older HOLIDAY'}).map(r=>r.id),['1']);assert.equal(results(db,{query:"' OR 1=1 --"}).length,0);db.close()});
test('only fixed order clauses enter SQL and malformed pages are bounded',()=>{for(const sort of ['DROP TABLE listing_batches','recent','oldest']){const q=batchHistoryQuery(new URLSearchParams({sort,page:'-10'}));assert.equal(q.offset,0);assert.ok(['updated_at DESC,id DESC','updated_at ASC,id ASC'].includes(q.order));assert.ok(!q.selectSql.includes('DROP TABLE'))}});
test('history client sends pagination and search without changing shared default reads',async()=>{const urls=[];const fetcher=async url=>{urls.push(String(url));return new Response(JSON.stringify({batches:[],total:45,page:2}))};await readBatchHistory(fetcher,1000);const result=await readBatchHistory(fetcher,1000,{query:'tees & mugs',page:2,sort:'oldest'});assert.equal(urls[0],'/api/batches');const url=new URL(urls[1],'https://example.com');assert.equal(url.searchParams.get('query'),'tees & mugs');assert.equal(url.searchParams.get('page'),'2');assert.equal(result.total,45)});
