import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');
const {waitProgress,progressValue}=await import('data:text/javascript;base64,'+Buffer.from(ts.transpile(read('app/wait-progress-model.ts'),{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022})).toString('base64'));
test('minute threshold and elapsed time do not invent progress',()=>{assert.deepEqual(waitProgress(59999,0),{elapsed:'59s',long:false,stale:false});assert.deepEqual(waitProgress(60000,0),{elapsed:'1m 0s',long:true,stale:false});assert.equal(waitProgress(793275,0).elapsed,'13m 13s');assert.equal(waitProgress(-1,0).elapsed,'0s');assert.equal(progressValue(undefined,20),undefined);assert.equal(progressValue(0,0),undefined);assert.equal(progressValue(7,20),7);assert.equal(progressValue(21,20),20)});
test('stale background status is distinguished from a confirmed recent update',()=>{assert.equal(waitProgress(100000,0,10001).stale,false);assert.equal(waitProgress(100000,0,10000).stale,true);assert.equal(waitProgress(100000,0,99999).stale,false)});
test('progress modal blocks accidental dismissal, restores focus and cleans up timers',()=>{const ui=read('app/wait-progress.tsx');assert.match(ui,/showModal\(\)/);assert.match(ui,/tabIndex=\{-1\}/);assert.match(ui,/containModalFocus\(active\.title,opener\)/);assert.match(ui,/aria-modal="true"/);assert.match(ui,/onCancel=\{event=>event.preventDefault\(\)\}/);assert.match(ui,/restoreFocus\(\)/);assert.match(ui,/clearInterval\(timer\)/);assert.match(ui,/clearTimeout\(timer\)/);assert.match(ui,/value=\{value\}/);assert.doesNotMatch(ui,/Math.random|setInterval.*\+\s*1/)});
test('background delivery exposes durable timestamps and true completed counts without blocking safe navigation',()=>{assert.match(read('app/api/listing-photos/delivery/route.ts'),/createdAt:row.created_at,updatedAt:row.updated_at/);const ui=read('app/photo-delivery-handoff.tsx');assert.match(ui,/done=\{completed\} total=\{targets.length\} background/);assert.match(ui,/operation=\{busy\?/);assert.match(read('app/listing-factory-app.tsx'),/observeTools=\{!\(running\|\|Boolean\(bundleRun\)\)\}/)});

test('long waits expose local support without canceling or resubmitting work',()=>{const ui=read('app/wait-progress.tsx');assert.match(ui,/state.long&&onHelp/);assert.match(ui,/Get help with this wait/);assert.match(ui,/new CustomEvent\('goldie-support'/);assert.match(ui,/The original request is still pending/);assert.doesNotMatch(ui,/fetch\(|AbortController|location.reload/);assert.match(ui,/if\(!active\)setHelpOpen\(false\)/)});
