"use client";
import Link from "next/link";
import PlatformUpdate from "../platform-updates/update-view";
import { useEffect, useState } from "react";
import type {ResearchView} from "../niche-research-view";
type Saved={id:string;name:string;phase:string;monitoring:boolean};
type Month={revenueMinor:number;currency:string;orders:number;stale?:boolean;month?:string};
export default function HomeView(){
 const [saved,setSaved]=useState<Saved[]>([]),[research,setResearch]=useState<ResearchView|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[month,setMonth]=useState<Month|null>(null),[moneyLoading,setMoneyLoading]=useState(true);
 useEffect(()=>{let alive=true;
 void fetch('/api/niche-research').then(async r=>{if(!r.ok)throw Error();return r.json() as Promise<{projects?:Saved[]}>;}).then(async b=>{if(!alive)return;const projects:Saved[]=b.projects??[];setSaved(projects);setLoading(false);if(projects.length){const r=await fetch('/api/niche-research?id='+encodeURIComponent(projects[0].id));if(r.ok){const b=await r.json() as {project:ResearchView};if(alive)setResearch(b.project);}}}).catch(()=>{if(alive){setError('Your research could not be loaded.');setLoading(false);}});
 void fetch('/api/home').then(async r=>{if(!r.ok)throw Error();return r.json() as Promise<{blocks?:{thisMonth?:Month}}>;}).then(b=>{if(alive)setMonth(b.blocks?.thisMonth??null);}).catch(()=>{}).finally(()=>{if(alive)setMoneyLoading(false);});
 return()=>{alive=false;};},[]);
 const lead=saved[0],photo=research?.listings.find(l=>l.image&&Date.now()/1000-l.displayAt<21600),a=research?.analysis;
 const money=month?new Intl.NumberFormat(undefined,{style:'currency',currency:month.currency}).format(month.revenueMinor/100):null;
 return <main className="current-home">
 <header className="current-page-heading"><div><p className="current-kicker">{new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</p><h1>Make your next move.</h1><p>Your research, your shop, and a little perspective.</p></div><Link className="current-button" href="/market-watch/research">+ New research</Link></header>
 <div className="current-home-layout"><section className="current-radar"><div className="current-section-heading"><h2>On your radar</h2><span>{loading?'Loading…':`${saved.length} saved ${saved.length===1?'niche':'niches'}`}</span></div>
 {lead?<><Link className="current-home-feature" href={'/market-watch/research?id='+encodeURIComponent(lead.id)}><div><span className="current-pill">{lead.phase==='ready'?(lead.monitoring?'Monitoring your niche':'Monitoring paused'):'Research in progress'}</span><h2>{lead.name}</h2><p>{a?.young.length?`Explore ${a.young.length} newer listings that are finding buyers.`:a?.opportunities[0]?.hypothesis||'See the shops, products and buyer activity in your saved research.'}</p><span className="current-home-meta">{a?`${a.shops} shops · ${a.reviews30} reviews in 30 days`:'Open research'}</span></div>{photo&&<img src={photo.image!} alt={photo.title}/>}<span className="current-circle-arrow" aria-hidden="true">→</span></Link>
 {saved.slice(1).map(s=><Link className="current-home-secondary" href={'/market-watch/research?id='+encodeURIComponent(s.id)} key={s.id}><span className="current-niche-icon" aria-hidden="true">⌕</span><span><b>{s.name}</b><small>{s.phase==='ready'?(s.monitoring?'Monitoring':'Paused'):'Research in progress'}</small></span><span aria-hidden="true">→</span></Link>)}</>:<div className="current-home-feature"><div><span className="current-pill">Niche research</span><h2>{loading?'Loading your radar…':error?'Let’s reconnect.':'Your next idea starts here.'}</h2><p>{error||'Find relevant shops and follow the products, phrases and buyer needs appearing across them.'}</p><Link className="current-button current-white" href="/market-watch/research">{error?'Open research':'Research a niche'} →</Link></div></div>}
 </section><aside className="current-home-aside"><PlatformUpdate compact/><section className="current-shop-peek"><p className="current-kicker">Your shop · this month</p><strong>{moneyLoading?'Loading…':money??'Your shop numbers'}</strong><p>{month?`${month.orders} ${month.orders===1?'order':'orders'}${month.stale?' · last synced figures':''}`:'Open your shop to connect Etsy or check your numbers.'}</p><Link href="/shop-map">Your shop numbers <span aria-hidden="true">→</span></Link></section></aside></div>
 <footer className="current-suite-footer">The term &apos;Etsy&apos; is a trademark of Etsy, Inc. This application uses the Etsy API but is not endorsed or certified by Etsy, Inc.</footer></main>;
}
