/** Suggested seller experiments linked to observed wording, never inferred defects. */
export function buyerAction(phrase:string): {change:string;check:string}|null {
 if(['too small','too big','runs small','runs large','wrong size','true to size'].includes(phrase))return {change:'Test a size-help image that shows the actual garment measurements and how to compare them with a shirt the buyer already owns.',check:'Check the provider’s size chart for this exact blank. Use a measured sample before claiming a different fit. Track size-related questions and returns on the changed listings.'};
 if(['faded','cracked','peeling','vibrant'].includes(phrase))return {change:'Test a close-up print photo and specific care instructions for your own print method.',check:'Inspect and wash-test your own sample first. Compare repeat complaints and refund reasons after the change; a competitor review does not establish your product has the same issue.'};
 if(['thin','thick','soft','scratchy','comfortable','great quality','well made'].includes(phrase))return {change:'Make fabric feel easier to judge: show your actual blank close up and state its fabric composition and weight from the provider.',check:'Compare a sample with the mockup and description. Test this on one listing before changing the entire catalog; track material-related questions and feedback.'};
 if(['late','fast shipping','damaged','wrong item'].includes(phrase))return {change:'Audit the promise buyers see against your actual provider’s handling time, delivery range and order exceptions.',check:'Review recent orders and destination-specific shipping quotes. Change only promises you can support; monitor delivery complaints and reprints separately from product demand.'};
 if(['gift','birthday','christmas','anniversary','wedding','graduation',"mother's day","father's day",'baby shower','halloween','valentine','daughter','son','wife','husband','mom','mother','dad','father','sister','brother','friend','teacher','grandma','granddaughter'].includes(phrase))return {change:`Test a gift-focused photo or description for “${phrase}” with one relevant product you already sell.`,check:'Explain who it is for, what arrives and realistic arrival timing. Do not imply gift packaging unless the provider supplies it. Compare actual orders over equal periods and record seasonal or promotion changes.'};
 if(phrase==='exactly as pictured')return {change:'Test one real sample photo beside your mockup to reduce uncertainty about color, scale and placement.',check:'Use the same blank and print area the buyer receives. Track questions and “not as pictured” feedback; never copy another seller’s artwork.'};
 return null;
}
