"use client";
import { useEffect, useState } from "react";
import { phrasesFromErank } from "./seo-utils";

export type Pricing = { targetProfit: number; etsyFeePercent: number; fixedFee: number; listingFee: number; shippingCost: number; shippingCharged: number };
export type Recipe = { id: string; name: string; templateUrl: string; description: string; defaultTitle: string; defaultMockupTheme: string; pricing: Pricing; keywordListId?:string; printifyImageIndices?:number[]; normalizePadding?:boolean };
export type KeywordList = { id: string; name: string; keywords: string[] };

type WorkflowProps = {
  connected: boolean; templateUrl: string; description: string; defaultTitle: string; mockupTheme: string; pricing: Pricing; templateVerified: boolean; loadingTemplate: boolean;
  onTemplateUrl: (value: string) => void; onDescription: (value: string) => void; onDefaultTitle: (value: string) => void; onUseRecipe: (recipe: Recipe) => void; onVerifyTemplate: (url: string) => Promise<boolean>; onPricing: (pricing: Pricing) => void; onMockupTheme: (value: string) => void;
};

export function SavedWorkflow(props: WorkflowProps) {
  const [recipes, setRecipes] = useState<Recipe[]>([]), [themes, setThemes] = useState<string[]>([]), [name, setName] = useState(""), [message, setMessage] = useState(""), [editing, setEditing] = useState(false), [editingId, setEditingId] = useState(""), [activeId, setActiveId] = useState("");
  const [keywordLists,setKeywordLists]=useState<KeywordList[]>([]),[keywordListId,setKeywordListId]=useState("");
  const reload = () => fetch("/api/product-recipes").then((r) => r.json()).then((r) => setRecipes(r.recipes || [])).catch(() => undefined);
  // Account defaults load once; recipe selection can intentionally override them later.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { reload(); fetch("/api/keyword-lists").then(r=>r.json()).then(r=>setKeywordLists(r.lists||[])); fetch("/api/mockups/library").then((r) => r.json()).then((r) => { const preference=(r.preferences||[]).find((p:{sourceTheme:string})=>p.sourceTheme==="Pink Dorm"); const builtIn=preference?.hidden?[]:[preference?.displayName||"Pink Dorm"]; setThemes([...new Set([...builtIn, ...(r.templates || []).map((t: { theme: string }) => t.theme)])] as string[]); }).catch(() => setThemes(["Pink Dorm"])); fetch("/api/seller-preferences").then(r=>r.json()).then(r=>{if(r.pricing)props.onPricing({...props.pricing,...r.pricing})}).catch(()=>undefined); }, []);
  async function save() {
    setMessage("");
    if (!props.templateVerified && !(await props.onVerifyTemplate(props.templateUrl))) return setMessage("Verify the Printify template before saving this recipe.");
    const response = await fetch("/api/product-recipes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: editingId || undefined, name, templateUrl: props.templateUrl, description: props.description, defaultTitle: props.defaultTitle, defaultMockupTheme: props.mockupTheme, keywordListId, normalizePadding:true, pricing: props.pricing }) });
    const result = await response.json() as { error?: string };
    if (!response.ok) return setMessage(result.error || "Recipe could not be saved.");
    setName(""); setEditingId(""); setMessage(editingId ? "Recipe updated." : "Recipe saved. You will not need to paste this template again."); setEditing(false); reload();
  }
  async function remove(recipe: Recipe) { if (!window.confirm(`Delete “${recipe.name}”? This removes only the saved recipe, not any Printify products.`)) return; await fetch("/api/product-recipes", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: recipe.id }) }); if (activeId === recipe.id) setActiveId(""); reload(); }
  async function savePricingDefaults() { const response=await fetch("/api/seller-preferences",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pricing:props.pricing})}); setMessage(response.ok?"Pricing defaults saved for future recipes.":"Pricing defaults could not be saved."); }
  return <article className="step-card recipe-card"><div className="step-number">02</div><div className="step-content"><div className="step-heading"><div><p className="mini-label">PRODUCT RECIPE</p><h2>Choose a saved recipe or build a new one</h2></div>{props.templateVerified && <span className="done-mark">✓ Ready</span>}</div><p className="step-copy">A product recipe remembers the Printify template, description, pricing rules, and starting mockup set. Set it up once, then reuse it for every future batch.</p>
    {recipes.length > 0 && <><div className="recipe-library-head"><span>{recipes.length} saved {recipes.length === 1 ? "recipe" : "recipes"}</span><button onClick={() => { setEditing(true); setEditingId(""); setActiveId(""); setName("");setKeywordListId(""); }}>＋ Add another recipe</button></div><div className="recipe-grid">{recipes.map((recipe) => <article className={`recipe-tile ${activeId === recipe.id ? "selected" : ""}`} key={recipe.id}><button className="recipe-use" onClick={() => { setActiveId(recipe.id);setKeywordListId(recipe.keywordListId||""); props.onUseRecipe(recipe); setEditing(false); setMessage(`${recipe.name} selected. Verifying its saved Printify template…`); }}><span className="recipe-icon">P</span><span className="recipe-copy"><b>{recipe.name}</b><small>{recipe.defaultMockupTheme || "Mockups chosen after drafts"} · ${Number(recipe.pricing?.targetProfit || 0).toFixed(2)} profit target</small><em>{activeId === recipe.id ? "Selected" : "Use recipe →"}</em></span></button><button className="edit-recipe" onClick={() => { setActiveId(recipe.id); setEditingId(recipe.id); setName(recipe.name);setKeywordListId(recipe.keywordListId||""); props.onUseRecipe(recipe); setEditing(true); }}>Edit</button><button className="delete-recipe" aria-label={`Delete ${recipe.name}`} title="Delete saved recipe" onClick={() => void remove(recipe)}>×</button></article>)}</div></>}
    {!recipes.length && <div className="first-recipe-callout"><span>＋</span><div><b>Create your first product recipe</b><p>Connect one Printify template with its description, pricing, and preferred mockup set. Every future batch starts in one click.</p></div></div>}
    {(editing || !recipes.length) && <div className="recipe-form"><div className="recipe-form-heading"><b>New product recipe</b><span>Everything here will be saved together.</span></div><label><span>Recipe name</span><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Example: Bella Canvas 3001 shirts"/></label><label className="wide"><span>Printify template link</span><div className="inline-field"><input value={props.templateUrl} onChange={(e) => props.onTemplateUrl(e.target.value)} placeholder="Paste the Printify product-editor link"/><button onClick={() => void props.onVerifyTemplate(props.templateUrl)} disabled={!props.connected || !props.templateUrl.trim() || props.loadingTemplate}>{props.loadingTemplate ? "Verifying…" : props.templateVerified ? "✓ Verified" : "Verify template"}</button></div><small>This is saved inside the recipe, so you paste it only once.</small></label><label><span>Default mockup set</span><select value={props.mockupTheme} onChange={(e) => props.onMockupTheme(e.target.value)}><option value="">Choose after drafts</option>{themes.map((theme) => <option key={theme}>{theme}</option>)}</select><small>This is only the starting set. Every listing can use a different set later.</small></label><label><span>Recipe keyword bank</span><select value={keywordListId} onChange={e=>setKeywordListId(e.target.value)}><option value="">Choose during each batch</option>{keywordLists.map(list=><option key={list.id} value={list.id}>{list.name}</option>)}</select><small>The saved bank opens with this recipe, but can still be changed per batch.</small></label><details className="wide optional-recipe"><summary>Optional listing defaults</summary><label><span>Default title structure</span><input value={props.defaultTitle} onChange={(e) => props.onDefaultTitle(e.target.value)} maxLength={140} placeholder="Optional starting title or phrase structure"/></label><label><span>Product description</span><textarea value={props.description} onChange={(e) => props.onDescription(e.target.value)} rows={5} placeholder="Optional reusable description"/></label></details>
      <details className="pricing-box"><summary>Pricing rules · ${props.pricing.targetProfit.toFixed(2)} profit target</summary><p>Goldie calculates each size and color independently from its Printify cost. Offsite Ads are intentionally excluded. Save these account-level defaults once, then adjust a specific recipe only when needed.</p><div className="pricing-grid">{([['targetProfit','Target profit'],['etsyFeePercent','Etsy fees %'],['fixedFee','Payment fixed fee'],['listingFee','Listing fee'],['shippingCost','Shipping cost'],['shippingCharged','Shipping charged']] as [keyof Pricing,string][]).map(([key,label]) => <label key={key}>{label}<input type="number" min="0" step="0.01" value={props.pricing[key]} onChange={(e) => props.onPricing({ ...props.pricing, [key]: Number(e.target.value) })}/></label>)}</div><button className="save-pricing-defaults" onClick={()=>void savePricingDefaults()}>Save as my default pricing profile</button></details><button className="save-recipe" onClick={() => void save()} disabled={!name.trim() || !props.templateUrl.trim()}>{editingId ? "Update product recipe" : "Save product recipe"}</button></div>}
    {!editing && recipes.length > 0 && props.templateUrl && <div className="active-recipe"><b>Recipe loaded</b><span>{props.templateVerified ? "Printify template verified and ready for this batch." : "Verifying the saved Printify template…"}</span><button onClick={() => setEditing(true)}>Edit or save as a new recipe</button></div>}{message && <p className="field-warning" role="status">{message}</p>}
  </div></article>;
}

export function KeywordBank({ onAdd,preferredListId }: { onAdd: (keyword: string) => void;preferredListId?:string }) {
  const [lists, setLists] = useState<KeywordList[]>([]), [name, setName] = useState(""), [raw, setRaw] = useState(""), [active, setActive] = useState(""), [message, setMessage] = useState("");
  const reload = () => fetch("/api/keyword-lists").then((r) => r.json()).then((r) => setLists(r.lists || [])).catch(() => undefined);
  // Load the bank once without returning the fetch promise as an effect cleanup.
  useEffect(() => { void reload(); }, []);
  useEffect(()=>{if(preferredListId)setActive(preferredListId)},[preferredListId]);
  const words = phrasesFromErank(raw.replace(/;/g, "\n"));
  async function save() { const response = await fetch("/api/keyword-lists", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, keywords: words }) }); if (!response.ok) return setMessage("That keyword bank could not be saved."); setName(""); setRaw(""); setMessage("Keyword bank saved."); reload(); }
  const chosen = lists.find((list) => list.id === active);
  async function remove() { if (!chosen || !window.confirm(`Delete “${chosen.name}”?`)) return; const response = await fetch("/api/keyword-lists", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: chosen.id }) }); if (!response.ok) return setMessage("That keyword bank could not be deleted."); setActive(""); setMessage("Keyword bank deleted."); reload(); }
  return <details className="keyword-bank"><summary>Saved keyword banks + eRank import</summary><p>Paste an eRank column or CSV phrases, name the list, and reuse it across batches. Select a design row, then click phrases to build that title.</p><div className="keyword-save"><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Keyword list name"/><textarea value={raw} onChange={(e) => setRaw(e.target.value)} placeholder="Paste keywords or CSV here" rows={3}/><button disabled={!name.trim() || !words.length} onClick={() => void save()}>Save keyword bank</button></div><div className="keyword-list-picker"><select value={active} onChange={(e) => setActive(e.target.value)}><option value="">Choose a saved keyword bank</option>{lists.map((list) => <option value={list.id} key={list.id}>{list.name}</option>)}</select>{chosen && <button className="delete-keyword-bank" onClick={() => void remove()}>Delete bank</button>}</div>{chosen && <div className="keyword-chips">{chosen.keywords.map((word) => <button key={word} onClick={() => onAdd(word)}>+ {word}</button>)}</div>}{message && <p className="field-warning" role="status">{message}</p>}</details>;
}
