"use client";
import { useEffect, useState } from "react";

export type Pricing = { targetProfit: number; etsyFeePercent: number; fixedFee: number; listingFee: number; shippingCost: number; shippingCharged: number };
export type Recipe = { id: string; name: string; templateUrl: string; description: string; defaultTitle: string; defaultMockupTheme: string; pricing: Pricing; keywordListId?:string; printifyImageIndices?:number[]; normalizePadding?:boolean };
export type KeywordList = { id: string; name: string; keywords: string[] };

type WorkflowProps = {
  connected: boolean; templateUrl: string; mockupTheme: string; pricing: Pricing; templateVerified: boolean; loadingTemplate: boolean;
  onTemplateUrl: (value: string) => void; onUseRecipe: (recipe: Recipe) => void; onVerifyTemplate: (url: string) => Promise<boolean>; onPricing: (pricing: Pricing) => void; onMockupTheme: (value: string) => void;
};

export function SavedWorkflow(props: WorkflowProps) {
  const [recipes, setRecipes] = useState<Recipe[]>([]), [themes, setThemes] = useState<string[]>([]), [name, setName] = useState(""), [message, setMessage] = useState(""), [editing, setEditing] = useState(false), [editingId, setEditingId] = useState(""), [activeId, setActiveId] = useState("");
  const [keywordLists,setKeywordLists]=useState<KeywordList[]>([]),[keywordListId,setKeywordListId]=useState("");
  const reload = () => fetch("/api/product-recipes").then((r) => r.json()).then((r) => setRecipes(r.recipes || [])).catch(() => undefined);
  // Account fee defaults load once. Recipes only own their profit target.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { reload(); fetch("/api/keyword-lists").then(r=>r.json()).then(r=>setKeywordLists(r.lists||[])); fetch("/api/mockups/library").then((r) => r.json()).then((r) => { const preference=(r.preferences||[]).find((p:{sourceTheme:string})=>p.sourceTheme==="Pink Dorm"); const builtIn=preference?.hidden?[]:[preference?.displayName||"Pink Dorm"]; setThemes([...new Set([...builtIn, ...(r.templates || []).map((t: { theme: string }) => t.theme)])] as string[]); }).catch(() => setThemes(["Pink Dorm"])); fetch("/api/seller-preferences").then(r=>r.json()).then(r=>{if(r.pricing)props.onPricing({...props.pricing,etsyFeePercent:Number(r.pricing.etsyFeePercent??props.pricing.etsyFeePercent),fixedFee:Number(r.pricing.fixedFee??props.pricing.fixedFee),listingFee:Number(r.pricing.listingFee??props.pricing.listingFee)})}).catch(()=>undefined); }, []);
  async function save() {
    setMessage("");
    if (!props.templateVerified && !(await props.onVerifyTemplate(props.templateUrl))) return setMessage("Connect the Printify template before saving this product.");
    const response = await fetch("/api/product-recipes", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: editingId || undefined, name, templateUrl: props.templateUrl, defaultMockupTheme: props.mockupTheme, keywordListId, normalizePadding:true, pricing: {targetProfit:props.pricing.targetProfit} }) });
    const result = await response.json() as { id?: string; error?: string };
    if (!response.ok) return setMessage(result.error || "The product could not be saved.");
    const saved:Recipe={id:result.id||editingId,name:name.trim(),templateUrl:props.templateUrl,description:"",defaultTitle:"",defaultMockupTheme:props.mockupTheme,keywordListId,normalizePadding:true,pricing:{targetProfit:props.pricing.targetProfit}};
    setActiveId(saved.id);props.onUseRecipe(saved);setName(""); setEditingId(""); setMessage(editingId ? "Product updated and selected." : "Product saved and selected. You will not need to paste this Printify template again."); setEditing(false); reload();
  }
  async function remove(recipe: Recipe) { if (!window.confirm(`Delete “${recipe.name}”? This removes only the saved product, not the connected Printify product.`)) return; await fetch("/api/product-recipes", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: recipe.id }) }); if (activeId === recipe.id) setActiveId(""); reload(); }
  return <article className="step-card recipe-card"><div className="step-number">02</div><div className="step-content"><div className="step-heading"><div><p className="mini-label">SAVED PRODUCTS</p><h2>Choose a saved product or add another</h2></div>{props.templateVerified && <span className="done-mark">✓ Product ready</span>}</div><p className="step-copy">Your Printify template is the foundation. A saved product remembers that template plus your profit target and preferred mockup set—so you configure it once and reuse it.</p>
    {recipes.length > 0 && <><div className="recipe-library-head"><span>{recipes.length} saved {recipes.length === 1 ? "product" : "products"}</span><button onClick={() => { setEditing(true); setEditingId(""); setActiveId(""); setName("");setKeywordListId(""); }}>＋ Add another product</button></div><div className="recipe-grid">{recipes.map((recipe) => <article className={`recipe-tile ${activeId === recipe.id ? "selected" : ""}`} key={recipe.id}><button className="recipe-use" onClick={() => { setActiveId(recipe.id);setKeywordListId(recipe.keywordListId||""); props.onUseRecipe(recipe); setEditing(false); setMessage(`${recipe.name} selected. Checking its connected Printify template…`); }}><span className="recipe-icon">P</span><span className="recipe-copy"><b>{recipe.name}</b><small>Printify template connected · {recipe.defaultMockupTheme || "Mockups chosen after drafts"} · ${Number(recipe.pricing?.targetProfit || 0).toFixed(2)} profit target</small><em>{activeId === recipe.id ? "Product selected" : "Use this product →"}</em></span></button><button className="edit-recipe" onClick={() => { setActiveId(recipe.id); setEditingId(recipe.id); setName(recipe.name);setKeywordListId(recipe.keywordListId||""); props.onUseRecipe(recipe); setEditing(true); }}>Edit</button><button className="delete-recipe" aria-label={`Delete ${recipe.name}`} title="Delete saved product" onClick={() => void remove(recipe)}>×</button></article>)}</div></>}
    {!recipes.length && <div className="first-recipe-callout"><span>＋</span><div><b>Create your first saved product</b><p>Start by connecting a completed Printify template. Then add the Goldie defaults you want remembered with it.</p></div></div>}
    {(editing || !recipes.length) && <div className="recipe-form"><div className="recipe-form-heading"><b>{editingId ? "Edit saved product" : "New saved product"}</b><span>Connect the Printify template first. Goldie imports its product facts and permanent description automatically.</span></div><label><span>Product name</span><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Example: Comfort Colors 1717 shirts"/></label><label className="wide"><span>Connect this Printify template</span><div className="inline-field"><input value={props.templateUrl} onChange={(e) => props.onTemplateUrl(e.target.value)} placeholder="Paste the Printify product-editor link"/><button onClick={() => void props.onVerifyTemplate(props.templateUrl)} disabled={!props.connected || !props.templateUrl.trim() || props.loadingTemplate}>{props.loadingTemplate ? "Checking…" : props.templateVerified ? "✓ Template connected" : "Connect template"}</button></div><small>This is the product foundation: variants, placement, permanent description, and physical product settings must be completed in Printify first.</small></label><label><span>Default mockup set</span><select value={props.mockupTheme} onChange={(e) => props.onMockupTheme(e.target.value)}><option value="">Choose after drafts</option>{themes.map((theme) => <option key={theme}>{theme}</option>)}</select><small>Optional. This is only the starting set; every listing can use a different set later.</small></label>
      <details className="pricing-box"><summary>Profit target · ${props.pricing.targetProfit.toFixed(2)} per item</summary><p>Goldie imports every enabled variant’s Printify cost and standard shipping, then applies your saved Etsy fee profile. This saved product only needs the profit you want.</p><div className="pricing-grid"><label>Target profit per item<input type="number" min="0" step="0.01" value={props.pricing.targetProfit} onChange={(e) => props.onPricing({ ...props.pricing, targetProfit: Number(e.target.value) })}/></label></div></details><button className="save-recipe" onClick={() => void save()} disabled={!name.trim() || !props.templateUrl.trim()}>{editingId ? "Update product" : "Save product"}</button></div>}
    {!editing && recipes.length > 0 && props.templateUrl && <div className="active-recipe"><b>Product ready</b><span>{props.templateVerified ? "Its Printify template is connected and ready for this batch." : "Checking the connected Printify template…"}</span><button onClick={() => setEditing(true)}>Edit this product</button></div>}{message && <p className="field-warning" role="status">{message}</p>}
  </div></article>;
}

export function KeywordBank({ onAdd }: { onAdd: (keyword: string) => void }) {
  const [lists, setLists] = useState<KeywordList[]>([]), [active, setActive] = useState("");
  const reload = () => fetch("/api/keyword-lists").then((r) => r.json()).then((r) => setLists(r.lists || [])).catch(() => undefined);
  // Load the bank once without returning the fetch promise as an effect cleanup.
  useEffect(() => { void reload(); }, []);
  const chosen = lists.find((list) => list.id === active);
  return <section className="keyword-bank keyword-workspace"><div className="keyword-workspace-heading"><div><b>Choose a keyword bank for this batch</b><span>A keyword CSV becomes a saved bank after you upload it once. You do not need to upload it again here.</span></div><a href="/keywords">Upload or manage keyword banks</a></div><div className="keyword-list-picker"><select value={active} onChange={(e) => setActive(e.target.value)}><option value="">Choose a keyword bank</option>{lists.map((list) => <option value={list.id} key={list.id}>{list.name}</option>)}</select></div>{chosen ? <><p>Select a listing below, then click the phrases you want to add to its title.</p><div className="keyword-chips">{chosen.keywords.map((word) => <button key={word} onClick={() => onAdd(word)}>+ {word}</button>)}</div></> : <p>Choose a bank to see its keyword phrases.</p>}</section>;
}
