"use client";

import { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { safeImagePreviewDataUrl } from "./client-image-preview";
import { runBounded } from "./bounded-work";
import type { ResolvedPlacement } from "./placement-math";
import type { ArtworkBounds } from "./design-artwork";
import { measureReference, productBoxInScene, derivedPlacement, type ProductBox, type ReferenceFit } from "./mockups/reference-placement";

type Point=[number,number]; type SurfaceKind="rigid-flat"|"t-shirt"|"sweatshirt"|"hoodie"|"other-apparel"|"apparel"|"soft-goods"|"curved"|"irregular";
type Template={id:string;name:string;theme:string;src:string;corners:[Point,Point,Point,Point];normalized?:boolean;surfaceKind?:SurfaceKind;foregroundPrompt?:string};
type Result={name:string;url:string;template:string;templateId:string;surfaceKind:SurfaceKind;warning?:string};
type Adjustment={scale:number;x:number;y:number};
const MAX_MOCKUPS_PER_LISTING=8;
const load=(src:string)=>new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.crossOrigin="anonymous";image.onload=()=>resolve(image);image.onerror=reject;image.src=src});
const dataUrl=(blob:Blob)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob)});
const foregroundCache=new Map<string,string[]>();
function garmentKind(productName:string){const name=productName.toLowerCase();if(/hoodie|hooded/.test(name))return"hoodie";if(/sweatshirt|crewneck|sweater/.test(name))return"sweatshirt";if(/t[ -]?shirt|\btee\b/.test(name))return"t-shirt";return""}
function isCalibratedSurface(kind:SurfaceKind){return["rigid-flat","t-shirt","sweatshirt","hoodie","other-apparel","apparel"].includes(kind)}
function compatibleTemplate(template:Template,productName:string){const productKind=garmentKind(productName),templateKind=template.surfaceKind||"rigid-flat";if(!["t-shirt","sweatshirt","hoodie","other-apparel","apparel"].includes(templateKind))return true;if(!productKind)return templateKind==="other-apparel"||templateKind==="apparel";return templateKind===productKind||(templateKind==="apparel"&&productKind==="t-shirt")}
async function foregroundLayers(t:Template){if(!t.foregroundPrompt)return[];const cached=foregroundCache.get(t.id);if(cached)return cached;const response=await fetch("/api/mockups/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({imageUrl:new URL(t.src,window.location.origin).toString(),prompt:t.foregroundPrompt})}),payload=await response.json() as {masks?:Array<{url:string}>;error?:string};if(!response.ok)throw new Error(payload.error||`Could not safely layer ${t.name}.`);const urls=(payload.masks||[]).map(x=>x.url);foregroundCache.set(t.id,urls);return urls}
function area(c:Point[]){return Math.abs(c.reduce((n,[x,y],i)=>{const q=c[(i+1)%c.length];return n+x*q[1]-q[0]*y},0)/2)}
function safeCorners(c:Template["corners"],w:number,h:number):Template["corners"]{if(c.some(([x,y])=>x<0||y<0||x>w||y>h)||area(c)<w*h*.01)throw new Error("This mockup does not have a dependable calibrated product area.");const cx=c.reduce((n,p)=>n+p[0],0)/4,cy=c.reduce((n,p)=>n+p[1],0)/4,inset=Math.max(2,Math.min(w,h)*.002);return c.map(([x,y])=>{const dx=cx-x,dy=cy-y,d=Math.hypot(dx,dy)||1;return[x+dx/d*inset,y+dy/d*inset] as Point}) as Template["corners"]}
function bilinear(c:Template["corners"],u:number,v:number):Point{const[tl,tr,br,bl]=c;return[(1-u)*(1-v)*tl[0]+u*(1-v)*tr[0]+u*v*br[0]+(1-u)*v*bl[0],(1-u)*(1-v)*tl[1]+u*(1-v)*tr[1]+u*v*br[1]+(1-u)*v*bl[1]]}
function affine(ctx:CanvasRenderingContext2D,s:Point[],d:Point[]){const[s0,s1,s2]=s,[d0,d1,d2]=d,den=s0[0]*(s1[1]-s2[1])+s1[0]*(s2[1]-s0[1])+s2[0]*(s0[1]-s1[1]);ctx.setTransform((d0[0]*(s1[1]-s2[1])+d1[0]*(s2[1]-s0[1])+d2[0]*(s0[1]-s1[1]))/den,(d0[1]*(s1[1]-s2[1])+d1[1]*(s2[1]-s0[1])+d2[1]*(s0[1]-s1[1]))/den,(d0[0]*(s2[0]-s1[0])+d1[0]*(s0[0]-s2[0])+d2[0]*(s1[0]-s0[0]))/den,(d0[1]*(s2[0]-s1[0])+d1[1]*(s0[0]-s2[0])+d2[1]*(s1[0]-s0[0]))/den,(d0[0]*(s1[0]*s2[1]-s2[0]*s1[1])+d1[0]*(s2[0]*s0[1]-s0[0]*s2[1])+d2[0]*(s0[0]*s1[1]-s1[0]*s0[1]))/den,(d0[1]*(s1[0]*s2[1]-s2[0]*s1[1])+d1[1]*(s2[0]*s0[1]-s0[0]*s2[1])+d2[1]*(s0[0]*s1[1]-s1[0]*s0[1]))/den)}
function tri(ctx:CanvasRenderingContext2D,image:CanvasImageSource,s:Point[],d:Point[]){ctx.save();ctx.beginPath();ctx.moveTo(...d[0]);ctx.lineTo(...d[1]);ctx.lineTo(...d[2]);ctx.closePath();ctx.clip();affine(ctx,s,d);ctx.drawImage(image,0,0);ctx.restore()}
async function rigid(file:File,t:Template,adjustment:Adjustment={scale:1,x:0,y:0},quadOverride?:Template["corners"]):Promise<Result>{const[master,sourceArt,foregrounds]=await Promise.all([load(t.src),load(URL.createObjectURL(file)),foregroundLayers(t)]),artCanvas=document.createElement("canvas");artCanvas.width=sourceArt.width;artCanvas.height=sourceArt.height;const artContext=artCanvas.getContext("2d")!,drawWidth=sourceArt.width*adjustment.scale,drawHeight=sourceArt.height*adjustment.scale;artContext.drawImage(sourceArt,(sourceArt.width-drawWidth)/2+adjustment.x*sourceArt.width,(sourceArt.height-drawHeight)/2+adjustment.y*sourceArt.height,drawWidth,drawHeight);const art=artCanvas,canvas=document.createElement("canvas");canvas.width=master.naturalWidth;canvas.height=master.naturalHeight;const source=quadOverride??t.corners,raw=((quadOverride||t.normalized)?source.map(([x,y])=>[x*canvas.width,y*canvas.height] as Point):source) as Template["corners"],c=safeCorners(raw,canvas.width,canvas.height),ctx=canvas.getContext("2d",{alpha:false})!;ctx.drawImage(master,0,0);ctx.save();ctx.beginPath();c.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.clip();for(let y=0;y<16;y++)for(let x=0;x<12;x++){const u=x/12,U=(x+1)/12,v=y/16,V=(y+1)/16,s00:[number,number]=[u*art.width,v*art.height],s10:[number,number]=[U*art.width,v*art.height],s11:[number,number]=[U*art.width,V*art.height],s01:[number,number]=[u*art.width,V*art.height],d00=bilinear(c,u,v),d10=bilinear(c,U,v),d11=bilinear(c,U,V),d01=bilinear(c,u,V);tri(ctx,art as unknown as HTMLImageElement,[s00,s10,s11],[d00,d10,d11]);tri(ctx,art as unknown as HTMLImageElement,[s00,s11,s01],[d00,d11,d01])}ctx.globalCompositeOperation="multiply";ctx.globalAlpha=.12;ctx.drawImage(master,0,0);ctx.restore();for(const layer of foregrounds)ctx.drawImage(await load(layer),0,0,canvas.width,canvas.height);const blob=await new Promise<Blob>((resolve)=>canvas.toBlob((b)=>resolve(b!),"image/jpeg",.93));return{name:`${file.name.replace(/\.[^.]+$/,'')}-${t.name}.jpg`,url:URL.createObjectURL(blob),template:t.name,templateId:t.id,surfaceKind:"rigid-flat"}}
// Printify's placement, expressed the way rigid() wants it. rigid() maps the
// whole design canvas onto the scene's calibrated printable area, so its scale
// means the same thing Printify's does - the fraction of the print area the
// uploaded image covers - and its x/y are offsets from the centre of that area.
// Before this, apparel rendered at a flat 42% and rigid-flat at a flat 100%:
// constants that had no relationship to where Printify actually put the art.

// Measured on the live site against her Gildan Tee draft: in the Printify
// preview the artwork is about 27% of the shirt width, and rendering it here at
// the template's own scale of 1 produced about 60% - more than twice too big.
//
// The assumption behind D424 was wrong. A template's calibrated corners are not
// the Printify print area; they cover a much larger region of the garment, so a
// Printify scale cannot be used here directly. The old constants were empirical
// calibrations of that unknown ratio, and .42 x the artwork's 66% canvas share
// lands at ~28% - which is why they matched the preview and my "exact" mirroring
// did not.
//
// Restored until each mockup template records how its calibrated quad relates to
// the print area, which is the missing number that would make real mirroring
// possible. The placement is still recorded on every draft, ready for that work.
function placementAdjustment(_placement?:ResolvedPlacement,kind:SurfaceKind="rigid-flat"):Adjustment{
  return{scale:kind==="rigid-flat"?1:.42,x:0,y:0};
}
async function product(file:File,t:Template,reference:File):Promise<Result>{
  const scene=await(await fetch(t.src)).blob(),response=await fetch("/api/mockups/render",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:t.surfaceKind,scene:await dataUrl(scene),design:await safeImagePreviewDataUrl(file),reference:await dataUrl(reference)})}),started=await response.json() as {jobId?:string;error?:string};
  if(!response.ok||!started.jobId)throw new Error(started.error||`Could not start ${t.name}.`);
  let payload:{status?:string;image?:string;error?:string;warning?:string}={status:"queued"};
  while(payload.status!=="completed"){
    await new Promise(resolve=>window.setTimeout(resolve,2000));
    const poll=await fetch(`/api/mockups/render?jobId=${encodeURIComponent(started.jobId)}`);payload=await poll.json() as typeof payload;
    if(payload.status==="failed"||(!poll.ok&&poll.status!==202))throw new Error(payload.error||`Could not finish ${t.name}.`);
  }
  if(!payload.image)throw new Error(`Goldie finished ${t.name}, but the image is still being saved.`);const blob=await(await fetch(payload.image)).blob();return{name:`${file.name.replace(/\.[^.]+$/,'')}-${t.name}.png`,url:URL.createObjectURL(blob),template:t.name,templateId:t.id,surfaceKind:t.surfaceKind||"apparel",warning:payload.warning}
}
async function withRecovery<T>(task:()=>Promise<T>){let lastError:unknown;for(let attempt=0;attempt<3;attempt++){try{return await task()}catch(error){lastError=error;if(attempt<2)await new Promise(resolve=>window.setTimeout(resolve,1200*(attempt+1)))}}throw lastError instanceof Error?lastError:new Error("This mockup could not be created after automatic recovery.")}

export default function IntegratedMockups({design,productId,productName="",defaultTheme,defaultTemplateIds=[],referenceUrl,placement,artworkBounds,onPrepared}:{design:File;productId:string;productName?:string;defaultTheme:string;defaultTemplateIds?:string[];referenceUrl?:string;placement?:ResolvedPlacement;artworkBounds?:ArtworkBounds;onPrepared?:(count:number)=>void}){
 const[library,setLibrary]=useState<Template[]>([]),[theme,setTheme]=useState(defaultTheme),[selected,setSelected]=useState<Set<string>>(new Set()),[results,setResults]=useState<Result[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[expanded,setExpanded]=useState<Result|null>(null),[etsyStatus,setEtsyStatus]=useState(""),[adjustments,setAdjustments]=useState<Record<string,Adjustment>>({}),[renderStatus,setRenderStatus]=useState("");
 const seededDefaults=useRef(false);
 useEffect(()=>{fetch("/api/mockups/library").then(r=>r.json()).then(p=>setLibrary(p.templates||[]));},[]);
 useEffect(()=>{if(seededDefaults.current||!library.length)return;seededDefaults.current=true;let session:{theme?:string;ids?:string[]}|null=null;try{session=JSON.parse(window.sessionStorage.getItem("goldie-batch-mockups")||"null")}catch{}const ids=defaultTemplateIds.length?defaultTemplateIds:Array.isArray(session?.ids)?session.ids:[],expectedTheme=defaultTheme||session?.theme||"";const valid=ids.filter(id=>library.some(item=>item.id===id&&(!expectedTheme||item.theme===expectedTheme))).slice(0,MAX_MOCKUPS_PER_LISTING);setSelected(new Set(valid))},[library,defaultTheme,defaultTemplateIds.join("|")]);
 useEffect(()=>{if(selected.size<=MAX_MOCKUPS_PER_LISTING)return;setSelected(new Set([...selected].slice(0,MAX_MOCKUPS_PER_LISTING)));setError("You can create up to eight lifestyle mockups for one listing.")},[selected]);
 const compatibleLibrary=library.filter(template=>compatibleTemplate(template,productName)),themes=[...new Set(compatibleLibrary.map(t=>t.theme))],items=theme==="__all"?compatibleLibrary:compatibleLibrary.filter(t=>t.theme===theme),chosen=compatibleLibrary.filter(t=>selected.has(t.id)).slice(0,MAX_MOCKUPS_PER_LISTING),needsReference=chosen.some(t=>!isCalibratedSurface(t.surfaceKind||"rigid-flat"));
 async function stageForEtsy(made:Result[]){setEtsyStatus(`Saving ${made.length} mockups for Etsy…`);const form=new FormData();form.set("productId",productId);form.set("kind","mockup");form.set("replace","true");for(const result of made){const blob=await(await fetch(result.url)).blob();form.append("file",new File([blob],result.name,{type:blob.type||"image/jpeg"}))}const response=await fetch("/api/etsy/images",{method:"POST",body:form}),payload=await response.json() as {error?:string};if(!response.ok)throw new Error(payload.error||"Goldie could not safely replace this listing’s mockups. Your previous mockups were kept.");onPrepared?.(made.length);setEtsyStatus(`✓ ${made.length} mockups will be added automatically when this listing publishes.`)}

 /* Segmentation runs once per scene and is remembered for the session: the same
    photo always yields the same product box, and this costs a call. */
 const productBoxes=useRef(new Map<string,ProductBox|null>());
 async function derivedFor(template:Template,fit:ReferenceFit){
   if(!productBoxes.current.has(template.id)){
     let box:ProductBox|null=null;
     try{
       const blob=await(await fetch(template.src)).blob();
       const asDataUrl=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(blob)});
       box=await productBoxInScene(asDataUrl,productName);
     }catch{box=null}
     productBoxes.current.set(template.id,box);
   }
   const box=productBoxes.current.get(template.id);
   return box?derivedPlacement(fit,box,artworkBounds):null;
 }
 async function generate(){if(!chosen.length)return;setBusy(true);setError("");setEtsyStatus("");setResults([]);setRenderStatus(`Preparing ${chosen.length} selected ${chosen.length===1?"scene":"scenes"}…`);try{let reference:File|null=null;if(referenceUrl){const blob=await(await fetch(referenceUrl,{signal:AbortSignal.timeout(30_000)})).blob();reference=new File([blob],"printify-placement-reference.jpg",{type:blob.type||"image/jpeg"})}if(needsReference&&!reference)throw new Error("Wait for the Printify preview before creating this product’s mockups.");/* D433 - measure the specification once per run: how big the artwork is on the product, and where, according to the Printify preview. */const fit=reference?await measureReference(reference):null;const completed=new Map<number,Result>(),jobs=chosen.map((template,index)=>({template,index}));setRenderStatus(`Creating ${chosen.length} ${chosen.length===1?"mockup":"mockups"} in a reliable queue. Goldie will retry an interrupted scene automatically.`);await runBounded(jobs,2,async({template,index})=>{const result=await withRecovery(async()=>{if(!isCalibratedSurface(template.surfaceKind||"rigid-flat"))return product(design,template,reference!);const derived=fit?await derivedFor(template,fit):null;return derived?rigid(design,template,derived.adjustment,derived.quad):rigid(design,template,placementAdjustment(placement,template.surfaceKind||"rigid-flat"));});return{index,result}},({index,result})=>{completed.set(index,result);const ready=[...completed.entries()].sort((a,b)=>a[0]-b[0]).map(([,item])=>item);setResults(ready);setRenderStatus(`${ready.length} of ${chosen.length} finished. ${ready.length<chosen.length?"Goldie is creating the remaining scenes.":"Saving all finished mockups to this listing…"}`)});const made=[...completed.entries()].sort((a,b)=>a[0]-b[0]).map(([,item])=>item);if(made.length!==chosen.length)throw new Error("Goldie could not finish every selected scene. Nothing was replaced; try the batch again.");await stageForEtsy(made);const warning=made.find(item=>item.warning)?.warning;if(warning)setEtsyStatus(`✓ Mockups saved. ${warning}`)}catch(e){setError(e instanceof Error?e.message:"Mockups could not be created.")}finally{setBusy(false);setRenderStatus("")}}
 async function adjustResult(result:Result,next:Adjustment){const template=library.find(item=>item.id===result.templateId);if(!template)return;setAdjustments(current=>({...current,[result.templateId]:next}));setBusy(true);try{const revised=await rigid(design,template,next),nextResults=results.map(item=>item===result?revised:item);URL.revokeObjectURL(result.url);setResults(nextResults);setExpanded(revised);await stageForEtsy(nextResults)}catch(e){setError(e instanceof Error?e.message:"This mockup could not be adjusted.")}finally{setBusy(false)}}
 function toggleTemplate(id:string){setSelected(current=>{const next=new Set(current);if(next.has(id)){next.delete(id);setError("");return next}if(next.size>=MAX_MOCKUPS_PER_LISTING){setError("You can create up to eight lifestyle mockups for one listing.");return next}next.add(id);setError("");return next})}
 const lightbox=expanded&&typeof document!=="undefined"?createPortal(<div className="inline-lightbox" role="dialog" aria-modal="true" onMouseDown={event=>{if(event.target===event.currentTarget)setExpanded(null)}}><button onClick={()=>setExpanded(null)} aria-label="Close">×</button><img src={expanded.url} alt={`${expanded.template} enlarged`}/>{isCalibratedSurface(expanded.surfaceKind)?<div className="mockup-adjust"><b>Adjust this mockup only</b>{(()=>{const value=adjustments[expanded.templateId]||placementAdjustment(placement,expanded.surfaceKind);return <><label>Design size<input type="range" min=".5" max="1.6" step=".02" value={value.scale} onChange={event=>void adjustResult(expanded,{...value,scale:Number(event.target.value)})}/></label><label>Left / right<input type="range" min="-.3" max=".3" step=".01" value={value.x} onChange={event=>void adjustResult(expanded,{...value,x:Number(event.target.value)})}/></label><label>Up / down<input type="range" min="-.3" max=".3" step=".01" value={value.y} onChange={event=>void adjustResult(expanded,{...value,y:Number(event.target.value)})}/></label></>})()}</div>:<p className="mockup-placement-lock">Placement is locked to the real Printify preview so the apparel mockup matches what the customer receives.</p>}</div>,document.body):null;
 return <><div className="integrated-mockups"><div className="mockup-limit-note"><b>Choose up to 8 lifestyle mockups</b><span>Goldie processes them in a reliable queue.</span></div><div className="mockup-control-row"><label>Browse mockups<select value={theme} onChange={e=>{setTheme(e.target.value);setResults([]);setEtsyStatus("")}}><option value="">Choose a mockup set</option><option value="__all">All mockups</option>{themes.map(x=><option key={x}>{x}</option>)}</select></label><a href="/mockups" target="_blank" rel="noopener noreferrer">Manage saved mockup sets ↗</a></div>{theme&&<div className="inline-mockup-grid">{items.map(t=><label className={selected.has(t.id)?"selected":""} key={t.id}><input type="checkbox" checked={selected.has(t.id)} onChange={()=>toggleTemplate(t.id)}/><img src={t.src} alt={t.name}/><span>{t.theme} · {t.name}</span></label>)}</div>}{needsReference&&<p className="automatic-reference">✓ Goldie will use the real Printify preview above as the placement reference.</p>}<div className="mockup-action-sequence"><div className="mockup-primary-action"><span>1</span><div><b>Create mockups for this listing</b><small>Goldie creates the mockups you selected above and saves them to this listing.</small></div><button className="generate-inline" aria-busy={busy} disabled={!chosen.length||busy||needsReference&&!referenceUrl} onClick={()=>void generate()}>{busy?"Goldie is creating them…":`Create ${chosen.length ? `these ${chosen.length} ${chosen.length===1?"mockup":"mockups"}` : "selected mockups"}`}</button></div>{busy&&renderStatus&&<div className="mockup-live-progress" role="status" aria-live="polite"><i/><span>{renderStatus}</span></div>}</div>{error&&<p className="field-error" role="alert">{error}</p>}{etsyStatus&&<p className="etsy-ready-status" role="status">{etsyStatus}</p>}{results.length>0&&<div className="inline-generated">{results.map(r=><figure key={r.name}><button className="mockup-enlarge" onClick={()=>setExpanded(r)}><img src={r.url} alt={r.template}/><span>View larger</span></button><figcaption><span>{r.template}</span><a href={r.url} download={r.name}>Download</a></figcaption></figure>)}</div>}<p className="etsy-note">Goldie saves these mockups for this exact listing and adds them automatically through Etsy when you publish. Individual downloads stay available as a backup.</p></div>{lightbox}</>
}
