"use client";
/* eslint-disable @next/next/no-img-element */
import { useEffect, useMemo, useState } from "react";

type Point=[number,number]; type SurfaceKind="rigid-flat"|"apparel"|"soft-goods"|"curved"|"irregular";
type Template={id:string;name:string;theme:string;src:string;corners:[Point,Point,Point,Point];normalized?:boolean;surfaceKind?:SurfaceKind};
type Result={name:string;url:string;template:string};
const builtIns:Template[]=[
 {id:"pink-1",theme:"Pink Dorm",name:"Leaning frame",src:"/mockups/pink-dorm-01-leaning-frame.png",corners:[[230,382],[810,328],[798,1321],[197,1254]]},
 {id:"pink-2",theme:"Pink Dorm",name:"Hanging wall art",src:"/mockups/pink-dorm-02-hanging-poster.png",corners:[[546,105],[1065,79],[1065,929],[546,896]]},
 {id:"pink-3",theme:"Pink Dorm",name:"Maximalist bedroom",src:"/mockups/pink-dorm-03-maximalist-bed.png",corners:[[305,101],[878,125],[879,985],[305,988]]},
 {id:"pink-4",theme:"Pink Dorm",name:"Chair and plants",src:"/mockups/pink-dorm-04-chair-and-plants.png",corners:[[346,104],[870,123],[868,930],[346,942]]},
 {id:"pink-5",theme:"Pink Dorm",name:"Bed and plants",src:"/mockups/pink-dorm-05-bed-and-plants.png",corners:[[462,150],[868,150],[868,699],[462,699]]},
];
const load=(src:string)=>new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.crossOrigin="anonymous";image.onload=()=>resolve(image);image.onerror=reject;image.src=src});
const dataUrl=(blob:Blob)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob)});
function bilinear(c:Template["corners"],u:number,v:number):Point{const[tl,tr,br,bl]=c;return[(1-u)*(1-v)*tl[0]+u*(1-v)*tr[0]+u*v*br[0]+(1-u)*v*bl[0],(1-u)*(1-v)*tl[1]+u*(1-v)*tr[1]+u*v*br[1]+(1-u)*v*bl[1]]}
function affine(ctx:CanvasRenderingContext2D,s:Point[],d:Point[]){const[s0,s1,s2]=s,[d0,d1,d2]=d,den=s0[0]*(s1[1]-s2[1])+s1[0]*(s2[1]-s0[1])+s2[0]*(s0[1]-s1[1]);ctx.setTransform((d0[0]*(s1[1]-s2[1])+d1[0]*(s2[1]-s0[1])+d2[0]*(s0[1]-s1[1]))/den,(d0[1]*(s1[1]-s2[1])+d1[1]*(s2[1]-s0[1])+d2[1]*(s0[1]-s1[1]))/den,(d0[0]*(s2[0]-s1[0])+d1[0]*(s0[0]-s2[0])+d2[0]*(s1[0]-s0[0]))/den,(d0[1]*(s2[0]-s1[0])+d1[1]*(s0[0]-s2[0])+d2[1]*(s1[0]-s0[0]))/den,(d0[0]*(s1[0]*s2[1]-s2[0]*s1[1])+d1[0]*(s2[0]*s0[1]-s0[0]*s2[1])+d2[0]*(s0[0]*s1[1]-s1[0]*s0[1]))/den,(d0[1]*(s1[0]*s2[1]-s2[0]*s1[1])+d1[1]*(s2[0]*s0[1]-s0[0]*s2[1])+d2[1]*(s0[0]*s1[1]-s1[0]*s0[1]))/den)}
function tri(ctx:CanvasRenderingContext2D,image:HTMLImageElement,s:Point[],d:Point[]){ctx.save();ctx.beginPath();ctx.moveTo(...d[0]);ctx.lineTo(...d[1]);ctx.lineTo(...d[2]);ctx.closePath();ctx.clip();affine(ctx,s,d);ctx.drawImage(image,0,0);ctx.restore()}
async function rigid(file:File,t:Template):Promise<Result>{const master=await load(t.src),art=await load(URL.createObjectURL(file)),canvas=document.createElement("canvas");canvas.width=master.naturalWidth;canvas.height=master.naturalHeight;const c=(t.normalized?t.corners.map(([x,y])=>[x*canvas.width,y*canvas.height] as Point):t.corners) as Template["corners"],ctx=canvas.getContext("2d",{alpha:false})!;ctx.drawImage(master,0,0);ctx.save();ctx.beginPath();c.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.clip();for(let y=0;y<16;y++)for(let x=0;x<12;x++){const u=x/12,U=(x+1)/12,v=y/16,V=(y+1)/16,s00:[number,number]=[u*art.width,v*art.height],s10:[number,number]=[U*art.width,v*art.height],s11:[number,number]=[U*art.width,V*art.height],s01:[number,number]=[u*art.width,V*art.height],d00=bilinear(c,u,v),d10=bilinear(c,U,v),d11=bilinear(c,U,V),d01=bilinear(c,u,V);tri(ctx,art,[s00,s10,s11],[d00,d10,d11]);tri(ctx,art,[s00,s11,s01],[d00,d11,d01])}ctx.restore();const blob=await new Promise<Blob>((resolve)=>canvas.toBlob((b)=>resolve(b!),"image/jpeg",.93));return{name:`${file.name.replace(/\.[^.]+$/,'')}-${t.name}.jpg`,url:URL.createObjectURL(blob),template:t.name}}
async function product(file:File,t:Template,reference:File):Promise<Result>{const scene=await(await fetch(t.src)).blob(),response=await fetch("/api/mockups/render",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:t.surfaceKind,scene:await dataUrl(scene),design:await dataUrl(file),reference:await dataUrl(reference)})}),payload=await response.json() as {image?:string;error?:string};if(!response.ok||!payload.image)throw new Error(payload.error||`Could not create ${t.name}.`);const blob=await(await fetch(payload.image)).blob();return{name:`${file.name.replace(/\.[^.]+$/,'')}-${t.name}.png`,url:URL.createObjectURL(blob),template:t.name}}

export default function IntegratedMockups({design,defaultTheme}:{design:File;defaultTheme:string}){
 const[library,setLibrary]=useState<Template[]>(builtIns),[theme,setTheme]=useState(defaultTheme),[selected,setSelected]=useState<Set<string>>(new Set()),[results,setResults]=useState<Result[]>([]),[reference,setReference]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{fetch("/api/mockups/library").then(r=>r.json()).then(p=>{const preference=(p.preferences||[]).find((item:{sourceTheme:string})=>item.sourceTheme==="Pink Dorm"),included=preference?.hidden?[]:builtIns.map(item=>({...item,theme:preference?.displayName||item.theme}));setLibrary([...included,...(p.templates||[])])});},[]);
 const themes=useMemo(()=>[...new Set(library.map(t=>t.theme))],[library]),items=library.filter(t=>t.theme===theme),chosen=items.filter(t=>selected.has(t.id)),needsReference=chosen.some(t=>(t.surfaceKind||"rigid-flat")!=="rigid-flat");
 async function generate(){if(!chosen.length)return;setBusy(true);setError("");setResults([]);try{const made:Result[]=[];for(const t of chosen){if((t.surfaceKind||"rigid-flat")!=="rigid-flat"&&!reference)throw new Error("Add one placement reference for this product mockup set.");made.push((t.surfaceKind||"rigid-flat")==="rigid-flat"?await rigid(design,t):await product(design,t,reference!));setResults([...made])}}catch(e){setError(e instanceof Error?e.message:"Mockups could not be created.")}finally{setBusy(false)}}
 return <div className="integrated-mockups"><div className="mockup-control-row"><label>Mockup set<select value={theme} onChange={e=>{setTheme(e.target.value);setSelected(new Set());setResults([])}}><option value="">Choose a mockup set</option>{themes.map(x=><option key={x}>{x}</option>)}</select></label><a href="/mockups">Manage saved mockup sets</a></div>{theme&&<div className="inline-mockup-grid">{items.map(t=><label className={selected.has(t.id)?"selected":""} key={t.id}><input type="checkbox" checked={selected.has(t.id)} onChange={()=>setSelected(s=>{const n=new Set(s);if(n.has(t.id))n.delete(t.id);else if(n.size<10)n.add(t.id);return n})}/><img src={t.src} alt={t.name}/><span>{t.name}</span></label>)}</div>}{needsReference&&<label className="reference-inline">Placement reference<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>setReference(e.target.files?.[0]||null)}/><small>Required for apparel, curved, soft, or irregular products so placement matches your approved example.</small></label>}<button className="generate-inline" disabled={!chosen.length||busy||needsReference&&!reference} onClick={()=>void generate()}>{busy?`Creating ${results.length} of ${chosen.length}…`:`Create ${chosen.length||"selected"} mockups`}</button>{error&&<p className="field-error">{error}</p>}{results.length>0&&<div className="inline-generated">{results.map(r=><figure key={r.name}><img src={r.url} alt={r.template}/><figcaption><span>{r.template}</span><a href={r.url} download={r.name}>Download</a></figcaption></figure>)}</div>}<p className="etsy-note">These files are ready now. Automatic attachment and image ordering will turn on after Etsy approves the API connection.</p></div>
}
