"use client";

import { useEffect, useMemo, useRef, useState } from "react";

type StoredImage={id:string;key:string;kind:"mockup"|"uploaded"|"size-guide";name:string;src:string};
type Photo={id:string;kind:"mockup"|"uploaded"|"printify"|"size-guide";name:string;src:string};

export default function ListingPhotoOrder({productId,printifyImages,indices,refreshKey,preview=false}:{productId:string;printifyImages:string[];indices:number[];refreshKey:string;preview?:boolean}){
  const[stored,setStored]=useState<StoredImage[]>([]),[savedOrder,setSavedOrder]=useState<string[]>([]),[order,setOrder]=useState<string[]>([]),[dragged,setDragged]=useState<string>(""),[status,setStatus]=useState(""),[loading,setLoading]=useState(true);
  const orderRef=useRef<string[]>([]),draggedRef=useRef(""),savedOnDropRef=useRef(false);
  const isPreview=preview||(typeof window!=="undefined"&&["localhost","127.0.0.1"].includes(window.location.hostname));
  useEffect(()=>{let active=true;if(isPreview){setStored([]);setSavedOrder([]);setStatus("");setLoading(false);return()=>{active=false}}setLoading(true);fetch(`/api/etsy/images?productId=${encodeURIComponent(productId)}`).then(async response=>{const payload=await response.json() as {images?:StoredImage[];order?:string[];error?:string};if(!response.ok)throw new Error(payload.error||"Photo order could not be loaded.");if(active){setStored(payload.images||[]);setSavedOrder(payload.order||[])}}).catch(error=>active&&setStatus(error instanceof Error?error.message:"Photo order could not be loaded.")).finally(()=>active&&setLoading(false));return()=>{active=false}},[productId,refreshKey,isPreview]);
  const photos=useMemo<Photo[]>(()=>[...stored.filter(image=>image.kind==="mockup"||image.kind==="uploaded"),...indices.map(index=>({id:`printify:${index}`,kind:"printify" as const,name:`Printify photo ${index+1}`,src:printifyImages[index]})).filter(image=>Boolean(image.src)),...stored.filter(image=>image.kind==="size-guide")],[stored,indices,printifyImages]);
  useEffect(()=>{const available=new Set(photos.map(photo=>photo.id)),next=[...savedOrder.filter(id=>available.has(id)),...photos.map(photo=>photo.id).filter(id=>!savedOrder.includes(id))];orderRef.current=next;setOrder(next)},[photos.map(photo=>photo.id).join("|"),savedOrder.join("|")]);
  const byId=new Map(photos.map(photo=>[photo.id,photo]));
  async function save(next:string[]){orderRef.current=next;setOrder(next);if(isPreview){setSavedOrder(next);setStatus("✓ Photo order saved in preview");return}setStatus("Saving photo order…");try{const response=await fetch("/api/etsy/images",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({productId,order:next})}),payload=await response.json() as {error?:string};if(!response.ok)throw new Error(payload.error||"Photo order could not be saved.");setSavedOrder(next);setStatus("✓ Photo order saved") }catch(error){setStatus(error instanceof Error?error.message:"Photo order could not be saved.")}}
  function move(source:string,target:string){if(!source||source===target)return;setOrder(current=>{const next=current.filter(id=>id!==source),index=next.indexOf(target);next.splice(Math.max(0,index),0,source);orderRef.current=next;return next})}
  function nudge(id:string,direction:-1|1){const index=order.indexOf(id),target=index+direction;if(index<0||target<0||target>=order.length)return;const next=[...order];[next[index],next[target]]=[next[target],next[index]];void save(next)}
  if(loading)return <div className="photo-order-loading">Loading listing photos…</div>;
  if(!photos.length)return null;
  return <section className="listing-photo-order">{/* D554 - this printed "Rearrange listing photos" at display size once per
      listing, under a task row already called "Arrange final photo order" and a
      heading already carrying the listing's name. Three titles for one grid. The
      instruction it carried is said once, by the task panel. */}<div className={`photo-order-strip ${dragged?"is-reordering":""}`}>{order.map((id,index)=>{const photo=byId.get(id);if(!photo)return null;return <article className={dragged===id?"dragging":""} key={id} draggable onDragStart={event=>{draggedRef.current=id;savedOnDropRef.current=false;setDragged(id);event.dataTransfer.effectAllowed="move";/* D411 - The browser draws its own half-transparent copy of the card under the cursor, while the real list reorders live underneath it. Two versions of the same card, one of them ghostly, is why it was impossible to tell whether a move had taken. Suppress the ghost and let the actual card move - the pattern every sortable list uses. */try{const blank=document.createElement("canvas");blank.width=1;blank.height=1;event.dataTransfer.setDragImage(blank,0,0)}catch{/* older browsers keep their ghost */}}} onDragEnter={()=>move(draggedRef.current,id)} onDragOver={event=>{event.preventDefault();event.dataTransfer.dropEffect="move"}} onDrop={event=>{event.preventDefault();savedOnDropRef.current=true;void save(orderRef.current)}} onDragEnd={()=>{draggedRef.current="";setDragged("");if(!savedOnDropRef.current)void save(orderRef.current)}}><span className="photo-rank">{index+1}</span><img src={photo.src} alt={photo.name}/>{/* D554 - every tile printed its label twice: <b>"Printify photo 1"</b> and
      then <small>"Printify photo"</small> beside it, with the first truncated to
      "Printify ph…" by its own width. The badge already carries the number, so
      the tile names the kind, once. */}
      <b>{photo.kind==="uploaded"?"Uploaded photo":photo.kind==="mockup"?"Saved mockup":photo.kind==="size-guide"?"Size guide":"Printify photo"}</b><div className="photo-order-buttons"><button type="button" disabled={index===0} onClick={()=>nudge(id,-1)} aria-label={`Move ${photo.name} earlier`}>←</button><button type="button" disabled={index===order.length-1} onClick={()=>nudge(id,1)} aria-label={`Move ${photo.name} later`}>→</button></div><span className="drag-handle" aria-hidden="true">⋮⋮</span></article>})}</div>{status&&<p role="status">{status}</p>}</section>;
}
