'use client';
import {readDeliveryStatus} from './delivery-status-read';
import {deliveryWrite,resolvedDeliveryUncertainty,deliveryChoiceRecovery} from './delivery-write';
import {statusReadCoordinator} from './status-read-coordinator';
import {deliveryPollDelay} from './delivery-polling';
import WaitProgress,{WaitCard} from './wait-progress';
import {prepareDraftBatch} from './draft-batch-preparation';
import {forwardRef,useEffect,useImperativeHandle,useRef,useState} from 'react';
type Target={id:string;title:string;indices:number[];shippingProfileId:number};
type Delivery={id:string;productId:string;status:string;error:string|null;photoCount:number;createdAt?:number;updatedAt?:number;listingId:number|null;mode?:'draft'|'photos';choicesChanged?:boolean;choiceCheckUnavailable?:boolean};
type ProductionPartner={id:number;name:string;location:string};
export type PhotoDeliveryHandle={prepare():Promise<boolean>};
const label=(status:string,draft=false)=>draft?({preparing:'Saving draft choices',waiting:'Preparing your Etsy draft',delivering:'Creating and checking your Etsy draft',completed:'Etsy draft verified',canceled:'Finishing canceled',expired:'Checking ended — prepare again',failed:'Preparation needs another try',needs_attention:'Draft needs attention'}[status]||'Not prepared'):({preparing:'Saving photo set',waiting:'Waiting for publication',delivering:'Updating Etsy photos',completed:'Photos verified on Etsy',canceled:'Delivery canceled',expired:'Checking ended — prepare again',failed:'Preparation needs another try',needs_attention:'Delivery needs attention'}[status]||'Not prepared');
const PhotoDeliveryHandoff=forwardRef<PhotoDeliveryHandle,{targets:Target[];beforePrepare:()=>Promise<unknown>;onReview?:(id:string,photos:boolean)=>void;onStatusReady?:(ready:boolean)=>void}>(({targets,beforePrepare,onReview,onStatusReady},ref)=>{
 const [statusKnown,setStatusKnown]=useState(false);
 useEffect(()=>{onStatusReady?.(statusKnown);return()=>onStatusReady?.(false)},[statusKnown,onStatusReady]);
 const [deliveries,setDeliveries]=useState<Delivery[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true),[prepared,setPrepared]=useState<number|null>(null),[preparationErrors,setPreparationErrors]=useState<Record<string,string>>({});
 const [partners,setPartners]=useState<ProductionPartner[]>([]),[partnerId,setPartnerId]=useState(0),[partnersLoading,setPartnersLoading]=useState(true),[partnerError,setPartnerError]=useState('');
 const recoveryFocus=useRef<string|null>(null),polling=useRef(true),locked=useRef(false),queryKey=useRef(""),panel=useRef<HTMLElement>(null),targetKey=JSON.stringify(targets.map(t=>[t.id,t.indices,t.shippingProfileId]));
 const uncertainProducts=useRef(new Set<string>());
 const statusReads=useRef(statusReadCoordinator<Delivery[]>());
 const pollSchedule=useRef({started:Date.now(),next:0,failures:0});
 queryKey.current=targetKey;
 useEffect(()=>{let alive=true;setPartnersLoading(true);setPartnerError('');fetch('/api/etsy/production-partners',{cache:'no-store',signal:AbortSignal.timeout(20000)}).then(async response=>{const payload=await response.json() as {partners?:ProductionPartner[];selectedId?:number;error?:string};if(!response.ok)throw Error(payload.error||'Production partners could not be loaded.');if(alive){setPartners(payload.partners||[]);setPartnerId(Number(payload.selectedId)||0)}}).catch(value=>{if(alive)setPartnerError(value instanceof Error?value.message:'Production partners could not be loaded.')}).finally(()=>{if(alive)setPartnersLoading(false)});return()=>{alive=false}},[targetKey]);
 async function choosePartner(id:number){setPartnerId(id);setPartnerError('');try{const response=await fetch('/api/etsy/production-partners',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id}),signal:AbortSignal.timeout(20000)}),payload=await response.json() as {error?:string};if(!response.ok)throw Error(payload.error||'The production partner could not be saved.')}catch(value){setPartnerId(0);setPartnerError(value instanceof Error?value.message:'The production partner could not be saved.')}}
 useEffect(()=>{if(busy||!recoveryFocus.current)return;const id=recoveryFocus.current;recoveryFocus.current=null;panel.current?.querySelector<HTMLButtonElement>(`[data-recovery-product="${CSS.escape(id)}"]`)?.focus()},[busy,preparationErrors]);
 async function refresh(){if(locked.current)return;
  const expectedKey=targetKey;
  try{await statusReads.current.run(expectedKey,async signal=>{
   const query=new URLSearchParams();for(const target of targets){query.append('productId',target.id);query.set(`images.${target.id}`,JSON.stringify(target.indices));query.set(`shipping.${target.id}`,String(target.shippingProfileId));}
   const response=await fetch(`/api/listing-photos/delivery?${query}`,{cache:'no-store',signal:AbortSignal.any([signal,AbortSignal.timeout(20000)])});
   if(response.status===401&&queryKey.current===expectedKey)polling.current=false;
   return readDeliveryStatus<Delivery>(response);
  },next=>{if(queryKey.current===expectedKey){setStatusKnown(true);setDeliveries(next);const resolved=next.filter(item=>uncertainProducts.current.has(item.productId)&&resolvedDeliveryUncertainty(item));if(resolved.length){for(const item of resolved)uncertainProducts.current.delete(item.productId);setPreparationErrors(current=>{const remaining={...current};for(const item of resolved)delete remaining[item.productId];return remaining})}polling.current=next.some(d=>['preparing','waiting','delivering'].includes(d.status));setLoading(false);setError('')}})}catch(value){if(queryKey.current===expectedKey)setStatusKnown(false);throw value}
 }
 useEffect(()=>{let alive=true;setStatusKnown(false);setDeliveries([]);setLoading(true);setError('');setPreparationErrors({});
  polling.current=true;pollSchedule.current={started:Date.now(),next:0,failures:0};
  let reading=false;
  const check=async()=>{if(!alive||document.hidden||reading||locked.current)return;reading=true;try{await refresh();pollSchedule.current.failures=0}catch(e){if(alive){pollSchedule.current.failures++;setLoading(false);setError(e instanceof Error?e.message:'Photo delivery status could not be loaded.')}}finally{reading=false;pollSchedule.current.next=Date.now()+deliveryPollDelay(Date.now()-pollSchedule.current.started,pollSchedule.current.failures)}};
  void check();const interval=setInterval(()=>{if(polling.current&&Date.now()>=pollSchedule.current.next)void check()},1000);document.addEventListener('visibilitychange',check);
  return()=>{alive=false;statusReads.current.invalidate();clearInterval(interval);document.removeEventListener('visibilitychange',check)};
 // Membership and selections both determine whether the verified package is still current.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[targetKey]);
 useImperativeHandle(ref,()=>({prepare:async()=>{
  if(!statusKnown){setError('Check saved progress before preparing or updating Etsy drafts.');return false}
  if(partnersLoading){setError('Your Etsy production partners are still loading. Try again in a moment.');return false}
  if(partnerError){setError(partnerError);return false}
  if(partners.length>1&&!partnerId){setError('Choose the production partner for these Etsy drafts.');panel.current?.scrollIntoView({block:'center'});return false}
  if(locked.current)return false;locked.current=true;statusReads.current.invalidate();setBusy(true);setError('');setPrepared(null);setPreparationErrors({});
  try{
   await beforePrepare();if(!targets.length)throw Error('No completed drafts are available yet.');
   setPrepared(0);
   const errors=await prepareDraftBatch(targets,async target=>{
    let confirmedFailure=false;
    try{
    const response=await deliveryWrite('/api/listing-photos/delivery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId:target.id,printifyImageIndices:target.indices,shippingProfileId:target.shippingProfileId,productionPartnerId:partnerId||undefined,mode:'draft',automaticDraft:true})});
    const payload=await response.json() as {error?:string;delivery?:Delivery};if(!response.ok||!payload.delivery){confirmedFailure=true;throw Error(payload.error||'Photo delivery could not be prepared.');}
    polling.current=true;pollSchedule.current={started:Date.now(),next:0,failures:0};setLoading(false);setDeliveries(current=>[...current.filter(d=>d.productId!==target.id),payload.delivery!]);
    }catch(value){if(confirmedFailure)uncertainProducts.current.delete(target.id);else uncertainProducts.current.add(target.id);polling.current=!confirmedFailure;pollSchedule.current.next=0;const message=value instanceof Error?value.message:'Draft preparation failed.';if(!recoveryFocus.current)recoveryFocus.current=target.id;setPreparationErrors(current=>({...current,[target.id]:message}));throw value}
   },finished=>setPrepared(finished));
   if(errors.length)throw Error(`${errors.length} ${errors.length===1?'listing needs':'listings need'} attention. Review the message beside each listing.`);
   panel.current?.scrollIntoView({block:'center',behavior:'smooth'});return true;
  }catch(e){setError(e instanceof Error?e.message:'Photo delivery could not be prepared.');panel.current?.scrollIntoView({block:'center',behavior:'smooth'});return false}
  finally{locked.current=false;setBusy(false);setPrepared(null)}
 }}));
 async function prepareOne(target:Target,recheckId?:string){if(!statusKnown||locked.current)return;setPreparationErrors(current=>{const next={...current};delete next[target.id];return next});locked.current=true;statusReads.current.invalidate();setBusy(true);setError('');try{await beforePrepare();const response=await deliveryWrite('/api/listing-photos/delivery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId:target.id,printifyImageIndices:target.indices,shippingProfileId:target.shippingProfileId,productionPartnerId:partnerId||undefined,mode:'draft',automaticDraft:true,recheckId})});const payload=await response.json() as {error?:string;delivery?:Delivery};if(!response.ok||!payload.delivery)throw Error(payload.error||'Draft preparation failed.');polling.current=true;pollSchedule.current={started:Date.now(),next:0,failures:0};setLoading(false);setDeliveries(current=>[...current.filter(d=>d.productId!==target.id),payload.delivery!])}catch(e){uncertainProducts.current.add(target.id);polling.current=true;pollSchedule.current.next=0;const message=e instanceof Error?e.message:'Draft preparation failed.';recoveryFocus.current=target.id;setPreparationErrors(current=>({...current,[target.id]:message}));setError('This listing needs attention. Review its message below.')}finally{locked.current=false;setBusy(false)}}
 async function cancel(id:string){statusReads.current.invalidate();try{const response=await deliveryWrite(`/api/listing-photos/delivery?id=${encodeURIComponent(id)}`,{method:'DELETE'});const payload=await response.json() as {error?:string;deliveries?:Delivery[]};if(!response.ok)throw Error(payload.error);statusReads.current.invalidate();await refresh()}catch(e){setError(e instanceof Error?e.message:'Delivery could not be canceled.')}}
 const activeDeliveries=deliveries.filter(d=>['waiting','delivering'].includes(d.status));
 const completed=deliveries.filter(d=>d.status==='completed'&&!d.choicesChanged).length;
 const problems=deliveries.filter(d=>['failed','expired','canceled','needs_attention'].includes(d.status)||d.choicesChanged||preparationErrors[d.productId]);
 const preparationProblemCount=Object.keys(preparationErrors).length,hasPreparationProblems=preparationProblemCount>0,hasUncertainPreparation=targets.some(target=>uncertainProducts.current.has(target.id));
 const showResults=deliveries.length>0||hasPreparationProblems||Boolean(error)||Boolean(partnerError)||partners.length>1;
 return <section className={`photo-delivery-handoff ${showResults||!statusKnown||busy?'':'is-empty'}`} ref={panel} aria-label="Finish Etsy drafts" aria-busy={busy}>
  {partners.length>1&&<label className="etsy-production-partner-choice">Production partner<select value={partnerId||''} disabled={busy||partnersLoading} onChange={event=>void choosePartner(Number(event.target.value))}><option value="">Choose the partner that makes these products</option>{partners.map(partner=><option key={partner.id} value={partner.id}>{partner.name}{partner.location?` — ${partner.location}`:''}</option>)}</select><small>This choice is remembered for this Etsy shop and added to every draft.</small></label>}
  {partnerError&&<p className="photo-delivery-error" role="alert">{partnerError}</p>}
  <WaitProgress operation={busy?{title:'Preparing your Etsy drafts',detail:prepared===null?'Saving your selected photos and listing details.':`${prepared} of ${targets.length} prepared. Submitted drafts are already finishing in the background.`}:null}/>
  {activeDeliveries.length>0&&!busy&&<WaitCard title="Finishing your Etsy drafts" detail="The Listing Factory is transferring the saved listings to Etsy Drafts. Allow several minutes." started={Math.min(...activeDeliveries.map(d=>d.createdAt||d.updatedAt||Date.now()))} lastConfirmed={Math.max(...activeDeliveries.map(d=>d.updatedAt||0))||undefined} done={completed} total={targets.length} background/>}
  {!statusKnown&&<p className="photo-delivery-quiet-status" role="status">{loading?'Checking Etsy Drafts…':'Etsy Draft status unavailable.'}</p>}
  {showResults&&<details className={`draft-handoff-details ${problems.length||hasPreparationProblems||error?'has-problems':''}`} open={Boolean(problems.length||hasPreparationProblems||error)}><summary><span>{hasPreparationProblems&&!deliveries.length?'Etsy drafts not started':problems.length||hasPreparationProblems?'Etsy drafts need attention':activeDeliveries.length?'Creating Etsy drafts':completed===targets.length?'Etsy drafts ready':'Etsy draft progress'}</span><b>{hasPreparationProblems&&!deliveries.length?`${preparationProblemCount} ${preparationProblemCount===1?'listing needs':'listings need'} attention`:`${completed} of ${targets.length}`}</b></summary>
  <ul className="draft-handoff-results">{targets.map(target=>{const item=deliveries.find(d=>d.productId===target.id),problem=preparationErrors[target.id];if(!item&&!problem)return null;const messages=[...new Set([item?.error?.trim(),problem?.trim()].filter((value):value is string=>Boolean(value)))];return <li key={target.id}><strong>{target.title}</strong><span>{problem?'Needs attention':item?.choiceCheckUnavailable?'Choices not verified':item?.choicesChanged&&item.status==='completed'?'Saved changes not applied':item?label(item.status,item.mode==='draft'):'Not prepared'}</span>{item?.choicesChanged&&<small>{deliveryChoiceRecovery(item)}</small>}{messages.map(message=><small role="alert" key={message}>{message}</small>)}{problem&&onReview&&<button type="button" disabled={busy} data-recovery-product={target.id} onClick={()=>onReview(target.id,/photo|image|mockup/i.test(problem))}>{/photo|image|mockup/i.test(problem)?'Review photos':'Review listing'}</button>}{item&&['failed','expired','canceled','needs_attention'].includes(item.status)&&<button type="button" className="draft-prepare" disabled={busy||loading||!statusKnown} onClick={()=>void prepareOne(target,item.mode==='draft'&&item.status==='needs_attention'?item.id:undefined)}>{item.mode==='draft'&&item.status==='needs_attention'?'Verify last change':'Try again'}</button>}{item?.mode==='draft'&&item.status==='needs_attention'&&<button type="button" disabled={busy||!statusKnown} onClick={()=>void prepareOne(target)}>Use corrected choices</button>}{item?.mode==='draft'&&item.status==='completed'&&item.choicesChanged&&!item.choiceCheckUnavailable&&<button type="button" className="draft-prepare" disabled={busy||loading||!statusKnown} onClick={()=>void prepareOne(target)}>Apply saved changes</button>}{item?.status==='waiting'&&<button type="button" disabled={busy} onClick={()=>void cancel(item.id)}>Cancel</button>}{item?.status==='completed'&&item.listingId&&<a className="draft-open" href={item.mode==='draft'?`https://www.etsy.com/your/shops/me/listing-editor/edit/${item.listingId}`:`https://www.etsy.com/listing/${item.listingId}`} target="_blank" rel="noopener noreferrer">{item.mode==='draft'?'Open Etsy draft':'View on Etsy'} ↗</a>}</li>})}</ul></details>}
  {error&&(hasUncertainPreparation||!hasPreparationProblems)&&<button type="button" disabled={busy||loading} onClick={()=>{setLoading(true);void refresh().catch(e=>{setLoading(false);setError(e instanceof Error?e.message:'Saved progress could not be checked.')})}}>{loading?'Checking saved progress…':'Check saved progress'}</button>}
  {error&&<div className="photo-delivery-error" role="alert"><p>{error}</p>{/sign in/i.test(error)&&<a href="/account/sign-in?return_to=%2Flisting-factory" target="_blank" rel="noopener noreferrer">Sign in to Listing Factory ↗</a>}<p>{hasPreparationProblems&&!deliveries.length?'Nothing was sent. Fix the items above, then choose Save to Etsy Drafts again.':'Completed work is saved. Check progress before trying again.'}</p></div>}
 </section>;
});
PhotoDeliveryHandoff.displayName='PhotoDeliveryHandoff';export default PhotoDeliveryHandoff;
