"use client";
import { FormEvent, useEffect, useRef, useState } from "react";
import { supportResponse, SupportTurn } from "./support-engine";
const SUGGESTIONS = ["A design failed", "Printify won’t connect", "My template won’t load", "My image won’t upload"];
const CONTACT_KEY = "5b639ca5-fea3-4f99-bf3e-a08f6e9482c2";

function SupportText({ text }: { text: string }) { const parts = text.split(/(\*\*[^*]+\*\*)/g); return <>{parts.map((part, index) => part.startsWith("**") ? <b key={index}>{part.slice(2, -2)}</b> : part)}</>; }

export default function SupportChat() {
  const [open,setOpen]=useState(false); const [view,setView]=useState<"chat"|"contact">("chat"); const [query,setQuery]=useState("");
  const [messages,setMessages]=useState<SupportTurn[]>([{role:"support",text:"Hi 👋 I’m here to help with the Goldie Listing Factory. Paste an error message or describe what happened, and I’ll work through it with you."}]);
  const [suggestions,setSuggestions]=useState(SUGGESTIONS);
  const [email,setEmail]=useState(""); const [issue,setIssue]=useState(""); const [screenshot,setScreenshot]=useState<File|null>(null); const [contactStatus,setContactStatus]=useState(""); const [sending,setSending]=useState(false);
  const endRef=useRef<HTMLDivElement>(null);
  function answer(value:string){const clean=value.trim();if(!clean)return;setMessages(current=>{const response=supportResponse(clean,current);setSuggestions(response.suggestions??[]);return [...current,{role:"user",text:clean},{role:"support",text:response.text,articleId:response.articleId}];});setQuery("");}
  useEffect(()=>{try{const saved=sessionStorage.getItem("goldie-listing-support");if(saved){const parsed=JSON.parse(saved) as SupportTurn[];if(Array.isArray(parsed)&&parsed.length)setMessages(parsed.slice(-30));}}catch{}},[]);
  useEffect(()=>{try{sessionStorage.setItem("goldie-listing-support",JSON.stringify(messages.slice(-30)));}catch{}},[messages]);
  useEffect(()=>{const openWithError=(event:Event)=>{const detail=(event as CustomEvent<string>).detail;setOpen(true);setView("chat");if(detail)answer(detail);};window.addEventListener("goldie-support",openWithError);return()=>window.removeEventListener("goldie-support",openWithError);},[]);
  useEffect(()=>{endRef.current?.scrollIntoView({behavior:"smooth"});},[messages,open]);
  function submit(event:FormEvent){event.preventDefault();answer(query);}
  async function sendContact(event:FormEvent){event.preventDefault();setContactStatus("");if(!/^\S+@\S+\.\S+$/.test(email)){setContactStatus("Enter a valid email address.");return;}if(issue.trim().length<5){setContactStatus("Tell us what happened so we can help.");return;}if(screenshot&&screenshot.size>5*1024*1024){setContactStatus("The optional screenshot must be 5 MB or smaller.");return;}setSending(true);try{const form=new FormData();form.append("access_key",CONTACT_KEY);form.append("subject",`Goldie Listing Factory support — ${email}`);form.append("from_name","Goldie Listing Factory Support");form.append("replyto",email);form.append("email",email);form.append("message",issue.trim());form.append("page",window.location.href);form.append("conversation",messages.map(message=>`${message.role==="user"?"Member":"Goldie Support"}: ${message.text}`).join("\n\n"));if(screenshot)form.append("attachment",screenshot,screenshot.name);const response=await fetch("https://api.web3forms.com/submit",{method:"POST",body:form});const result=await response.json() as {success?:boolean;message?:string};if(!response.ok||!result.success)throw new Error(result.message||"Message failed");setContactStatus("Sent. We’ll reply to the email you provided.");setIssue("");setScreenshot(null);}catch{setContactStatus("That message did not send. Email goldie@beawolfbiz.com directly.");}finally{setSending(false);}}
  return <div className="support-root"><button className="support-launcher" onClick={()=>setOpen(value=>!value)} aria-expanded={open} aria-controls="support-panel" aria-label="Open Goldie support"><span>G</span></button>{open&&<section className="support-panel" id="support-panel" aria-label="Goldie support assistant"><header><nav><button className={view==="chat"?"active":""} onClick={()=>setView("chat")}>Chat</button><button className={view==="contact"?"active":""} onClick={()=>setView("contact")}>Contact Support</button></nav><button className="support-close" onClick={()=>setOpen(false)} aria-label="Close support">×</button></header>{view==="chat"?<><div className="support-messages" aria-live="polite">{messages.map((message,index)=><div className={`support-message ${message.role}`} key={index}><SupportText text={message.text}/></div>)}{suggestions.length>0&&<div className="support-suggestions">{suggestions.map(suggestion=><button key={suggestion} onClick={()=>answer(suggestion)}>{suggestion}</button>)}</div>}<div ref={endRef}/></div><form className="support-chat-form" onSubmit={submit}><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Ask about an error or problem" aria-label="Support message"/><button disabled={!query.trim()} aria-label="Send">→</button></form></>:<form className="support-contact-form" onSubmit={sendContact}><p>Need a human? Tell us what happened and we’ll email you back as soon as we can.</p><label>Email address *</label><input type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="you@email.com"/><label>What happened? *</label><textarea rows={6} value={issue} onChange={event=>setIssue(event.target.value)} placeholder="Include the error message or what you expected to happen."/><label>Screenshot of the error <span>optional</span></label><div className="screenshot-field"><input id="support-screenshot" type="file" accept="image/png,image/jpeg,image/webp" onChange={event=>setScreenshot(event.target.files?.[0]??null)}/><label htmlFor="support-screenshot">{screenshot?screenshot.name:"Choose screenshot"}</label><small>PNG, JPG or WebP · 5 MB maximum</small></div><button className="contact-send" disabled={sending}>{sending?"Sending…":"Send message"}</button>{contactStatus&&<div className="contact-status" role="status">{contactStatus}</div>}</form>}</section>}</div>;
}
