export type SupportArticle = { id: string; title: string; triggers: string[]; answer: string };

export const SUPPORT_ARTICLES: SupportArticle[] = [
  { id:"image-8253", title:"Provided images do not exist / error 8253", triggers:["8253","provided images do not exist","image does not exist","images do not exist"], answer:"Goldie now accepts Printify’s completed upload response immediately instead of performing the extra lookup that caused this false error. If Printify genuinely returns an incomplete upload, Goldie waits up to one minute before marking only that design failed. Keep successful drafts and use **Retry failed designs** only for any remaining failure." },
  { id:"retry-failed", title:"Retry only failed designs", triggers:["design failed","retry failed","rerun failed","some failed","one failed","failed designs","try again"], answer:"When a batch has failures, Goldie shows **Retry [number] failed designs**. That button reruns only the failed files and keeps every successful draft untouched, so it will not duplicate successful listings. The original batch tab must still be open so the browser still has those files." },
  { id:"token-connect", title:"Printify will not connect", triggers:["token","connect printify","won't connect","not connecting","401","403","unauthorized","saved connection"], answer:"Create a new Printify personal access token with **all access scopes enabled**, copy it before leaving Printify, then paste it into Connect Printify. If an old connection is showing, disconnect it first. Goldie encrypts and remembers the replacement token." },
  { id:"template-not-found", title:"Template product not found", triggers:["template not found","product not found","different account","different shop","template product was not found"], answer:"The connected token cannot see that template. Confirm the template is in **My Products** under the same Printify account connected to Goldie. Then paste its Printify product editor link. Do not use an Etsy URL or catalog product URL. If it belongs to another Printify account, reconnect the correct account." },
  { id:"template-link", title:"Which Printify link to paste", triggers:["which url","which link","product url","editor link","design editor","listing editor","load template"], answer:"Open the prepared product from **Printify → My Products**, enter its editor, and copy that page’s URL. The link should contain `/app/editor/` or `/products/`. Before loading it, save the provider, enabled sizes, colors, prices, print areas and initial placement you want carried into the batch." },
  { id:"template-print-area", title:"Print-area validation / error 8150", triggers:["8150","validation failed","print area","print_areas","placeholder","template setup"], answer:"Printify rejected the template’s print-area setup. Open the template in Printify, make sure every enabled product side has a real placeholder design, save it, and load the template again. If it continues, duplicate the product in Printify, save the fresh copy, and use that copy as the template." },
  { id:"cloud-file", title:"Goldie can see the filename but cannot read the image", triggers:["could not be decoded","cannot read","can't read","cloud file","icloud","onedrive","google drive","invalidstateerror","filename"], answer:"The file is visible in the folder but is not fully downloaded to the computer. In Finder or File Explorer, download the file locally first, then select it again. Use a valid PNG, JPG or WebP. You do not need to report every file’s dimensions or size." },
  { id:"image-size", title:"Image too large", triggers:["image too large","file too large","size limit","8201","file.size.limit","75 mb","95 mb","100 mb"], answer:"Goldie automatically prepares oversized artwork for the selected product while preserving transparency when needed. If Printify still reports an image-size error, retry that failed design once. If it repeats, export that one design as a PNG or high-quality JPG and run it again; the rest of the batch does not need to be repeated." },
  { id:"wrong-format", title:"Unsupported image format", triggers:["wrong format","unsupported format","tiff","tif","pdf","svg","heic","webp","format"], answer:"The Listing Factory accepts PNG, JPG/JPEG and WebP. Use transparent PNG for apparel or any product where the background should not print. Convert TIFF, PDF, SVG or HEIC files before adding them." },
  { id:"transparent-background", title:"Background printed unexpectedly", triggers:["transparent","background","white box","apparel","shirt background"], answer:"When the background should disappear, the finished file must already be a transparent-background PNG. Goldie preserves existing transparency, but it does not remove a background from the design." },
  { id:"low-resolution", title:"Low-resolution warning", triggers:["low resolution","dpi","blurry","pixelated","too small","upscale"], answer:"Upscale the finished design before adding it to the Listing Factory. Goldie can reduce oversized artwork safely, but enlarging a genuinely small design would not restore missing detail. Check Printify’s quality indicator in the editor before publishing." },
  { id:"batch-limits", title:"Batch limits", triggers:["20","batch limit","how many designs","500 mb","maximum","too many files"], answer:"Each batch can contain **1–20 designs** and up to **500 MB total**. You do not need exactly 20. Smaller batches are allowed. Start another batch after the first finishes." },
  { id:"network", title:"Upload connection interrupted", triggers:["won't upload","image won't upload","failed to fetch","network","connection interrupted","load failed","internet","temporarily unavailable"], answer:"Keep the Listing Factory tab open and do not let the computer sleep while a batch runs. Goldie automatically retries temporary upload and Printify interruptions. If a file still fails, wait for the batch to finish and use **Retry failed designs**." },
  { id:"rate-limit", title:"Printify is limiting requests / error 429", triggers:["429","rate limit","too many requests","taking longer","slow","stuck"], answer:"Printify is temporarily limiting request speed. Goldie automatically waits between attempts and keeps working through the batch. Keep the page open. If any designs remain failed at the end, use **Retry failed designs**; do not restart the successful listings." },
  { id:"batch-progress", title:"Batch appears slow", triggers:["taking long","taking forever","progress","creating","how long","spinner","number off"], answer:"Large images and Printify processing can make individual drafts take longer. The progress number shows the design currently being handled. Keep the page open until **Batch finished** appears. Only take action if a design is marked Failed; then use the retry button." },
  { id:"draft-location", title:"Where the drafts go", triggers:["where are drafts","can't find drafts","not in etsy","unpublished","publish","draft location"], answer:"Goldie creates **unpublished products in Printify → My Products**. Nothing is published to Etsy automatically. Edit placement, add your title and mockups, and finish the listing in Printify before publishing it to your connected Etsy shop." },
  { id:"editor-login", title:"Edit in Printify opens login or product not found", triggers:["printify login","product not found after login","edit in printify","opens login","wrong tab","editor button"], answer:"Be signed into the same Printify account connected to Goldie in the same browser. Click **Edit in Printify** again after signing in. If Printify still says product not found, the browser is signed into a different Printify account than the token used by Goldie." },
  { id:"popups", title:"Open all does not open every tab", triggers:["open all","popup","pop-up","tabs did not open","only one tab"], answer:"Your browser blocked some Printify editor tabs. Allow pop-ups for the Listing Factory site, then click **Open all in Printify** again. Or use the individual **Edit in Printify** button beside each draft." },
  { id:"duplicate-drafts", title:"Avoiding duplicate drafts", triggers:["duplicate","duplicates","run again","successful designs","already created"], answer:"Use **Retry failed designs**, not Create Printify drafts again. The retry button keeps successful drafts and reruns only files marked Failed. Starting the entire batch again can create another copy of designs that already succeeded." },
  { id:"description", title:"Descriptions, titles, and Etsy details", triggers:["description","title","tags","keywords","same description","unique blurb"], answer:"Goldie imports the permanent product description from the verified Printify template. After drafts are created, build each final title from your keyword bank; matching tags generate automatically. Goldie then adds a design-specific introduction and prepares only the Etsy attributes supported by the product and listing." },
  { id:"mastermind-access", title:"Mastermind sign-in or access code", triggers:["mastermind","access code","chatgpt sign in","sign in button","new tab","testing is closed"], answer:"Open the mastermind Listing Factory page in desktop Chrome or Edge, choose **Sign in with ChatGPT**, and complete sign-in in the new tab. Return to the Listing Factory tab if needed, enter the current mastermind code once, and continue. The ChatGPT email does not need to match the mastermind purchase email." },
  { id:"browser-support", title:"Supported browser and devices", triggers:["safari","firefox","phone","mobile","browser","windows","mac"], answer:"Use the Listing Factory on a computer in current Chrome or Edge. Folder selection works on both Mac and Windows. Keep the browser tab open until the batch finishes; mobile browsers are not supported for production batches." },
  { id:"start-over", title:"Clear the current batch", triggers:["clear all","start over","remove files","new batch","reset"], answer:"Choose **Clear all / start over** after the current batch finishes. It clears the template, description, selected files and on-page results. It does not delete any drafts already created in Printify." },
  { id:"signin-required", title:"Sign in to continue", triggers:["sign in to continue","sign in with chatgpt first","not signed in","logged out"], answer:"Your Listing Factory sign-in expired or opened in a different browser tab. Return to the mastermind Listing Factory page, choose Sign in with ChatGPT, finish sign-in in the new tab, then return to the original Listing Factory tab." },
  { id:"invalid-template-link", title:"Unrecognized Printify editor link", triggers:["not a recognized printify","unrecognized printify","product-editor link","recognized printify editor link"], answer:"Open Printify → My Products, click the prepared unpublished product, enter its editor and copy that browser URL. Do not use the Printify catalog page, an Etsy listing, or a general My Products URL." },
  { id:"missing-placeholder", title:"Template has no placeholder artwork", triggers:["add one placeholder design","placeholder design","before using it for a batch"], answer:"Open the template in Printify and add one temporary design to every print side you intend to use. Position it the way you want the batch artwork placed, save the product, then reload that template in Goldie. Goldie replaces the placeholder while copying its placement." },
  { id:"secure-service", title:"Secure storage or artwork delivery unavailable", triggers:["secure token storage","secure artwork delivery","access storage is unavailable","storage is unavailable","not configured"], answer:"This is a Listing Factory service configuration problem, not a file or Printify problem. Do not replace your token or designs. Use Contact Support and paste the exact message so the team can correct the service." },
  { id:"mastermind-code", title:"Mastermind code is not accepted", triggers:["mastermind code is not correct","code is not correct","testing is closed","testing is currently closed"], answer:"Confirm you are using the current mastermind access code exactly as provided, without extra spaces. If the page says testing is closed rather than code incorrect, the access period has been turned off and Contact Support must confirm whether it should be active." },
  { id:"printify-server", title:"Printify server error", triggers:["printify remained temporarily unavailable","printify returned 500","printify returned 502","printify returned 503","printify returned 504"], answer:"Printify’s server remained unavailable after Goldie’s automatic retries. Keep the completed drafts, wait a few minutes, then use Retry failed designs. If the same server code returns, no local file or token change will fix it; Printify must recover." },
];

export function findSupportArticle(query: string) {
  const normalized = query.toLowerCase().replace(/[’']/g, "'").trim();
  let best: { article: SupportArticle; score: number } | null = null;
  for (const article of SUPPORT_ARTICLES) {
    const score = article.triggers.reduce((total, trigger) => {
      const phrase = trigger.toLowerCase();
      if (normalized.includes(phrase)) return total + (phrase.length > 8 ? 5 : 3);
      return total + phrase.split(/\s+/).filter((word) => word.length > 3 && normalized.includes(word)).length;
    }, 0);
    if (!best || score > best.score) best = { article, score };
  }
  return best && best.score >= 2 ? best.article : null;
}
