"use client";
import { useEffect, useRef, useState, type ChangeEvent } from "react";
type UploadedPhoto={key:string;kind:"uploaded"|"mockup"|"size-guide";name:string;src:string};
export default function UploadedListingPhotos({productId,onCountChange}:{productId:string;onCountChange:(count:number)=>void}){
  const[photos,setPhotos]=useState<UploadedPhoto[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");const input=useRef<HTMLInputElement>(null);
  async function load(){const response=await fetch(`/api/etsy/images?productId=${encodeURIComponent(productId)}`),payload=await response.json() as {images?:UploadedPhoto[];error?:string};if(!response.ok)throw new Error(payload.error||"Your uploaded photos could not be loaded.");const next=(payload.images||[]).filter(photo=>photo.kind==="uploaded"||photo.kind==="mockup");setPhotos(next);onCountChange(next.length)}
  useEffect(()=>{let active=true;void load().catch(error=>{if(active)setMessage(error instanceof Error?error.message:"Your uploaded photos could not be loaded.")});return()=>{active=false}},[productId]);
  async function upload(event:ChangeEvent<HTMLInputElement>){const files=Array.from(event.target.files||[]);event.target.value="";if(!files.length)return;setBusy(true);setMessage("");try{const form=new FormData();form.set("productId",productId);form.set("kind","upload");files.forEach(file=>form.append("file",file));const response=await fetch("/api/etsy/images",{method:"POST",body:form}),payload=await response.json() as {error?:string};if(!response.ok)throw new Error(payload.error||"These photos could not be uploaded.");await load();setMessage(`✓ ${files.length} ${files.length===1?"photo":"photos"} added to this listing.`)}catch(error){setMessage(error instanceof Error?error.message:"These photos could not be uploaded.")}finally{setBusy(false)}}
  async function remove(photo:UploadedPhoto){setBusy(true);setMessage("");try{const response=await fetch(`/api/etsy/images?productId=${encodeURIComponent(productId)}&key=${encodeURIComponent(photo.key)}`,{method:"DELETE"}),payload=await response.json() as {error?:string};if(!response.ok)throw new Error(payload.error||"This photo could not be removed.");await load();setMessage("✓ Photo removed from this listing.")}catch(error){setMessage(error instanceof Error?error.message:"This photo could not be removed.")}finally{setBusy(false)}}
  return <div className="uploaded-listing-photos"><div className="task-panel-heading"><div><b>Add listing photos</b><p>Upload finished lifestyle mockups or any other photos you want buyers to see.</p></div><button type="button" disabled={busy||photos.length>=20} onClick={()=>input.current?.click()}>{busy?"Uploading…":"Upload photos"}</button><input ref={input} hidden multiple type="file" accept="image/png,image/jpeg,image/webp" onChange={event=>void upload(event)}/></div>{photos.length?<div className="uploaded-photo-grid">{photos.map(photo=><figure key={photo.key}><img src={photo.src} alt={photo.name}/><figcaption><span>{photo.name}</span><button type="button" disabled={busy} onClick={()=>void remove(photo)}>Remove</button></figcaption></figure>)}</div>:null}{message&&<p role="status">{message}</p>}</div>
}
