"use client";
import { useEffect, useRef, useState, type ChangeEvent } from "react";

type UploadedPhoto={key:string;kind:"uploaded"|"mockup"|"size-guide";name:string;src:string};

export default function UploadedListingPhotos({productId,onCountChange,sizeGuideName,batchSizeGuideName,onSizeGuideSaved}:{productId:string;onCountChange:(count:number)=>void;sizeGuideName?:string;batchSizeGuideName?:string;onSizeGuideSaved:(name:string)=>void}){
  const[photos,setPhotos]=useState<UploadedPhoto[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const photoInput=useRef<HTMLInputElement>(null),guideInput=useRef<HTMLInputElement>(null);
  const guide=sizeGuideName??batchSizeGuideName;

  async function load(){const response=await fetch(`/api/etsy/images?productId=${encodeURIComponent(productId)}`),payload=await response.json() as {images?:UploadedPhoto[];error?:string};if(!response.ok)throw new Error(payload.error||"Your uploaded photos could not be loaded.");const next=(payload.images||[]).filter(photo=>photo.kind==="uploaded"||photo.kind==="mockup");setPhotos(next);onCountChange(next.length)}
  useEffect(()=>{let active=true;void load().catch(error=>{if(active)setMessage(error instanceof Error?error.message:"Your uploaded photos could not be loaded.")});return()=>{active=false}},[productId]);

  async function uploadPhotos(event:ChangeEvent<HTMLInputElement>){const files=Array.from(event.target.files||[]);event.target.value="";if(!files.length)return;setBusy(true);setMessage("");try{const form=new FormData();form.set("productId",productId);form.set("kind","upload");files.forEach(file=>form.append("file",file));const response=await fetch("/api/etsy/images",{method:"POST",body:form}),payload=await response.json() as {error?:string};if(!response.ok)throw new Error(payload.error||"These photos could not be uploaded.");await load();setMessage(`✓ ${files.length} ${files.length===1?"photo":"photos"} added to this listing.`)}catch(error){setMessage(error instanceof Error?error.message:"These photos could not be uploaded.")}finally{setBusy(false)}}
  async function removePhoto(photo:UploadedPhoto){setBusy(true);setMessage("");try{const response=await fetch(`/api/etsy/images?productId=${encodeURIComponent(productId)}&key=${encodeURIComponent(photo.key)}`,{method:"DELETE"}),payload=await response.json() as {error?:string};if(!response.ok)throw new Error(payload.error||"This photo could not be removed.");await load();setMessage("✓ Photo removed from this listing.")}catch(error){setMessage(error instanceof Error?error.message:"This photo could not be removed.")}finally{setBusy(false)}}
  async function uploadGuide(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value="";if(!file||busy)return;setBusy(true);setMessage("Saving size guide…");try{const form=new FormData();form.set("productId",productId);form.set("kind","size-guide");form.set("file",file);const response=await fetch("/api/etsy/images",{method:"POST",body:form}),payload=await response.json() as {error?:string};if(!response.ok)throw new Error(payload.error||"This size guide could not be saved.");onSizeGuideSaved(file.name);setMessage("✓ Size guide added to this listing.")}catch(error){setMessage(error instanceof Error?error.message:"This size guide could not be saved.")}finally{setBusy(false)}}
  async function removeGuide(){if(busy)return;setBusy(true);setMessage("Removing size guide…");try{const response=await fetch(`/api/etsy/images?productId=${encodeURIComponent(productId)}&kind=size-guide`,{method:"DELETE"}),payload=await response.json() as {error?:string};if(!response.ok)throw new Error(payload.error||"The size guide could not be removed.");onSizeGuideSaved("");setMessage("✓ Size guide removed from this listing.")}catch(error){setMessage(error instanceof Error?error.message:"The size guide could not be removed.")}finally{setBusy(false)}}

  return <div className="uploaded-listing-photos" aria-busy={busy} aria-label="Add listing photos or a size guide">
    <div className="task-panel-heading"><div><b>Add Listing Photos/Size Guide</b><p>Add finished mockups, other listing photos, or an optional size guide here.</p></div><div className="listing-upload-actions"><button type="button" disabled={busy||photos.length>=20} onClick={()=>photoInput.current?.click()}>{busy?"Working…":"Upload photos"}</button><button type="button" disabled={busy} onClick={()=>guideInput.current?.click()}>{guide?"Change size guide":"Add size guide"}</button></div><input ref={photoInput} hidden multiple type="file" accept="image/png,image/jpeg,image/webp" onChange={event=>void uploadPhotos(event)}/><input ref={guideInput} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={event=>void uploadGuide(event)}/></div>
    {guide?<div className="uploaded-size-guide"><span><b>Size guide added</b><small>{guide}</small></span><button type="button" disabled={busy} onClick={()=>void removeGuide()}>Remove</button></div>:null}
    {photos.length?<div className="uploaded-photo-grid">{photos.map(photo=><figure key={photo.key}><img src={photo.src} alt="Uploaded listing photo"/><figcaption><button type="button" disabled={busy} onClick={()=>void removePhoto(photo)}>Remove</button></figcaption></figure>)}</div>:null}
    {message&&<p role="status">{message}</p>}
  </div>
}
