'use client';
import {useEffect,useRef,useState} from 'react';
import {suggestedCluster,type NicheListing} from '@/app/niche-research-model';
import type {ResearchView} from '@/app/niche-research-view';
type Reply={error?:string;project:ResearchView;projects?:Saved[]};
type Saved={id:string;name:string;phase:string;monitoring:boolean};
const productName=(s:string)=>({tee:'Shirts',crewneck:'Sweatshirts',hoodie:'Hoodies',mug:'Mugs',tote:'Totes',longSleeve:'Long sleeves',phoneCase:'Phone cases',other:'Other products',digital:'Digital downloads',mixedApparel:'Mixed apparel'}[s]??s);
const date=(s:number)=>new Date(s*1000).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});
const price=(n:number,currency:string)=>{try{return new Intl.NumberFormat(undefined,{style:'currency',currency}).format(n/100);}catch{return `${(n/100).toFixed(2)} ${currency}`;}};
export default function ResearchClient(){
 const [saved,setSaved]=useState<Saved[]>([]),[p,setP]=useState<ResearchView|null>(null),[seed,setSeed]=useState(''),[terms,setTerms]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState<'brief'|'shops'|'listings'|'buyers'>('brief'),[listingIds,setListingIds]=useState<number[]|null>(null),[order,setOrder]=useState('reviews'),[shopFilter,setShopFilter]=useState('qualified'),[shown,setShown]=useState(40);
 const runner=useRef(false),alive=useRef(true),photoKey=useRef('');
 useEffect(()=>{alive.current=true;void loadSaved();return()=>{alive.current=false;runner.current=false;}},[]);
 async function loadSaved(){try{const r=await fetch('/api/niche-research'),b=await r.json() as Reply;if(!r.ok)throw Error(b.error??'Your niches could not be loaded.');setSaved(b.projects??[]);}catch(e){setError(String((e as Error).message));}}
 async function action(action:string,id:string,data:Record<string,unknown>={}){const r=await fetch('/api/niche-research',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id,...data})}),b=await r.json() as Reply;if(b.project&&alive.current)setP(b.project);if(!r.ok)throw Error(b.error??'This update could not be completed.');return b.project as ResearchView;}
 async function run(id:string){if(runner.current)return;runner.current=true;setBusy(true);setError('');try{while(runner.current&&alive.current){const next=await action('advance',id);if(next.phase==='ready')break;}}catch(e){setError((e as Error).message);}finally{runner.current=false;if(alive.current){setBusy(false);void loadSaved();}}}
 async function open(id:string){if(busy)return;setError('');setNotice('');setBusy(true);try{const r=await fetch(`/api/niche-research?id=${encodeURIComponent(id)}`),b=await r.json() as Reply;if(!r.ok)throw Error(b.error??'This request could not be completed.');setP(b.project);setTab('brief');photoKey.current='';}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function create(){if(!seed.trim()||busy)return;setError('');setBusy(true);try{const next=await action('create','',{name:seed,phrases:terms.split('\n').map(t=>t.trim()).filter(Boolean)});setBusy(false);void loadSaved();void run(next.id);}catch(e){setError((e as Error).message);setBusy(false);}}
 async function mutate(kind:string,data:Record<string,unknown>={}){if(!p||busy)return;setBusy(true);setError('');try{await action(kind,p.id,data);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 // Poll saved progress; the server clock continues when the browser is closed.
 useEffect(()=>{if(!p||busy)return;const id=p.id;const timer=setInterval(()=>{void fetch(`/api/niche-research?id=${id}`).then(async r=>{if(r.ok){const b=await r.json() as Reply;if(alive.current)setP(b.project);}}).catch(()=>{});},30000);return()=>clearInterval(timer);},[p?.id,busy]);
 const a=p?.analysis;
 const listingMap=new Map<number,NicheListing>();for(const l of p?.listings??[])if(!listingMap.has(l.id))listingMap.set(l.id,l);for(const s of p?.shops??[])for(const l of s.listings)if(!listingMap.has(l.id))listingMap.set(l.id,l);for(const l of [...(a?.repeated??[]),...(a?.young??[]),...(p?.newlyObserved??[])])if(!listingMap.has(l.id))listingMap.set(l.id,l);
 function evidence(ids:number[]){setListingIds(ids);setShown(40);setTab('listings');}
 async function bank(){if(!p)return;setBusy(true);setError('');try{const keywords=p.analysis.phrases.filter(x=>x.shops>=2).slice(0,20).map(x=>x.phrase);const r=await fetch('/api/keyword-lists',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:p.name.slice(0,70)+' research',keywords:keywords.length?keywords:p.phrases})}),b=await r.json() as Reply;if(!r.ok)throw Error(b.error??'This request could not be completed.');setNotice('Keyword bank saved. It is available in the existing Listing Factory keyword-bank selector.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const allListings=[...listingMap.values()].filter(l=>listingIds?listingIds.includes(l.id):!p?.selected.length||p.selected.includes(l.shopId)).sort((x,y)=>order==='newest'?(y.createdAt??0)-(x.createdAt??0):order==='price'?(x.currency.localeCompare(y.currency)||(x.price??Infinity)-(y.price??Infinity)):(p?.listings.find(l=>l.id===y.id)?.reviews30??0)-(p?.listings.find(l=>l.id===x.id)?.reviews30??0));
 const shownIds=tab==='shops'?(p?.shops??[]).flatMap(s=>s.listings.slice(0,3).map(l=>l.id)).slice(0,48):allListings.slice(Math.max(0,shown-40),shown).map(l=>l.id);
 useEffect(()=>{if(!p||busy||!shownIds.length)return;const key=p.id+':'+shownIds.join(',')+':'+Math.floor(Date.now()/3600000);if(photoKey.current===key)return;photoKey.current=key;void action('photos',p.id,{listingIds:shownIds}).catch(()=>{photoKey.current='';});},[p?.id,p?.phase,p?.updatedAt,busy,tab,shown,listingIds,order]);
 return <main className="nr"><header className="nr-head"><div><a className="nr-back" href="/market-watch?tab=shops">← Shop Watch</a><p className="nr-eyebrow">MARKET WATCH / NICHE RESEARCH</p><h1>{p?p.name:'Niche research'}</h1>{!p&&<p>Find shops with relevant listings and purchase reviews. Follow the products, phrases and buyer needs appearing across them.</p>}</div></header>
 {(error||p?.error)&&<div className="nr-error" role="alert">{error||p?.error}</div>}{notice&&<p className="nr-notice" role="status">{notice}</p>}
 {!p?<><section className="nr-search"><label htmlFor="nr-seed">Which niche are you researching?</label><div className="nr-search-row"><input id="nr-seed" value={seed} onChange={e=>{setSeed(e.target.value);setTerms(suggestedCluster(e.target.value).join('\n'));}} placeholder="e.g. romance reader shirt" maxLength={100}/><button className="nr-primary" disabled={busy||!seed.trim()||!terms.trim()} onClick={()=>void create()}>Find 10 shops →</button></div><details><summary>Related phrases included · edit the search</summary><p>Direct wording variations and product alternatives stay tied to your niche. Add adjacent niches only if you want them included.</p><label htmlFor="nr-terms">Search phrases · one per line, up to 8</label><textarea id="nr-terms" rows={6} value={terms} onChange={e=>setTerms(e.target.value)}/></details><p className="nr-muted">Your niche updates automatically after the first check. Initial research may take several minutes; you can leave and return.</p></section><section><h2>Your niches</h2>{!saved.length?<p className="nr-muted">Your ongoing research will appear here.</p>:<div className="nr-saved">{saved.map(s=><button disabled={busy} key={s.id} onClick={()=>void open(s.id)}><strong>{s.name}</strong><span>{s.phase==='ready'?(s.monitoring?'Monitoring':'Paused'):'Research in progress'} →</span></button>)}</div>}</section></>:<>
 <div className="nr-project-head"><div><button className="nr-text" disabled={busy} onClick={()=>{setP(null);void loadSaved();}}>← All niches</button><p className="nr-muted">{p.phase==='ready'?`Updated ${date(p.updatedAt)} · ${p.monitoring?'Automatic checks every 6 hours':'Monitoring paused'}`:''}</p></div><div className="nr-actions"><button disabled={busy} onClick={()=>void mutate('monitor',{enabled:!p.monitoring})}>{p.monitoring?'Pause updates':'Resume updates'}</button>{busy?<button onClick={()=>{runner.current=false;}}>Continue in background</button>:<button onClick={()=>p.phase==='ready'?void mutate('refresh'):void run(p.id)}>{p.phase==='ready'?'Refresh now':'Continue research'}</button>}</div></div>
 {p.phase!=='ready'&&<section className="nr-progress" role="status"><strong>{p.qualified} qualified shops found</strong><p>{p.checked} shops checked · {p.candidates} candidates discovered. {p.progress}.</p></section>}
 {p.phase==='ready'&&p.qualified<10&&<p className="nr-notice">Found {p.qualified} qualifying shops in the available search results. We haven’t filled the panel with unrelated shops.</p>}
 <details className="nr-cluster"><summary>Searching {p.phrases.length} related phrases</summary><div className="nr-chips">{p.phrases.map(t=><span key={t}>{t}</span>)}</div></details>
 <nav className="nr-tabs" aria-label="Niche research sections">{(['brief','shops','listings','buyers'] as const).map(t=><button key={t} aria-current={tab===t?'page':undefined} onClick={()=>{setTab(t);setListingIds(null);}}>{({brief:'Niche briefing',shops:'Your shops',listings:'Listing evidence',buyers:'Buyer insights'})[t]}</button>)}</nav>
 {tab==='brief'&&a&&<>
 <div className="nr-stats"><div><strong>{a.shops}</strong><span>shops in your panel</span></div><div><strong>{a.listings}</strong><span>matching active listings</span></div><div><strong>{a.reviews30}</strong><span>reviews · last 30 days</span></div><div><strong>{a.products.filter(x=>x.reviews>0).length}</strong><span>product types reviewed</span></div></div>
 {!a.shops?<section className="nr-card"><h3>Your briefing builds from qualified shops</h3><p>As shops qualify, select them under Your shops—or let Goldie suggest the first 10. Emerging shops appear separately.</p><button onClick={()=>setTab('shops')}>See shops checked</button></section>:<>
 <section><div className="nr-section-head"><h2>What’s worth testing</h2><span>Patterns across independent shops</span></div>{a.opportunities.length?<div className="nr-opportunities">{a.opportunities.map(o=><article className="nr-card" key={o.phrase}><span className="nr-kicker">{o.shops} SHOPS · {o.reviews} RECENT REVIEWS</span><h3>{o.phrase}</h3><p>{o.hypothesis.replace(/\b(tee|crewneck|hoodie|mug|tote)\b/g,x=>productName(x).toLowerCase())}</p><div className="nr-actions"><button onClick={()=>evidence(o.listingIds)}>See supporting listings →</button><a href={`/trademark?phrase=${encodeURIComponent(o.phrase)}`}>Check trademark</a></div><details><summary>What this does—and doesn’t—show</summary><p>{o.caution} Phrases come from titles and tags, not buyers’ search terms.</p></details></article>)}</div>:<div className="nr-card"><h3>No strong cross-shop pattern yet</h3><p>Recommendations appear when a phrase has recent review activity across at least three shops. You can still explore the products and buyer feedback below.</p></div>}</section>
 <section className="nr-card"><h2>What changed</h2>{p.newReviewListings.length>0&&<p>{p.newReviewListings.length} listings received reviews since the previous recorded check. <button onClick={()=>evidence(p.newReviewListings.map(l=>l.id))}>View newly reviewed listings</button></p>}{p.newlyObserved.length>0&&<p>{p.newlyObserved.length} recent listings created since this niche was started. <button onClick={()=>evidence(p.newlyObserved.map(l=>l.id))}>View new listings</button></p>}{p.changes?<><p>Compared with {date(p.changes.since)}, using the same shops.</p><div className="nr-change-grid"><strong>{p.changes.listings>0?'+':''}{p.changes.listings} matching active listings</strong><strong>{p.changes.reviews30>0?'+':''}{p.changes.reviews30} reviews in the rolling 30-day window</strong></div>{p.changes.phrases.slice(0,6).map(c=><p key={c.phrase}><b>{c.phrase}</b> · {c.listings>0?'+':''}{c.listings} listings · {c.reviews>0?'+':''}{c.reviews} recent reviews. {c.listings>0&&c.reviews<=0?'Supply expanded without an increase in recent review activity.':c.reviews>0&&c.shops>=2?'Review activity increased across the tracked market.':''}</p>)}</>:<p>Your first completed check establishes the baseline. Comparisons appear after another day of observations, using the same shops.</p>}</section>
 <section><div className="nr-section-head"><h2>Products receiving reviews</h2><span>Last 30 days · listed prices</span></div><div className="nr-table-wrap"><table><thead><tr><th>Product</th><th>Active listings</th><th>Reviews</th><th>Shops with reviews</th><th>Middle price range</th><th/></tr></thead><tbody>{a.products.map(x=><tr key={x.product}><td>{productName(x.product)}</td><td>{x.listings}</td><td>{x.reviews}</td><td>{x.shops}</td><td>{x.prices.map(v=><div key={v.currency}>{price(v.low,v.currency)}–{price(v.high,v.currency)} <small>({v.count})</small></div>)}</td><td><button onClick={()=>evidence(x.listingIds)}>View</button></td></tr>)}</tbody></table></div></section>
 <div className="nr-two">{a.young.length>0&&<section className="nr-card"><h3>Newer listings finding buyers</h3><p>{a.young.length} displayed listings created in the last 90 days received reviews in the last 30 days.</p><button onClick={()=>evidence(a.young.map(l=>l.id))}>View newer listings</button></section>}{a.smaller.length>0&&<section className="nr-card"><h3>Activity in smaller shops</h3><p>{a.smaller.length} displayed listings with recent reviews belong to shops with 100 or fewer active listings.</p><button onClick={()=>evidence(a.smaller.map(l=>l.id))}>View smaller-shop examples</button></section>}</div>
 <section className="nr-card"><h2>Recurring phrases</h2><p>Tags on reviewed listings—not search attribution. Sorted by number of shops receiving reviews, then review count.</p><div className="nr-phrase-list">{a.phrases.filter(x=>x.reviews>0).slice(0,12).map(x=><button key={x.phrase} onClick={()=>evidence(x.listingIds)}><strong>{x.phrase}</strong><span>{x.shops} shops · {x.reviews} reviews / 30 days</span></button>)}</div><div className="nr-actions"><button disabled={busy} onClick={()=>void bank()}>Save phrases to Keyword Bank</button><a className="nr-primary p-button p-button-primary" href="/listing-factory?step=setup">Open Listing Factory →</a></div></section>
 </>}
 </>}
 {tab==='shops'&&<section><div className="nr-section-head"><div><h2>Find the right shops to follow</h2><p>{p.selected.length} selected · up to 15 shops per panel</p></div><label>Show <select value={shopFilter} onChange={e=>setShopFilter(e.target.value)}><option value="qualified">Qualified shops</option><option value="emerging">Emerging shops</option><option value="all">All checked shops</option></select></label></div><div className="nr-shop-grid">{p.shops.filter(s=>shopFilter==='all'||shopFilter==='emerging'?shopFilter==='all'||s.metrics.emerging:s.metrics.qualified||s.metrics.focused).map(s=><article className="nr-card" key={s.id}><div className="nr-section-head"><h3>{s.name}</h3><label className="nr-select"><input type="checkbox" disabled={busy||!s.complete||!p.selected.includes(s.id)&&p.selected.length>=15} checked={p.selected.includes(s.id)} onChange={()=>void mutate('select',{selected:p.selected.includes(s.id)?p.selected.filter(id=>id!==s.id):[...p.selected,s.id]})}/> Follow</label></div><span className="nr-kicker">{s.metrics.qualified?'ESTABLISHED':s.metrics.focused?'NICHE FOCUSED':s.metrics.emerging?'EMERGING':'CHECKING'}</span><dl className="nr-shop-stats"><div><dt>Matching listings</dt><dd>{s.metrics.matching}{!s.complete?' found':''}</dd></div><div><dt>Reviewed listings / year</dt><dd>{s.complete?s.metrics.reviewedListings:'Checking…'}</dd></div><div><dt>Reviews / 90 days</dt><dd>{s.complete?s.metrics.reviews90:'Checking…'}</dd></div><div><dt>Niche concentration</dt><dd>{s.metrics.concentration===null?'Checking…':`${Math.round(s.metrics.concentration*100)}%`}</dd></div></dl><p className="nr-muted">{s.metrics.latestReview?`Latest niche review ${date(s.metrics.latestReview)}`:s.complete?'No matching reviews found':'Review check in progress'}</p>{s.metrics.reviewsPrior90!==null&&<p className="nr-muted">{s.metrics.reviews90} reviews in the last 90 days · {s.metrics.reviewsPrior90} in the previous 90 days</p>}<div className="nr-mini-images">{s.listings.slice(0,3).map(l=><a href={`https://www.etsy.com/listing/${l.id}`} target="_blank" rel="noreferrer" key={l.id}>{l.image?<img src={l.image} alt={l.title} width={88} height={88} loading="lazy"/>:<span>View listing ↗</span>}</a>)}</div><div className="nr-actions"><button onClick={()=>evidence((p.listings??[]).filter(l=>l.shopId===s.id).map(l=>l.id))}>View niche listings</button><a href={s.url} target="_blank" rel="noreferrer">Full Etsy shop ↗</a></div></article>)}</div>{!p.shops.length&&<p className="nr-muted">Shops appear here as their catalogs are checked.</p>}</section>}
 {tab==='listings'&&<section><div className="nr-section-head"><div><h2>Listing evidence</h2><p>{listingIds?'Listings supporting the selected finding':'Reviewed listings and current shop examples'} · reviews shown for the last 30 days</p></div><label>Sort <select value={order} onChange={e=>setOrder(e.target.value)}><option value="reviews">Most reviews · last 30 days</option><option value="newest">Newest listing first</option><option value="price">Price, within currency</option></select></label></div>{listingIds&&<button onClick={()=>setListingIds(null)}>Show all examples</button>}<div className="nr-listings">{allListings.slice(0,shown).map(l=><a className="nr-listing" href={`https://www.etsy.com/listing/${l.id}`} target="_blank" rel="noreferrer" key={l.id}>{l.image&&Date.now()/1000-l.displayAt<21600?<img src={l.image} alt="" width={100} height={100} loading="lazy"/>:<div className="nr-photo-empty">Open listing ↗</div>}<div><h3>{l.title}</h3><p>{l.price!==null&&l.currency?price(l.price,l.currency):'Price unavailable'} · {p?.listings.find(x=>x.id===l.id)?.reviewsComplete?`${p.listings.find(x=>x.id===l.id)?.reviews30??0} reviews / 30 days`:'Reviews being checked'}</p><small>{l.createdAt?`Created ${date(l.createdAt)}`:'Creation date unavailable'} · {l.active?'Active at last check':'No longer in active catalog'}</small></div></a>)}</div>{allListings.length>shown&&<button className="nr-load" onClick={()=>setShown(n=>n+40)}>Load more listings</button>}{!allListings.length&&<p className="nr-muted">No listings match this view yet.</p>}</section>}
 {tab==='buyers'&&a&&<section><div className="nr-section-head"><h2>What buyers mention</h2><span>Matching review text · last 365 days</span></div><p>Recurring occasions, recipients and product feedback. These are mentions in reviews, not a survey of every buyer.</p><div className="nr-two">{a.buyerThemes.map(t=><article className="nr-card" key={t.name}><span className="nr-kicker">{t.count} REVIEWS · {t.shops} SHOPS</span><h3>{t.name}</h3>{t.examples.map(r=><blockquote key={r.transactionId}><p>“{r.text.slice(0,230)}{r.text.length>230?'…':''}”</p><footer>{date(r.at)} · {r.rating??'—'}/5 · <a href={`https://www.etsy.com/listing/${r.listingId}#reviews`} target="_blank" rel="noreferrer">Listing & reviews ↗</a></footer></blockquote>)}</article>)}</div>{!a.buyerThemes.length&&<p className="nr-muted">No repeated buyer themes found in the available matching reviews yet.</p>}</section>}
 </>}
 </main>;
}
