'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {dailySummary,type UpdateItem} from '../platform-update-model';
type Brief={day:string;items:UpdateItem[];status:string;baseline:boolean;checkedAt:number;owner:boolean;sources:Array<{name:string;url:string}>};
export default function PlatformUpdate({compact=false}:{compact?:boolean}){const [data,setData]=useState<Brief|null>(null),[error,setError]=useState(''),[running,setRunning]=useState(false),[adminResult,setAdminResult]=useState('');
 async function load(){try{const r=await fetch('/api/platform-updates',{cache:'no-store'});if(!r.ok)throw new Error();setData(await r.json());setError('');}catch{setError('Today’s update couldn’t be loaded.');}}
 useEffect(()=>{void load();},[]);
 async function check(){setRunning(true);setAdminResult('');try{const r=await fetch('/api/platform-updates/tick',{method:'POST'});const body=await r.json();if(!r.ok)throw new Error(body.error||'Source check failed');setAdminResult(body.busy?'A source check is already running.':body.failed?`${body.failed} source checks need attention. ${body.failures.map((f:any)=>`${f.source}: ${f.error}`).join(' · ')}`:'Official sources checked.');await load();}catch(e){setAdminResult(e instanceof Error?e.message:'Source check failed');}finally{setRunning(false);}}
 const summary=error||!data?'':data.status!=='ready'?'Today’s source check is not complete yet.':data.baseline&&!data.items.length?'First check complete. New platform changes will appear here.':dailySummary(data.items);
 const date=data?new Date(data.day+'T12:00:00Z').toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'}):'';
 if(compact)return <section className="platform-brief-card" data-quiet={data?.status==='ready'&&!data.items.length&&!error?"true":undefined} aria-labelledby="platform-brief-title"><div><p className="platform-brief-eyebrow">ETSY + PRINTIFY</p><h2 id="platform-brief-title">{data?.status==='ready'&&!data.items.length?"No new updates":"Etsy + Printify updates"}</h2><p role="status">{error||(!data?'Checking today’s update…':summary)}</p></div>{error?<button type="button" onClick={()=>void load()}>Try again</button>:<Link href="/platform-updates">{data?.status==='ready'&&!data.items.length?'View checked sources':'Read today’s update'} <span aria-hidden="true">→</span></Link>}</section>;
 return <main className="platform-brief-page"><Link href="/home" className="platform-brief-back">← Home</Link><header><p className="platform-brief-eyebrow">ETSY + PRINTIFY UPDATES{date?` · ${date}`:''}</p><h1>Today’s update</h1><p role="status">{error||(!data?'Loading today’s update…':summary)}</p>{error&&<button type="button" onClick={()=>void load()}>Try again</button>}</header>{data?.items.map(item=><article key={item.id} className="platform-brief-item"><div className="platform-brief-labels"><strong data-priority={item.priority}>{item.priority}</strong><span>{item.platform}</span><span>{item.evidence}</span></div><h2>{item.title}</h2><p>{item.impact}</p><p><b>What to do:</b> {item.action}</p><a href={item.sourceUrl} target="_blank" rel="noreferrer">Original {item.platform} source ↗</a></article>)}{data&&<footer><p>Updated daily at 6 AM Pacific, or sooner for urgent changes.</p><details><summary>Official sources</summary><ul>{data.sources.map(s=><li key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.name} ↗</a></li>)}</ul></details>{data.owner&&<details className="platform-brief-admin"><summary>Owner controls</summary><button type="button" disabled={running} onClick={()=>void check()}>{running?'Checking official sources…':'Check official sources'}</button>{adminResult&&<p role="status">{adminResult}</p>}</details>}</footer>}</main>;
}
