"use client";
import { useState } from "react";
import { PLANS, type PlanKey } from "@/app/plan-limits";

export default function SignupClient({signedIn,checkout,returnTo="/listing-factory"}:{signedIn:boolean;checkout?:string;returnTo?:string}){
  const[loading,setLoading]=useState<PlanKey|null>(null),[error,setError]=useState("");
  async function choose(plan:PlanKey){setLoading(plan);setError("");const response=await fetch("/api/billing/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({plan})});const result=await response.json() as {url?:string;error?:string};if(!response.ok||!result.url){setError(result.error||"Checkout could not start.");setLoading(null);return}window.location.href=result.url}
  return <main className="signup-page"><header className="signup-brand"><span>Goldie</span><b>LISTING FACTORY</b></header><section className="signup-hero"><h1>Automated Etsy listings like you’ve never seen before.</h1><p>Let Goldie AI be your ultimate automation assistant.</p><p>Start with three days free. Create up to 10 Printify drafts and 5 AI lifestyle mockups, then keep going on the plan you choose.</p></section>
    {checkout==="success"&&<div className="signup-notice success"><b>Your Goldie access is being activated.</b><span>If this is your first subscription, your three-day trial starts now. Stripe is confirming everything securely.</span><a href={returnTo}>Open Listing Factory</a></div>}
    {checkout==="canceled"&&<div className="signup-notice"><b>No charge was made.</b><span>Your plan is still waiting whenever you are ready.</span></div>}
    {!signedIn&&<div className="signup-signin"><div><b>First, create your secure Goldie account</b><span>Your saved products, batches, keyword banks, and mockups stay attached to this account.</span></div><a href={`/signin-with-chatgpt?return_to=${encodeURIComponent(returnTo)}`}>Sign in to continue</a></div>}
    <h2 className="signup-plan-heading">Choose your plan</h2><section className="signup-plans">{(Object.keys(PLANS) as PlanKey[]).map((key,index)=>{const plan=PLANS[key];return <article className={index===0?"featured":""} key={key}>{index===0&&<span className="plan-ribbon">MOST POPULAR</span>}<p>{plan.name}</p><h2>${plan.price}<small>/month</small></h2><ul><li><b>{plan.drafts}</b> Printify drafts each month</li><li><b>{plan.aiMockups}</b> AI lifestyle mockups each month</li><li><b>{plan.mockupSets}</b> saved mockup sets</li><li>Up to <b>{plan.mockupsPerSet}</b> mockups in each set</li></ul><button disabled={!signedIn||Boolean(loading)} onClick={()=>void choose(key)}>{loading===key?"Opening secure checkout…":signedIn?`Choose ${plan.name}`:"Sign in first"}</button></article>})}</section>
    {error&&<p className="signup-error" role="alert">{error}</p>}<footer className="signup-footer"><span>Card required. Cancel through Stripe before the trial ends and you will not be charged.</span><span>Powered by Goldie AI · © 2026 Be A Wolf Biz</span></footer></main>
}
