import Link from "next/link";
import FactoryShell from "../factory-shell";
import { accountSignInPath, getChatGPTUser } from "@/app/chatgpt-auth";
import { etsyBudget } from "@/app/api/etsy/client";
import { isOwner, runtime } from "@/app/mastermind/access";

type CountRow={status:string;count:number};type FailedRow={product_id:string;attempts:number;last_error:string|null;updated_at:string};type RunRow={status:string;processed:number;error:string|null;started_at:string};
const date=(value:string|null)=>value?new Date(`${value.replace(" ","T").replace(/Z$/i,"")}Z`).toLocaleString():"Never";

export default async function OperationsPage(){
  const user=await getChatGPTUser();if(!user)return <main className="operations-auth"><Link href={accountSignInPath("/operations")}>Owner sign in</Link></main>;if(!isOwner(user))return <main className="operations-auth"><h1>Not authorized</h1></main>;
  const db=runtime().DB!;
  const [counts,oldest,average,rateLimits,failed,runs,budget]=await Promise.all([
    db.prepare("SELECT status,COUNT(*) count FROM etsy_publish_items GROUP BY status").all<CountRow>(),db.prepare("SELECT created_at FROM etsy_publish_items WHERE status='queued' ORDER BY created_at LIMIT 1").first<{created_at:string}>(),
    db.prepare("SELECT AVG(api_calls) average,MAX(api_calls) maximum,COUNT(*) samples FROM etsy_listing_usage WHERE api_calls>0").first<{average:number;maximum:number;samples:number}>(),db.prepare("SELECT COALESCE(SUM(rate_limited),0) count FROM etsy_api_usage_buckets WHERE bucket>=strftime('%Y-%m-%dT%H','now','-24 hours')").first<{count:number}>(),
    db.prepare("SELECT product_id,attempts,last_error,updated_at FROM etsy_publish_items WHERE status='failed' ORDER BY updated_at DESC LIMIT 12").all<FailedRow>(),db.prepare("SELECT status,processed,error,started_at FROM etsy_worker_runs ORDER BY started_at DESC LIMIT 10").all<RunRow>(),etsyBudget(),
  ]);
  const map=Object.fromEntries(counts.results.map(row=>[row.status,Number(row.count)]));
  return <FactoryShell active="factory" title="Operations"><div className="management-page operations-page interior-page"><header><p className="mini-label">OWNER ONLY</p><h1>Etsy draft transfer history</h1><p>Historical records from the retired publishing queue. Current Etsy Drafts transfers run through each batch’s final step.</p></header><section className="operations-status healthy"><span/><div><b>No legacy publishing work is waiting</b><p>The old scheduled publisher is intentionally off. Its last heartbeat is not a service warning.</p></div></section><section className="operations-metrics"><article><span>Shared Etsy quota</span><b>{budget.used.toLocaleString()} / {budget.limit.toLocaleString()}</b><p>{budget.remaining.toLocaleString()} safe calls remain after the 20% reserve.</p></article><article><span>Legacy queue</span><b>{map.queued||0} waiting</b><p>{map.running||0} processing · oldest queued {oldest?.created_at?date(oldest.created_at):"none"}</p></article><article><span>Historical API cost</span><b>{Number(average?.average||0).toFixed(1)} calls</b><p>Average per listing across {average?.samples||0} listings. Highest: {average?.maximum||0}.</p></article><article><span>Last 24 hours</span><b>{rateLimits?.count||0} rate limits</b><p>{map.completed||0} historical completed records · {map.failed||0} need attention.</p></article></section><section className="operations-columns"><article><h2>Legacy failures</h2>{failed.results.length?<div className="operations-list">{failed.results.map(row=><div key={row.product_id}><b>{row.product_id}</b><span>{row.attempts} attempts · {date(row.updated_at)}</span><p>{row.last_error||"No error was recorded."}</p></div>)}</div>:<p className="operations-empty">No failed listings.</p>}</article><article><h2>Historical worker runs</h2>{runs.results.length?<div className="operations-list">{runs.results.map((row,index)=><div key={`${row.started_at}-${index}`}><b>{row.status} · {row.processed} processed</b><span>{date(row.started_at)}</span>{row.error&&<p>{row.error}</p>}</div>)}</div>:<p className="operations-empty">No historical runs.</p>}</article></section></div></FactoryShell>
}
