import { NextResponse } from "next/server";
import { getChatGPTUser } from "@/app/chatgpt-auth";

type Details={category:string;attributes:Record<string,string>;optional:Record<string,string>;blurb:string;confidence:"high"|"review"};
const validImage=(value:unknown):value is string=>typeof value==="string"&&/^data:image\/(png|jpeg|webp);base64,/i.test(value)&&value.length<18*1024*1024;
const clean=(value:unknown)=>String(value||"").replace(/[<>]/g,"").trim().slice(0,300);
export async function POST(request:Request){
  const user=await getChatGPTUser();if(!user)return NextResponse.json({error:"Sign in to prepare Etsy details."},{status:401});
  const body=await request.json() as {mode?:"details"|"title";image?:string;product?:{blueprintTitle?:string;brand?:string;model?:string;description?:string};title?:string;tags?:string[];keywords?:string[];useCommas?:boolean};
  if(!validImage(body.image))return NextResponse.json({error:"Goldie could not read this design safely."},{status:400});
  const key=process.env.FAL_KEY;if(!key)return NextResponse.json({error:"Automatic Etsy details are temporarily unavailable."},{status:503});
  if(body.mode==="title"){
    const keywords=[...new Set((body.keywords||[]).map(clean).filter(Boolean))].slice(0,13);if(!keywords.length)return NextResponse.json({error:"Choose keyword phrases before asking Goldie to build the title."},{status:400});
    const titleResponse=await fetch("https://fal.run/openrouter/router/vision",{method:"POST",headers:{Authorization:`Key ${key}`,"Content-Type":"application/json"},body:JSON.stringify({image_urls:[body.image],model:"google/gemini-2.5-flash",temperature:0,system_prompt:"Return only compact valid JSON. Never use markdown.",prompt:`Build one readable Etsy title, maximum 140 characters, using only these seller-validated keyword phrases: ${JSON.stringify(keywords)}. Product: ${JSON.stringify(body.product||{})}. Preserve exact keyword wording wherever possible, remove duplicate meaning, do not invent search terms or claims, and do not add a holiday or occasion unless supplied. ${body.useCommas?"Separate keyword phrases with commas.":"Write a natural title without commas while keeping the phrases recognizable."} Return {"title":"..."}.`})});
    const titlePayload=await titleResponse.json() as {output?:string;detail?:string};if(!titleResponse.ok)return NextResponse.json({error:titlePayload.detail||"Goldie could not build this title."},{status:502});const match=titlePayload.output?.match(/\{[\s\S]*\}/);if(!match)return NextResponse.json({error:"Goldie could not read the prepared title."},{status:502});const title=clean((JSON.parse(match[0]) as {title?:string}).title).slice(0,140);if(!title)return NextResponse.json({error:"Goldie could not build a usable title."},{status:502});return NextResponse.json({title});
  }
  const response=await fetch("https://fal.run/openrouter/router/vision",{method:"POST",headers:{Authorization:`Key ${key}`,"Content-Type":"application/json"},body:JSON.stringify({image_urls:[body.image],model:"google/gemini-2.5-flash",temperature:0,system_prompt:"Return only compact valid JSON. Never use markdown.",prompt:`Prepare Etsy listing details for a print-on-demand product. Product facts: ${JSON.stringify(body.product||{})}. Final title: ${clean(body.title)}. Selected tags: ${JSON.stringify((body.tags||[]).slice(0,13))}. Use product facts, not the artwork, to determine physical attributes and the closest Etsy category. Inspect the artwork only for contextual relevance. Never fill holiday, occasion, recipient, or style merely because a field exists; omit optional fields unless clearly supported. Write a natural 1-2 sentence design-specific introduction using at most 2 exact keyword phrases from the title or tags, without keyword stuffing or unsupported claims. Return {"category":"...","attributes":{"Sleeve length":"..."},"optional":{"Holiday":"..."},"blurb":"...","confidence":"high"|"review"}. Attribute names must suit this product type; tote, mug, poster, shirt, and sweatshirt fields differ.`})});
  const payload=await response.json() as {output?:string;detail?:string};if(!response.ok)return NextResponse.json({error:payload.detail||"Goldie could not prepare Etsy details."},{status:502});
  const match=payload.output?.match(/\{[\s\S]*\}/);if(!match)return NextResponse.json({error:"Goldie could not read the prepared Etsy details."},{status:502});
  const raw=JSON.parse(match[0]) as Partial<Details>,record=(input:unknown)=>Object.fromEntries(Object.entries(input&&typeof input==="object"?input:{}).map(([k,v])=>[clean(k).slice(0,60),clean(v).slice(0,120)]).filter(([k,v])=>k&&v));
  return NextResponse.json({details:{category:clean(raw.category)||"Needs review",attributes:record(raw.attributes),optional:record(raw.optional),blurb:clean(raw.blurb),confidence:raw.confidence==="high"?"high":"review"} satisfies Details});
}
