"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { phrasesFromErank } from "../seo-utils";
type List = { id: string; name: string; keywords: string[] };
export default function KeywordBanks() {
  const [lists,setLists]=useState<List[]>([]),[name,setName]=useState(""),[raw,setRaw]=useState(""),[message,setMessage]=useState("");
  const reload=()=>fetch("/api/keyword-lists").then(r=>r.json()).then(r=>setLists(r.lists||[]));
  useEffect(()=>{void reload()},[]);
  const words=phrasesFromErank(raw.replace(/;/g,"\n"));
  async function save(){const response=await fetch("/api/keyword-lists",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,keywords:words})});setMessage(response.ok?"Keyword bank saved.":"That keyword bank could not be saved.");if(response.ok){setName("");setRaw("");void reload()}}
  async function remove(list:List){if(!window.confirm(`Delete “${list.name}”?`))return;await fetch("/api/keyword-lists",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:list.id})});void reload()}
  return <main className="management-page"><nav className="management-nav"><Link href="/">Listing Factory</Link><Link className="active" href="/keywords">Keyword Banks</Link><Link href="/mockups">Mockup Sets</Link><Link href="/usage">Usage + Plan</Link></nav><header><p className="mini-label">KEYWORD LIBRARY</p><h1>Your keyword banks</h1><p>Import organized eRank phrases once, then choose the right bank inside any product recipe or listing batch.</p></header><section className="management-create"><h2>Create a keyword bank</h2><label>Bank name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Example: Western shirts"/></label><label>eRank phrases or CSV column<textarea value={raw} onChange={e=>setRaw(e.target.value)} rows={6} placeholder="Paste one keyword phrase per line"/></label><label>Or upload an eRank CSV or text file<input type="file" accept=".csv,.txt,text/csv,text/plain" onChange={async e=>{const file=e.target.files?.[0];if(file)setRaw(await file.text());e.currentTarget.value=""}}/></label><div className="management-create-foot"><span>{words.length} valid phrases found</span><button disabled={!name.trim()||!words.length} onClick={()=>void save()}>Save keyword bank</button></div>{message&&<p>{message}</p>}</section><section className="bank-library"><div><h2>Saved banks</h2><span>{lists.length} total</span></div>{!lists.length?<p>No keyword banks yet.</p>:<div className="bank-grid">{lists.map(list=><article key={list.id}><div><h3>{list.name}</h3><button onClick={()=>void remove(list)}>Delete</button></div><p>{list.keywords.length} phrases</p><div>{list.keywords.slice(0,12).map(word=><span key={word}>{word}</span>)}</div>{list.keywords.length>12&&<small>+ {list.keywords.length-12} more</small>}</article>)}</div>}</section></main>
}
